"""Run all checks for the S^2 zero-mode toy and write RESULTS.md (never hand-edit it).

Rules and conventions are fixed in README.md, written before this script was run.
Nothing here derives the Standard Model or any quantum-gravity result.
"""
import datetime
import math
import os
import sys

import numpy as np
import sympy as sp

import anomalies as AN
import monopole as MP
import overlaps as OV

HERE = os.path.dirname(os.path.abspath(__file__))
L = []
w = L.append


def yn(b):
    return "YES" if b else "NO"


def chir_str(c):
    return {1: "+1 (4D left)", -1: "-1 (4D right)"}.get(c, "-")


def main():
    now = datetime.datetime.now().astimezone()
    z = now.strftime("%z")
    w("# RESULTS (generated by run.py - do not edit by hand)")
    w("")
    w("**Signed off 2026-10-02:** Venus (maths, PASS) and Helios (physics, PARTIAL: fermion table sound; Yukawa sector needs gauge-Higgs embedding).")
    w("")
    w("Generated: %s (local time, UTC%s:%s)" % (now.strftime("%Y-%m-%d %H:%M:%S"), z[:3], z[3:]))
    w("Python %s, numpy %s, sympy %s" % (sys.version.split()[0], np.__version__, sp.__version__))
    w("")
    w("Toy bookkeeping on a smooth round S^2 [by construction]. It does not derive the Standard Model "
      "and no quantum-gravity result follows.")
    w("")

    # ------------------------------------------------------------------ check 1
    w("## Check 1: zero modes need flux; count table for n = -4..4 (charge-1 field)")
    w("")
    w("(a) lowest-Landau-level formula 2j+1, j = |q| - 1/2 [standard]; (b) harmonic-basis Dirac matrix "
      "[computed; uses the standard eigenvalue formula, so not independent]; (c) finite differences of the "
      "explicit Dirac operator, N = 4000 grid points, D^2 eigenvalues below 0.5 counted [computed, independent].")
    w("")
    w("| n | q = n/2 | (a) LLL count | (b) count | (b) chiralities | (b) smallest non-zero abs D | (c) count sigma3=+1 | (c) count sigma3=-1 | (c) m values | all agree | 4D chirality of the modes |")
    w("|---|---|---|---|---|---|---|---|---|---|---|")
    table = {}
    for n in range(-4, 5):
        q = sp.Rational(n, 2)
        a_cnt = int(2 * (abs(q) - sp.Rational(1, 2)) + 1) if n != 0 else 0
        b_cnt, b_ch, b_gap, _ = MP.dirac_harmonic_basis(n)
        c_cnt, c_ms = MP.dirac_fd_count(n, N=4000)
        c_tot = c_cnt[+1] + c_cnt[-1]
        b_signs = sorted(set(int(round(x)) for x in b_ch))
        c_signs = [s for s in (+1, -1) if c_cnt[s]]
        agree = (a_cnt == b_cnt == c_tot) and (n == 0 or (b_signs == [int(np.sign(n))] and c_signs == [int(np.sign(n))]))
        table[n] = (a_cnt, b_cnt, c_tot, c_signs)
        msv = c_ms[+1] if c_cnt[+1] else c_ms[-1]
        w("| %d | %s | %d | %d | %s | %.6f | %d | %d | %s | %s | %s |" % (
            n, q, a_cnt, b_cnt, ",".join("%+d" % s for s in b_signs) or "-", b_gap, c_cnt[+1], c_cnt[-1],
            ", ".join(str(sp.nsimplify(m)) for m in msv) or "-", yn(agree),
            chir_str(c_signs[0]) if c_signs else "none (no zero modes)"))
    w("")
    w("Exact smallest non-zero |D| on the unit sphere is sqrt(|n| + 1) [standard]; for n = 0 it is 1, so "
      "there are no zero modes without flux (Lichnerowicz) [standard, expected].")
    w("")
    w("Convergence of the finite-difference eigenvalues of D^2 (exact values in brackets) [computed]:")
    w("")
    w("| case | N = 1000 | N = 4000 | N = 16000 |")
    w("|---|---|---|---|")
    cases = [("n=3, sigma3=+1, m=1/2 (edge zero mode) [0]", 3, 0.5, +1, 0),
             ("n=3, sigma3=+1, m=3/2 (middle zero mode) [0]", 3, 1.5, +1, 0),
             ("n=3, sigma3=+1, m=1/2, next level [4]", 3, 0.5, +1, 1),
             ("n=0, sigma3=+1, m=1/2, lowest [1]", 0, 0.5, +1, 0)]
    conv_rows = []
    for label, n, m, ch, k in cases:
        vals = [MP.fd_lowest(n, m, ch, N, k) for N in (1000, 4000, 16000)]
        conv_rows.append((label, vals))
        w("| %s | %.5f | %.5f | %.5f |" % (label, *vals))
    w("")
    w("Eigenvalue x ln N diagnostic [computed; the edge-mode values are expected to be about 1.2-1.3]:")
    w("")
    w("| case | N = 1000 | N = 4000 | N = 16000 |")
    w("|---|---|---|---|")
    for label, vals in conv_rows:
        w("| %s | %.5f | %.5f | %.5f |" % (label, *(val * math.log(N) for val, N in zip(vals, (1000, 4000, 16000)))))
    w("")
    w("The edge-mode convergence is logarithmic, as expected for a borderline inverse-square pole [computed + standard].")
    w("The n = 0 level has the same bias: at N = 16000 it is %.5f versus exact 1 [computed]." % conv_rows[-1][1][-1])
    w("The middle zero mode is already at 0. At every grid size the zero-mode candidates stay well below the threshold 0.5 and the first non-zero levels stay above 1, so the counts are unaffected by N [computed].")
    w("")
    w("Chiral projector from the flux sign: with Gamma7 = gamma5 x sigma3 and 6D Weyl Gamma7 = -1 "
      "[assumed convention], sigma3 = +1 zero modes are 4D left-handed. A 6D Weyl field with x n > 0 "
      "therefore gives ONLY left-handed 4D zero modes, and x n < 0 gives only right-handed ones "
      "[computed: every row above has a single chirality]. Putting SU(2)_L doublets at x n > 0 means only "
      "left-handed doublets couple to SU(2)_L; nothing is projected by hand.")
    w("")
    w("m-label map [identity]: Check 1 uses the rotating-frame m; Check 4 uses m_phi = m_J + q in the north patch (e.g. 1/2 = -1 + 3/2).")
    w("")

    # ------------------------------------------------------------------ check 2
    w("## Check 2: three copies")
    w("")
    target = 3
    n3 = min(n for n in range(1, 5) if table[n][2] == target)
    w("Target number of copies = %d [assumed]. Smallest n > 0 whose computed count is %d: **n = %d** [computed]. "
      "All fields below use this flux." % (target, target, n3))
    w("")
    n = n3

    # ------------------------------------------------------------------ check 3
    w("## Check 3: anomaly filter (4D, one generation, left-handed Weyl fields)")
    w("")
    w("Checked [computed, exact]: SU(3)^2 U(1)_Y, SU(2)^2 U(1)_Y, U(1)_Y^3, grav^2 U(1)_Y, SU(3)^3, and the Witten "
      "SU(2) global anomaly. Scan: Y_Q = 1/6 fixed; every other Y = k/6, k = -6..6.")
    w("")
    survivors_main = None
    for with_nu in (False, True):
        tested, surv, fields = AN.scan(with_nu)
        w("### %s nu^c: %d assignments tested, %d survive" % ("With" if with_nu else "Without", tested, len(surv)))
        w("")
        names = [f[0] for f in fields]
        w("| # | " + " | ".join("Y(%s)" % nm for nm in names) + " | SU(3)^2 U(1) | SU(2)^2 U(1) | U(1)^3 | grav^2 U(1) | SU(3)^3 |")
        w("|---|" + "---|" * (len(names) + 5))
        for i, (s, A) in enumerate(surv, 1):
            w("| %d | " % i + " | ".join(str(sp.Rational(s[nm].numerator, s[nm].denominator)) for nm in names)
              + " | %s | %s | %s | %s | %s |" % (A["SU(3)^2 U(1)"], A["SU(2)^2 U(1)"], A["U(1)^3"], A["grav^2 U(1)"], A["SU(3)^3"]))
        w("")
        if not with_nu:
            for s, A in surv:
                if s["u^c"] == AN.F(-2, 3):
                    survivors_main = s
    w("Reading [standard, expected]: without nu^c the only survivors are the SM hypercharges and the same set "
      "with the names u^c and d^c swapped (identical content). With nu^c, the survivors are the SM line plus "
      "the B-L direction, a one-parameter family on this grid (pairs related by swapping the names e^c and nu^c "
      "are the same content).")
    w("B-L line [standard]: Y = a Y_SM + b (B-L), with a + 2b = 1; equivalently Venus form Y_a = a Y_SM + (1-a)/2 (B-L). On the grid a = 1, 2/3, 1/3, 0; one row is pure (B-L)/2. With nu^c, anomalies alone cannot fix the hypercharge; only the Yukawa/Higgs charge choice picks a = 1.")
    w("")
    w("SU(3)^3 per generation [identity]: Q gives 2 triplets (+2), u^c and d^c give one antitriplet each (-1, -1); "
      "total 2 - 1 - 1 = 0 for any Y (vector-like colour content).")
    w("")
    wd = AN.witten_doublets(AN.FIELDS)
    w("Witten SU(2) global anomaly [computed]: doublets per generation = 3 (Q, one per colour) + 1 (L) = %d; "
      "even: %s." % (wd, yn(wd % 2 == 0)))
    w("")
    w("Exact sums for the SM survivor, term by term [computed]:")
    w("")
    Ysm = {k: sp.Rational(v.numerator, v.denominator) for k, v in survivors_main.items()}
    yQ, yu, yd, yL, ye = Ysm["Q"], Ysm["u^c"], Ysm["d^c"], Ysm["L"], Ysm["e^c"]
    w("- SU(3)^2 U(1): 2(%s) + (%s) + (%s) = %s" % (yQ, yu, yd, 2 * yQ + yu + yd))
    w("- SU(2)^2 U(1): 3(%s) + (%s) = %s" % (yQ, yL, 3 * yQ + yL))
    w("- U(1)^3: 6(%s)^3 + 3(%s)^3 + 3(%s)^3 + 2(%s)^3 + (%s)^3 = %s + %s + %s + %s + %s = %s" % (
        yQ, yu, yd, yL, ye, 6 * yQ**3, 3 * yu**3, 3 * yd**3, 2 * yL**3, ye**3, 6 * yQ**3 + 3 * yu**3 + 3 * yd**3 + 2 * yL**3 + ye**3))
    w("- grav^2 U(1): 6(%s) + 3(%s) + 3(%s) + 2(%s) + (%s) = %s" % (yQ, yu, yd, yL, ye, 6 * yQ + 3 * yu + 3 * yd + 2 * yL + ye))
    w("- with nu^c at Y = 0 the sums are unchanged (it adds 0).")
    w("")
    # U(1)_X anomalies of the zero-mode content
    Xleft = {"Q": 1, "L": 1, "u^c": 1, "d^c": 1, "e^c": 1, "nu^c": 1}
    Ynu = dict(Ysm); Ynu["nu^c"] = sp.Integer(0)
    XA = AN.x_anomalies(Xleft, Ysm, AN.FIELDS)
    XAn = AN.x_anomalies(Xleft, Ynu, AN.FIELDS + [AN.NU])
    w("### U(1)_X mixed anomalies of the zero modes (3 copies) [computed]")
    w("")
    w("Left-handed U(1)_X charges: Q, L have x = +1; u^c, d^c, e^c (nu^c) are conjugates of x = -1 fields, so "
      "x = +1 as left-handed fields.")
    w("")
    w("T = 1 normalisation (common T(R) = 1/2 factored out)")
    w("")
    w("| anomaly | without nu^c | with nu^c | cancels |")
    w("|---|---|---|---|")
    for k in XA:
        w("| %s | %s | %s | %s |" % (k, XA[k], XAn[k], yn(XA[k] == 0 and XAn[k] == 0)))
    w("")
    w("U(1)_X does not cancel in 4D. In 6D flux models this is usually handled by a Green-Schwarz mechanism "
      "that makes U(1)_X massive [standard, expected]; that is [not checked] here.")
    w("")
    w("Green-Schwarz precision [standard, not computed]: the 4D U(1)_X anomalies come from reducing the 6D anomaly polynomial on the integral of F_X = n, so they scale with n. They are cancelled by the reduced 6D GS term B wedge F_X. The B_mu_nu axion is eaten, U(1)_X becomes a massive Z' near the compactification scale, and it survives as a global selection rule that enforces the x-closure on the Yukawas. Because SU(2)^2X, SU(3)^2X and Y^2X are non-zero, the axion couples to WW~, GG~ and BB~ (generalised Chern-Simons terms needed).")
    w("")
    w("Anomalies NOT checked [not checked]:")
    w("- Irreducible 6D anomalies. Venus's count: the current all-Gamma_7 = -1 model has a net 15 Weyl (16 with nu^c) for tr R^4, so it needs extra matter or tensors [not checked]. The condition n_H - n_V + 29 n_T = 273 applies to 6D (1,0) supergravity; nothing here says this toy is supersymmetric [standard, not checked].")
    w("- Any cure for the 4D U(1)_X anomalies above [not checked].")
    w("- SU(2)^3 (identically zero for SU(2)) [standard].")
    w("- Global anomalies other than Witten's SU(2) [not checked].")
    w("- Background stability (radion, flux sector) [not checked].")
    w("")

    # ------------------------------------------------------------------ check 4
    w("## Check 4: Yukawas from triple overlaps")
    w("")
    w("### Harmonic sanity checks [computed]")
    w("")
    ph = np.linspace(0, 2 * math.pi, 7)
    worstN = worstS = 0.0
    for (q, l, m) in [(1, 1, -1), (1, 1, 0), (1, 1, 1), (2, 2, -2), (-1, 1, 1), (sp.Rational(3, 2), sp.Rational(3, 2), sp.Rational(1, 2))]:
        qf, lf, mf = float(q), float(l), float(m)
        vN = MP.Y_north(qf, lf, mf, np.zeros_like(ph), ph)
        vS = MP.Y_south(qf, lf, mf, np.full_like(ph, math.pi), ph)
        worstN = max(worstN, float(np.max(np.abs(vN - vN[0]))))
        worstS = max(worstS, float(np.max(np.abs(vS - vS[0]))))
    w("- Y^N at the north pole and Y^S at the south pole are the same for every phi (the sections are smooth "
      "in their own patch): largest spread %.1e (north), %.1e (south)." % (worstN, worstS))
    orth = []
    for (a, b) in [((1, 1, 0), (1, 1, 0)), ((1, 1, 1), (1, 1, 1)), ((1, 1, 1), (1, 1, 0)), ((2, 2, 1), (2, 2, 1))]:
        val = OV.triple_quadrature(*a, *b, 0, 0, 0) * math.sqrt(4 * math.pi)
        orth.append((a, b, val))
    w("- Normalisation by two-patch quadrature, integral of conj(Y_a) Y_b: " + "; ".join(
        "a=%s, b=%s: %.12f" % (a, b, v.real) for a, b, v in orth))
    w("")
    w("### Exact overlap (sympy wigner_3j) vs two-patch quadrature [computed]")
    w("")
    w("| (q1,l1,m1; q2,l2,m2; q3,l3,m3) | exact | exact value | quadrature | abs difference |")
    w("|---|---|---|---|---|")
    tests = [(1, 1, 0, 2, 2, 0, -1, 1, 0), (1, 1, 1, 2, 2, 2, -1, 1, -1), (1, 1, -1, 2, 2, -1, -1, 1, 0),
             (1, 1, 1, 0, 0, 0, 1, 1, 1), (1.5, 1.5, 0.5, 0.5, 0.5, 0.5, 1, 1, 0), (1, 1, 0, 2, 2, 1, -1, 1, 0)]
    for t in tests:
        ex = OV.triple_exact(*t)
        qd = OV.triple_quadrature(*t)
        exv = complex(sp.N(ex))
        w("| %s | %s | %.12f | %.12f %+.1ei | %.1e |" % (
            ", ".join(str(sp.nsimplify(x)) for x in t), sp.simplify(ex), exv.real, qd.real, qd.imag, abs(qd - exv)))
    w("")
    w("The last row breaks m conservation (0 != 1 + 0), so both give zero [identity].")
    w("")

    # flux assignments
    half = sp.Rational(1, 2)
    nR = sp.Integer(n)

    def Qeff_fermion(x):
        q = sp.Rational(x) * nR / 2
        return q, q - sp.sign(q) * half

    xL, xR = 1, -1
    qL, QL = Qeff_fermion(xL)
    qR, QR = Qeff_fermion(xR)
    assignments = [
        ("A", "main: doublets x=+1, singlets x=-1, Higgs x=+2 (q=3, Q_H = q-1 = 2, lowest level j=2)",
         QL, abs(QL), QR, abs(QR), sp.Integer(2), sp.Integer(2), (qL, sp.Integer(3), qR)),
        ("B", "alternative: neutral scalar Higgs (x=0, Q_H=0, j=0); singlets x=+1 (same sign as doublets)",
         QL, abs(QL), QL, abs(QL), sp.Integer(0), sp.Integer(0), (qL, sp.Integer(0), qL)),
        ("C", "alternative: as A but Higgs from the next level (Q_H = 2, j = 3)",
         QL, abs(QL), QR, abs(QR), sp.Integer(2), sp.Integer(3), (qL, sp.Integer(3), qR)),
    ]
    summary = []
    for tag, desc, QLa, lLa, QRa, lRa, QH, lH, bare in assignments:
        w("### Assignment %s [assumed flux assignment]: %s" % (tag, desc))
        w("")
        w("- Wavefunction charges: Q_L = %s (j = %s), Q_R = %s (j = %s), Q_H = %s (j = %s). Closure -Q_L + Q_H + Q_R = %s. "
          "Bare flux charges q: -(%s) + (%s) + (%s) = %s. m rule: m_L = m_H + m_R. [computed]"
          % (QLa, lLa, QRa, lRa, QH, lH, -QLa + QH + QRa, bare[0], bare[1], bare[2], -bare[0] + bare[1] + bare[2]))
        if tag == "B":
            w("- Both fermions here have sigma3 = +1, i.e. both are 4D left-handed, so the 4D coupling "
              "(left-bar)(H)(left) vanishes by Lorentz symmetry [identity]. Matrices are bookkeeping only.")
        if tag == "A":
            w("- Up, down and lepton sectors have the same flux charges (H_u and H_d both x = +2), so their "
              "matrices are identical up to an overall coupling [assumed = 1]. Shown once for all three.")
        w("")
        nmodes = int(2 * lH + 1)
        w("| Higgs mode m_H | matrix (rows m_L = -1,0,1; cols m_R = -1,0,1), exact | rank | singular values / largest |")
        w("|---|---|---|---|")
        ranks = []
        for i in range(nmodes):
            mH = -lH + i
            M, _, _ = OV.overlap_matrix(QLa, lLa, QH, lH, mH, QRa, lRa)
            rk, s, rat = OV.rank_and_ratios(M)
            ranks.append((mH, rk, rat))
            ms = "[" + "; ".join(", ".join(str(sp.simplify(M[r, c])) for c in range(M.shape[1])) for r in range(M.shape[0])) + "]"
            w("| %s | %s | %d | %s |" % (mH, ms, rk, ", ".join("%.6f" % x for x in rat) if rat else "-"))
        w("")
        if tag == "C":
            w("Assignment C rank 0 [identity: triangle rule, j_H <= j_L + j_R = 2].")
        w("Tag: [schematic; depends on flux assignment].")
        w("")
        summary.append((tag, ranks))
    # single-Higgs check
    QHt = -2
    Qu_needed = QL - QHt
    w("### Why two Higgs doublets in A [computed]")
    w("")
    w("With only H_d (Q_H = 2), the up sector must use its conjugate H~ (Q = %d). Closure -Q_L + Q_H~ + Q_u = 0 then "
      "needs Q_u = %s, i.e. j = %s and %d zero modes with sigma3 = +1 (4D left-handed, the wrong chirality for u_R). "
      "So one Higgs cannot give 3 right-handed up-type modes here; A uses a second doublet H_u [assumed]."
      % (QHt, Qu_needed, abs(Qu_needed), int(2 * abs(Qu_needed) + 1)))
    w("")
    w("Higgs mechanism note [identity]: in 6D a scalar Yukawa between Weyl fermions of the SAME 6D chirality vanishes identically, because Gamma^0 anticommutes with Gamma_7. All fermions here have Gamma_7 = -1, so the Higgs must be an internal gauge-field component A_z (spin weight 1), i.e. gauge-Higgs unification. That is why the charge is spin-shifted.")
    w("The flux sits only in U(1)_X and no SM gauge boson carries X, so there is no Nielsen-Olesen tachyon in the W/gluon sector [standard].")
    w("Tachyon formula [computed + standard: RSS 1983]: M^2 R^2 = j(j+1) - q^2 with j >= |q| - 1. At the lowest level M^2 = -|q|/R^2 exactly, with no curvature correction.")
    tachyon_rows = [(3, 2, -3, 5, "lowest level"), (3, 3, 3, 7, "next level"), (3, "other helicity", 11, "-", "other-helicity lowest = 3q + 2")]
    w("| q | j | M^2 R^2 | degeneracy | note |")
    w("|---|---|---|---|---|")
    for qv, jv, mass2, degeneracy, note in tachyon_rows:
        w("| %s | %s | %s | %s | %s |" % (qv, jv, mass2, degeneracy, note))
    w("q = 3 gives j = 2 with M^2 = -3/R^2 and 5 modes, j = 3 with +3/R^2; the other helicity's lowest is (3q+2)/R^2 = 11/R^2 > 0 [computed].")
    w("Tachyonic Higgs = EWSB at the compactification scale [standard: tachyonic Higgs = EWSB at the compactification scale]: the Higgs mass is tied to 1/R, so the hierarchy is unexplained.")
    w("H_u and H_d [requires gauge-Higgs embedding, not specified]: a doublet in A_M needs e.g. SU(3)_w or G2; SU(3)_w gives tree-level sin^2 theta_W = 3/4.")
    w("Yukawa = gauge coupling x 3j overlap [standard + computed], so the identical up, down and lepton matrices are a structural prediction: there is no tree-level flavour hierarchy.")
    w("There are 5 degenerate tachyonic doublets per Higgs; only the m_H = 0 vev preserves the S^2 U(1) rotation [standard].")
    w("The H_u/H_d hypercharge labels are opposite to the MSSM convention, but they are internally consistent with psi_bar_L H psi_R [identity].")
    w("")
    w("Plain statement: on a round S^2, rotation symmetry (m conservation) fixes the sparsity pattern of every "
      "matrix above. Any realistic mass hierarchy needs extra [assumed] input, such as Wilson lines, a deformed "
      "metric, localised sources or a chosen Higgs vev profile. None is added here.")
    w("")

    # ------------------------------------------------------------------ check 5
    w("## Check 5: geometry note")
    w("")
    w("The S^2 here is smooth and round [by construction]. It is NOT the branched Pair A double cover. "
      "A GoldbergHexa lattice version is deferred (useful later only as a fermion-doubling check).")
    w("")

    # ------------------------------------------------------------------ check 6
    w("## Check 6: final table of surviving modes (SM survivor, n = %d)" % n)
    w("")
    w("| multiplet (6D field) | SU(3)xSU(2)xU(1)_Y | Y | as 4D left-handed field | U(1)_X charge x | flux charge q = x n/2 | zero modes | 4D chirality |")
    w("|---|---|---|---|---|---|---|---|")
    rows = [("Q_L", "(3,2)", Ysm["Q"], "Q (3,2,%s)" % Ysm["Q"], 1),
            ("u_R", "(3,1)", -Ysm["u^c"], "u^c (3bar,1,%s)" % Ysm["u^c"], -1),
            ("d_R", "(3,1)", -Ysm["d^c"], "d^c (3bar,1,%s)" % Ysm["d^c"], -1),
            ("L_L", "(1,2)", Ysm["L"], "L (1,2,%s)" % Ysm["L"], 1),
            ("e_R", "(1,1)", -Ysm["e^c"], "e^c (1,1,%s)" % Ysm["e^c"], -1),
            ("nu_R (optional)", "(1,1)", sp.Integer(0), "nu^c (1,1,0)", -1)]
    for name, rep, Y, left, x in rows:
        q = sp.Rational(x) * n / 2
        cnt = table[x * n][2]
        ch = table[x * n][3][0]
        w("| %s | %s | %s | %s | %+d | %s | %d | %s |" % (name, rep, Y, left, x, q, cnt, "left" if ch > 0 else "right"))
    w("| H_d (Higgs, A) [requires gauge-Higgs embedding, not specified] | (1,2) | 1/2 | boson | +2 | 3 | 5 (Q_H = 2, j = 2) [assumed spin-weight shift] | - |")
    w("| H_u (Higgs, A) [requires gauge-Higgs embedding, not specified] | (1,2) | -1/2 | boson | +2 | 3 | 5 (Q_H = 2, j = 2) [assumed spin-weight shift] | - |")
    w("")
    w("Fermion counts and chiralities [computed] (from the check 1 table at x n = +-%d). Hypercharges [computed] "
      "(anomaly survivor; the u^c <-> d^c relabelled survivor is the same content). Higgs rows are [assumed]." % n)
    w("")
    w("### Coupling ranks and ratios [schematic; depends on flux assignment]")
    w("")
    w("| assignment | Higgs mode m_H | rank | singular values / largest |")
    w("|---|---|---|---|")
    for tag, ranks in summary:
        for mH, rk, rat in ranks:
            w("| %s | %s | %d | %s |" % (tag, mH, rk, ", ".join("%.4f" % x for x in rat) if rat else "-"))
    w("")
    w("## NOTES ONLY")
    w("")
    w("### Alternative model (Helios), not run unless Akitti asks")
    w("")
    w("Singlets at Gamma_7 = +1, x = +1. Still right-handed in 4D; a scalar Yukawa is allowed; a neutral scalar Higgs (x = 0, j = 0, no tachyon) makes Assignment B Lorentz-allowed (rank 3, equal singular values). [notes only; not run]")
    w("Per-generation X anomalies with nu^c (T = 1), milled by Venus: SU(3)^2X = 0, SU(2)^2X = 4, Y^2X = -2, YX^2 = 0, X^3 = grav^2X = 0 (both 1 without nu^c); over three generations, 12 and -6. [notes only; not run]")
    w("Irreducible 6D tr R^4 and tr F^4_SU(3) cancel (8 vs 8 Weyl, 2 vs 2 triplets), leaving only reducible parts for GS. [notes only; not run]")
    w("")
    w("Fermion content, chirality and SM hypercharges follow from n = 3 flux [computed]; with one 6D chirality the Higgs must be a gauge-field component, which is tachyonic (EWSB at 1/R) and gives universal, hierarchy-free Yukawas [standard + computed]; U(1)_X needs 6D GS and becomes a massive Z′ [standard, not checked].")
    w("")
    w("End of results. No Standard-Model derivation and no quantum-gravity claim is made.")
    with open(os.path.join(HERE, OUT_DEFAULT[0]), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")
    print("\n".join(L))


# ======================================================================================
# Alternative model (Helios, approved by Akitti 2026-10-02). Run with:  python run.py --model alt
# Writes ONLY RESULTS_alt.md. Reuses the exact harmonic-basis counts, the anomaly scan and the
# exact 3j overlaps. No finite-difference sweep is run in this mode.
# ======================================================================================
OUT_DEFAULT = ["RESULTS.md"]

ALT_CRITERIA = [
    "1. Each field has three copies with the correct 4D chirality.",
    "2. The anomaly filter still returns the SM hypercharges.",
    "3. The Yukawa overlap \u222b_{S^2} psibar_Q H psi_u is nonzero now that the fermions have opposite 6D chirality. "
    "Report its rank and its three singular values. Prediction (Venus's corrected wording, use this verbatim): "
    "'The coupling uses psibar_Q, which is complex-conjugated, so the modes pair as m_Q = m_u. With a constant Higgs "
    "Y_H = 1/sqrt(4 pi), the overlap is the orthonormality of two identical j = 1 sections: "
    "\u222b psibar_{Q,m} H psi_{u,m\u2032} = (1/sqrt(4 pi)) delta_{m m\u2032}. So the prediction is a diagonal matrix with "
    "entries 1/(2 sqrt(pi)), rank 3 and three exactly equal singular values [identity].' It's a check, not a target. "
    "Real masses come out, but all three generations are identical; splitting them needs something that breaks the "
    "round sphere's symmetry, which isn't part of this run. Also do the down and lepton matrices.",
    "4. Print the per-generation 4D anomaly table, then the totals over three generations (T = 1 normalisation, exact "
    "fractions): SU(3)^2X = 0, SU(2)^2X = 4 (12), Y^2X = -2 (-6), YX^2 = 0, X^3 = grav^2X = 0 (these two need nu^c; "
    "print the without-nu^c values too, expected 1 each).",
    "5. The irreducible 6D anomalies cancel: tr R^4 has 8 Weyl fields at Gamma_7 = -1 (Q 6, L 2) against 8 at +1 "
    "(u, d, e, nu), and tr F^4_SU(3) has 2 triplets against 2. Compute the counts. Anything left over goes to "
    "Green-Schwarz, which makes Z' massive [standard, not computed].",
    "6. The Higgs has no flux tachyon: x = 0 gives the lowest M^2 R^2 = 0 at tree level (j = 0). Print the scalar "
    "spectrum l(l+1) for the first few levels.",
]


def run_alt():
    L = []
    w = L.append
    now = datetime.datetime.now().astimezone()
    z = now.strftime("%z")
    w("# RESULTS_alt (generated by run.py --model alt - do not edit by hand)")
    w("")
    w("Generated: %s (local time, UTC%s:%s)" % (now.strftime("%Y-%m-%d %H:%M:%S"), z[:3], z[3:]))
    w("Python %s, numpy %s, sympy %s" % (sys.version.split()[0], np.__version__, sp.__version__))
    w("")
    w("Alternative model (Helios, approved by Akitti 2026-10-02). Toy bookkeeping on a smooth round S^2 "
      "[by construction]. It does not derive the Standard Model and no quantum-gravity result follows. "
      "The default model's RESULTS.md is not touched by this mode.")
    w("")
    w("## Pass criteria (fixed in README.md before this run, printed before any result)")
    w("")
    for c in ALT_CRITERIA:
        w(c)
        w("")
    w("## Setup [assumed input]")
    w("")
    n = 3
    w("Same S^2 (R = 1), U(1)_X flux n = %d, no flux in the SM gauge fields. Q and L: Gamma_7 = -1, x = +1. "
      "Singlets u, d, e, nu: Gamma_7 = +1, x = +1. Higgs: ordinary 6D scalar doublet, x = 0 (no flux); its "
      "potential (mu^2 < 0) is [assumed input]. 4D chirality: gamma5 = Gamma_7 x sigma3, gamma5 = -1 is "
      "left-handed [same convention as the default model]." % n)
    w("")
    half = sp.Rational(1, 2)
    # (name, SU3 dim, SU2 dim, Gamma7, x, Y of the 6D field, left-handed name, Y_left)
    fields = [("Q", 3, 2, -1, 1, sp.Rational(1, 6), "Q", sp.Rational(1, 6)),
              ("L", 1, 2, -1, 1, sp.Rational(-1, 2), "L", sp.Rational(-1, 2)),
              ("u", 3, 1, +1, 1, sp.Rational(2, 3), "u^c", sp.Rational(-2, 3)),
              ("d", 3, 1, +1, 1, sp.Rational(-1, 3), "d^c", sp.Rational(1, 3)),
              ("e", 1, 1, +1, 1, sp.Integer(-1), "e^c", sp.Integer(1)),
              ("nu", 1, 1, +1, 1, sp.Integer(0), "nu^c", sp.Integer(0))]

    # ---------------- criterion 1
    w("## Criterion 1: copies and 4D chirality [computed: exact harmonic-basis count, no FD]")
    w("")
    w("| field | (SU3, SU2) | Gamma_7 | x | q = x n/2 | zero modes | sigma3 | gamma5 = Gamma_7 sigma3 | 4D chirality | expected | ok |")
    w("|---|---|---|---|---|---|---|---|---|---|---|")
    ok1 = True
    for name, d3, d2, g7, x, Y, lname, Yl in fields:
        cnt, chir, _, _ = MP.dirac_harmonic_basis(x * n)
        s3 = sorted(set(int(round(c)) for c in chir))
        g5 = g7 * s3[0] if len(s3) == 1 else None
        hand = "left" if g5 == -1 else ("right" if g5 == +1 else "mixed")
        exp = "left" if name in ("Q", "L") else "right"
        good = (cnt == 3) and (hand == exp)
        ok1 &= good
        w("| %s | (%d,%d) | %+d | %+d | %s | %d | %s | %s | %s | %s | %s |" % (
            name, d3, d2, g7, x, sp.Rational(x * n, 2), cnt, ",".join("%+d" % v for v in s3),
            ("%+d" % g5) if g5 is not None else "mixed", hand, exp, yn(good)))
    w("")
    w("Right-handed singlet zero modes = left-handed conjugates u^c, d^c, e^c, nu^c with X = -1 [identity].")
    w("")

    # ---------------- criterion 2
    w("## Criterion 2: anomaly filter on the 4D content [computed, exact]")
    w("")
    tested, surv, _ = AN.scan(False)
    sm = {"Q": AN.F(1, 6), "u^c": AN.F(-2, 3), "d^c": AN.F(1, 3), "L": AN.F(-1, 2), "e^c": AN.F(1, 1)}
    swap = dict(sm); swap["u^c"], swap["d^c"] = sm["d^c"], sm["u^c"]
    sset = [s for s, A in surv]
    ok2 = (sm in sset) and all(s in (sm, swap) for s in sset)
    w("4D left-handed content Q, u^c, d^c, L, e^c is the same as in the default model, so the same scan applies. "
      "Without nu^c: %d tested, %d survive:" % (tested, len(surv)))
    w("")
    for s, A in surv:
        w("- " + ", ".join("Y(%s) = %s" % (k, s[k]) for k in ("Q", "u^c", "d^c", "L", "e^c"))
          + "; sums " + ", ".join("%s = %s" % (k, v) for k, v in A.items()))
    w("")
    w("SM hypercharges returned (up to the u^c <-> d^c name swap): %s." % yn(ok2))
    w("")

    # ---------------- criterion 3
    w("## Criterion 3: Yukawa overlaps with a constant Higgs [computed: exact sympy wigner_3j]")
    w("")
    w("All fermion zero modes here have q = 3/2, effective charge Q = +1, j = 1, m = -1, 0, 1. The Higgs is the "
      "constant mode Y_{0,0,0} = 1/sqrt(4 pi). Closure: -x_Q + x_H + x_u = -1 + 0 + 1 = 0 and "
      "-Q_Q + Q_H + Q_u = -1 + 0 + 1 = 0 [identity]. Opposite Gamma_7, so psibar psi is allowed by 6D chirality "
      "[identity]. Up uses H~ = i sigma2 H*, which is also the constant mode.")
    w("")
    expected = sp.Rational(1, 2) / sp.sqrt(sp.pi)
    ok3 = True
    w("| sector | coupling | matrix (rows m_Q or m_L = -1,0,1; cols m_R = -1,0,1), exact | rank | singular values | all equal to 1/(2 sqrt(pi)) |")
    w("|---|---|---|---|---|---|")
    for sector, coup in (("up", "psibar_Q H~ psi_u"), ("down", "psibar_Q H psi_d"), ("lepton", "psibar_L H psi_e")):
        M, _, _ = OV.overlap_matrix(1, 1, 0, 0, 0, 1, 1)
        rk, s, rat = OV.rank_and_ratios(M)
        diag_ok = all(sp.simplify(M[i, j] - (expected if i == j else 0)) == 0 for i in range(3) for j in range(3))
        sv_ok = rk == 3 and float(np.max(np.abs(s - float(expected)))) < 1e-12
        ok3 &= diag_ok and sv_ok
        ms = "[" + "; ".join(", ".join(str(sp.simplify(M[r, c])) for c in range(3)) for r in range(3)) + "]"
        w("| %s | %s | %s | %d | %s | %s |" % (sector, coup, ms, rk, ", ".join("%.12f" % x for x in s), yn(diag_ok and sv_ok)))
    w("")
    qd = OV.triple_quadrature(1, 1, 0, 0, 0, 0, 1, 1, 0)
    w("Two-patch quadrature cross-check of the m = 0 diagonal entry: %.12f (exact %.12f) [computed]." % (qd.real, float(expected)))
    w("Reading [identity]: diagonal, rank 3, three equal singular values 1/(2 sqrt(pi)) = %.12f. Real masses, but "
      "the three generations are identical; splitting them needs something that breaks the round sphere's symmetry "
      "[assumed input, not part of this run]." % float(expected))
    w("")

    # ---------------- criterion 4
    w("## Criterion 4: 4D U(1)_X anomalies (T = 1 normalisation, exact) [computed]")
    w("")
    Xl = {"Q": 1, "L": 1, "u^c": -1, "d^c": -1, "e^c": -1, "nu^c": -1}
    Yl = {"Q": sp.Rational(1, 6), "u^c": sp.Rational(-2, 3), "d^c": sp.Rational(1, 3), "L": sp.Rational(-1, 2),
          "e^c": sp.Integer(1), "nu^c": sp.Integer(0)}
    per_nu = AN.x_anomalies(Xl, Yl, AN.FIELDS + [AN.NU], ngen=1)
    per_no = AN.x_anomalies(Xl, Yl, AN.FIELDS, ngen=1)
    tot_nu = AN.x_anomalies(Xl, Yl, AN.FIELDS + [AN.NU], ngen=3)
    tot_no = AN.x_anomalies(Xl, Yl, AN.FIELDS, ngen=3)
    exp_per = {"SU(3)^2 X": 0, "SU(2)^2 X": 4, "Y^2 X": -2, "Y X^2": 0, "X^3": 0, "grav^2 X": 0}
    exp_tot = {"SU(3)^2 X": 0, "SU(2)^2 X": 12, "Y^2 X": -6, "Y X^2": 0, "X^3": 0, "grav^2 X": 0}
    exp_no = {"X^3": 1, "grav^2 X": 1}
    w("Left-handed X charges: Q, L = +1; u^c, d^c, e^c, nu^c = -1.")
    w("")
    w("| anomaly | per generation, with nu^c | per generation, without nu^c | 3 generations, with nu^c | 3 generations, without nu^c | expected (per gen; 3 gen) | ok |")
    w("|---|---|---|---|---|---|---|")
    ok4 = True
    for k in per_nu:
        good = (per_nu[k] == exp_per[k]) and (tot_nu[k] == exp_tot[k]) and (k not in exp_no or per_no[k] == exp_no[k])
        ok4 &= good
        e = "%s; %s" % (exp_per[k], exp_tot[k]) + (" (without nu^c: %s per gen)" % exp_no[k] if k in exp_no else "")
        w("| %s | %s | %s | %s | %s | %s | %s |" % (k, per_nu[k], per_no[k], tot_nu[k], tot_no[k], e, yn(good)))
    w("")
    w("Cross-reference [hand check, Venus 2026-10-02]: per generation with left-handed charges, SU(3)^2X 2-1-1 = 0, "
      "SU(2)^2X 3+1 = 4, Y^2X = -2, YX^2 = 0, X^3 = grav^2X 8-8 = 0 (8-7 = 1 without nu^c); totals 12 and -6. Agrees with the table.")
    w("")
    w("SU(2)^2X and Y^2X do not cancel; they need Green-Schwarz, which makes U(1)_X a massive Z' [standard, not computed].")
    w("")

    # ---------------- criterion 5
    w("## Criterion 5: irreducible 6D anomalies [computed counts; only spin-1/2 fields, no gravitino or tensors assumed]")
    w("")
    minus = [(f[0], f[1] * f[2]) for f in fields if f[3] == -1]
    plus = [(f[0], f[1] * f[2]) for f in fields if f[3] == +1]
    nm = sum(d for _, d in minus); np_ = sum(d for _, d in plus)
    np_nonu = sum(d for nme, d in plus if nme != "nu")
    t_m = sum(f[2] for f in fields if f[3] == -1 and f[1] == 3)   # SU(3) triplets at Gamma_7 = -1
    t_p = sum(f[2] for f in fields if f[3] == +1 and f[1] == 3)
    w("| quantity | Gamma_7 = -1 | Gamma_7 = +1 | net | expected |")
    w("|---|---|---|---|---|")
    w("| tr R^4: 6D Weyl fields (component count) | %d (%s) | %d (%s) | %d | 8 vs 8, net 0 |" % (
        nm, ", ".join("%s %d" % m for m in minus), np_, ", ".join("%s %d" % p for p in plus), np_ - nm))
    w("| tr R^4 without nu | %d | %d | %d | - |" % (nm, np_nonu, np_nonu - nm))
    w("| tr F^4 SU(3): triplets | %d (Q: 2) | %d (u 1, d 1) | %d | 2 vs 2, net 0 |" % (t_m, t_p, t_p - t_m))
    ok5 = (nm == 8 and np_ == 8 and t_m == 2 and t_p == 2)
    w("")
    w("SU(2) and U(1) have no independent quartic Casimir, so their F^4 terms are reducible [standard]. Everything "
      "reducible is left for Green-Schwarz [standard, not computed]. Without nu the tr R^4 count is off by one.")
    w("")

    # ---------------- criterion 6
    w("## Criterion 6: Higgs has no FLUX tachyon (x = 0, no flux) [computed, tree level]")
    w("")
    w("The constant j = 0 mode has M^2 = mu^2; its sign stays [assumed input]. The l(l+1)/R^2 tower below is the "
      "flux-free KK spectrum on top of mu^2, i.e. M^2 = mu^2 + l(l+1)/R^2.")
    w("")
    w("| l | KK part (M^2 - mu^2) R^2 = l(l+1) - q^2, q = 0 | degeneracy 2l+1 |")
    w("|---|---|---|")
    levels = [(l, l * (l + 1) - 0, 2 * l + 1) for l in range(5)]
    for l, m2, dg in levels:
        w("| %d | %d | %d |" % (l, m2, dg))
    ok6 = levels[0][1] == 0 and all(m2 >= 0 for _, m2, _ in levels)
    w("")
    w("Lowest level j = 0: KK part 0, a single constant mode with M^2 = mu^2; the flux adds no tachyonic shift "
      "[computed]. Electroweak breaking then comes from the assumed potential mu^2 < 0 [assumed input], not from the flux.")
    w("")

    # ---------------- final table
    w("## PASS/FAIL")
    w("")
    w("| criterion | result |")
    w("|---|---|")
    for i, okc in enumerate((ok1, ok2, ok3, ok4, ok5, ok6), 1):
        w("| %d | %s |" % (i, "PASS" if okc else "FAIL"))
    w("")
    allok = all((ok1, ok2, ok3, ok4, ok5, ok6))
    w("Reading: %s Opposite 6D chirality for the singlets gives three left-handed doublets and three right-handed "
      "singlets per field, the SM hypercharges, and an allowed scalar Yukawa with a constant, tachyon-free Higgs. "
      "The Yukawa matrices are diagonal with three equal entries, so there's no generation splitting on the round "
      "sphere. The irreducible 6D anomalies cancel only with nu included. U(1)_X still needs Green-Schwarz. This is "
      "a toy and derives nothing." % ("all six criteria PASS." if allok else "not all criteria pass (see table)."))
    w("")
    w("Degenerate generations [standard] (Helios, note 1): the three generations are the j = 1 triplet of the "
      "sphere's SO(3), acting as a rotation combined with a gauge transformation because of the flux. That makes "
      "SO(3) an exact flavour symmetry, which forces the three equal singular values. The metric side also gives "
      "flavour-changing KK vectors at about 1/R. Splitting the generations needs SO(3) breaking (a squashed sphere, "
      "a rugby ball with conical tips, or a localised source); that is a separate later step and is not computed here.")
    w("")
    w("Units [standard] (Helios, note 2): in 6D, [y_6] = -1 (a length), because [psibar psi H] = 5 + 2 = 7 against "
      "an action density of dimension 6. With unit-normalised harmonics on a radius-R sphere, "
      "y_4 = y_6 * (1/(2 sqrt(pi))) * (1/R). The overlap fixes the coupling ratios, not their overall size. The "
      "up, down and lepton 6D couplings are free [assumed input].")
    with open(os.path.join(HERE, "RESULTS_alt.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", choices=["default", "alt"], default="default")
    ap.add_argument("--out", default="RESULTS.md", help="default model only; for verification copies")
    args = ap.parse_args()
    if args.model == "alt":
        run_alt()
    else:
        OUT_DEFAULT[0] = args.out
        main()
