#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
LIFT step L1: harness calibration against Euclidean Schwarzschild (Einstein GR) - the Gross-Perry-Yaffe negative mode.
Spec: ..\\..\\JOB_LIFT_SPEC.md (Helios; Venus-cleared 22:56, SHA-256 prefix 77D663CE, replacing 9E2B9281), section "L1, first runnable step",
plus the "Local Grok Build lift checks" section: Requirement 1 harness test [kinematic, no gravity theory] (LOCAL_LIFT_CHECKS_REVIEW.md 3D9294B7).
HARD RULE (Akitti 22:41): the lift's gravity is quantum gravity and it is UNKNOWN. Einstein GR here is ONLY a
calibration/control row [standard: GR control]. L1 has NO gravity-independent part. A pass means the harness is calibrated;
it does not mean the lift is done or unblocked.
Writes RESULTS.md (only ever written by this script). Run: $env:PYTHONIOENCODING='utf-8'; python -B run.py
"""
import os, time, platform, hashlib, zlib, math, cmath
import numpy as np
import scipy
from scipy.integrate import solve_ivp, quad
from scipy.optimize import brentq
import scipy.sparse as sps
import scipy.sparse.linalg as spla
import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))          # C:\Users\Akitt\open-problems
SPEC = os.path.join(ROOT, "JOB_LIFT_SPEC.md")
T0 = time.time()
OUT = []


def out(s=""):
    print(s, flush=True)
    OUT.append(s)


# ---------------- parameters and thresholds (fixed before the graded run) ----------------
SPEC_HASH = "77D663CE"                    # Venus 22:56; replaces 9E2B9281
REVIEW = os.path.join(ROOT, "LOCAL_LIFT_CHECKS_REVIEW.md")
REVIEW_HASH = "7F9BAA67"
M = 1.0                                   # G = 1, units of M; r+ = 2M
RP, RS = 2.0 * M, 3.0 * M                 # bolt (horizon) and Prestidge's r_s (r V' - 2V = 0)
LAM_TARGET, LAM_TOL = -0.192, 0.002       # spec pass (a): M^2 lambda = -0.192 +- 0.002 (Prestidge 5.12; Reall 1.7)
COUNT_EXPECT = 1                          # spec pass (b): exactly one negative TT s-wave mode
LAM_SCAN_LO, LAM_SCAN_HI, N_SCAN = -5.0, -0.005, 400   # scan window for the count (M^-2) [assumed]
DELTA_H = 1e-3                            # start offset from the bolt (Frobenius series to x^3) [assumed]
RHO_DETOUR = 0.5                          # radius of the complex semicircle around r_s = 3M [assumed]
KR_FAR = 30.0                             # outer radius R = max(R_MIN, KR_FAR/k), k = sqrt(-lambda) [assumed]
R_MIN = 40.0
RTOL, ATOL = 1e-12, 1e-14
IMAG_TOL = 1e-8                           # path independence (upper vs lower detour) => r_s apparent singularity [assumed]
BOLT_TOL = 1e-6                           # bolt: derived smooth period vs 8 pi M, and cone angle vs 2 pi [assumed]
GL_LPPS = 0.876                           # LPPS m2 r_h ~ 0.876 (report-only code check; LPPS cited for this number only)
GL_REALL_MU = 0.44                        # Reall: mu* = 0.44 at r+ = 2 (report only)
CONF_BOXES = [20.0, 40.0, 80.0, 160.0]    # conformal column: trace operator -Laplacian in boxes r <= R_box [finite-size]
CONF_NPTS = 4000
ACTION_R = [1e2, 1e3, 1e4, 1e5]           # on-shell action boundary radii (report only)
TIP_PERIOD_QUOTED = 12.231695             # qg-operator RESULTS.md:18 (quoted in LOCAL_LIFT_CHECKS_REVIEW.md): smooth period 2 pi/eps_EP
EPS_EP = 2 * math.pi / TIP_PERIOD_QUOTED  # = 0.5137 (spec: eps_EP ~ 0.514) [assumed: taken from the quoted period]
EPS_EP_EXTRA = [0.25, 1.0]                # same test at other eps_EP: the result is kinematic and eps_EP-independent [assumed]
GB_TOL = 1e-8                             # Requirement 1 harness test: Gauss-Bonnet sum vs 2 pi chi = 4 pi (relative) [assumed]


def crc_sha(path):
    b = open(path, "rb").read()
    return "%08X" % (zlib.crc32(b) & 0xFFFFFFFF), hashlib.sha256(b).hexdigest()[:8].upper()


AUD = [os.path.join(ROOT, f) for f in sorted(os.listdir(ROOT)) if os.path.isfile(os.path.join(ROOT, f))]
before = {f: crc_sha(f) for f in AUD}

out("# LIFT L1 - harness calibration on Euclidean Schwarzschild (RESULTS, generated by run.py; do not edit by hand)")
out("")
out("**HARD RULE (Akitti, 22:41): the lift's gravity is quantum gravity, and it is UNKNOWN.** Einstein GR (Euclidean Schwarzschild) is used here "
    "ONLY as a calibration/control row - a known limit that the unknown quantum gravity must reproduce (or explicitly depart from). It is never the "
    "lift's gravity and never the answer. **L1 has NO gravity-independent part** (spec L16); the only gravity-free item is the spec's 'Requirement 1 harness test [kinematic, no gravity theory]', "
    "which tests the harness's smooth-tip check, not any gravity. A PASS means the harness is calibrated; it does NOT mean the lift is done or unblocked. "
    "Every GR row below is tagged [standard: GR control].")
out("")
out(f"Generated {time.strftime('%Y-%m-%d %H:%M:%S')} (local time, BST = UTC+01:00). Python {platform.python_version()}, numpy {np.__version__}, "
    f"scipy {scipy.__version__}, sympy {sp.__version__}.")
crc, sha = before[SPEC]
out(f"Spec: JOB_LIFT_SPEC.md, CRC32 {crc}, SHA-256 prefix {sha} (Venus-cleared {SPEC_HASH}, 22:56, replacing 9E2B9281: match {sha == SPEC_HASH}).")
crcR, shaR = before[REVIEW]
out(f"Review: LOCAL_LIFT_CHECKS_REVIEW.md, CRC32 {crcR}, SHA-256 prefix {shaR} (expected {REVIEW_HASH}: match {shaR == REVIEW_HASH}).")
if sha != SPEC_HASH or shaR != REVIEW_HASH:
    out("**STOP: spec/review hash mismatch - nothing computed.**")
    open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8", newline="\n").write("\n".join(OUT) + "\n")
    raise SystemExit(1)
out("")
out(f"Fixed before the graded run (spec L1 pass rule): (a) |M^2 lambda - ({LAM_TARGET})| <= {LAM_TOL}; (b) exactly {COUNT_EXPECT} negative TT s-wave mode "
    f"in the scan window M^2 lambda in [{LAM_SCAN_LO}, {LAM_SCAN_HI}]; (c) Lorentzian check finds no growing mode; (d) conformal modes reported in their own column. "
    f"Otherwise FAIL. Bolt rule (spec): smooth period 2 pi/kappa derived from the metric (tolerance {BOLT_TOL:g}); a 4 pi period must be flagged as a cone.")
out("")
out("Theory of every row: Euclidean Einstein gravity, Lambda = 0, Q = 0 (Euclidean Schwarzschild, ds^2 = V dtau^2 + dr^2/V + r^2 dOmega^2, V = 1 - 2M/r, G = 1, M = 1) "
    "[standard: GR control]. All eigenvalues and modes are REAL (real symmetric TT perturbations, Prestidge (3.12)); counts are real modes.")
out("")

# ---------------- sympy: Prestidge master ODE (4.4) for n = 4 Schwarzschild ----------------
r, Ms, lam = sp.symbols("r M lambda")
n = 4
V = 1 - 2 * Ms / r
Vp, Vpp = sp.diff(V, r), sp.diff(V, r, 2)
Dd = r * Vp - 2 * V
c1 = sp.factor(sp.simplify((2 * r ** 2 * (V * Vpp - Vp ** 2) - r * (n - 2) * V * Vp + 2 * n * V ** 2) / (r * Dd)))
c0 = sp.factor(sp.simplify((r ** 2 * Vp * Vpp + r * (2 * (n - 1) * V * Vpp - (n + 2) * Vp ** 2) + 4 * V * Vp) / (r * Dd)))
rs_sol = sp.solve(sp.Eq(Dd, 0), r)
out("## Prestidge master equation (4.4), n = 4, V = 1 - 2M/r [identity; sympy]")
out("")
out(f"-V chi'' + c1 chi' + c0 chi = lambda chi with c1 = {c1}, c0 = {c0}; ansatz (4.1)-(4.3): phi^a_b = diag(psi, chi, k, k), k = -(psi + chi)/2, "
    f"psi = [2rV chi' + (rV' + 6V) chi]/(rV' - 2V). Singular points: r+ = 2M (V = 0), r_s = {rs_sol} (rV' - 2V = 0), infinity.")
# Frobenius at the bolt and at r_s (M = 1)
y = sp.Symbol("y")
c1n, c0n = c1.subs(Ms, 1), c0.subs(Ms, 1)
Vn = V.subs(Ms, 1)
a = sp.symbols("a0:5")
chi_s = sum(a[j] * y ** j for j in range(5))
ex = sp.expand(sp.simplify(((-Vn * sp.diff(chi_s, r, 2) + c1n * sp.diff(chi_s, r) + (c0n - lam) * chi_s)).subs(r, 2 + y) if False else 0))
# do it directly in y
rr = 2 + y
c1y, c0y, Vy = c1n.subs(r, rr), c0n.subs(r, rr), Vn.subs(r, rr)
ex = sp.expand(sp.simplify((-Vy * sp.diff(chi_s, y, 2) + c1y * sp.diff(chi_s, y) + (c0y - lam) * chi_s) * rr ** 3 * (rr - 3)))
pol = sp.Poly(sp.series(ex, y, 0, 4).removeO(), y)
eqs = [pol.coeff_monomial(y ** j) for j in range(3)]
hs = sp.solve(eqs, [a[1], a[2], a[3]], dict=True)[0]
A1 = sp.factor(hs[a[1]].subs(a[0], 1)); A2 = sp.factor(hs[a[2]].subs(a[0], 1)); A3 = sp.factor(hs[a[3]].subs(a[0], 1))
out(f"- Bolt r+ = 2M: indicial roots 0 and -1 (Prestidge); the regular series chi = 1 + a1 x + a2 x^2 + a3 x^3, x = r - 2: a1 = {A1}, a2 = {A2}, a3 = {A3}. "
    "At r+, psi = chi (from (4.3)), so the mode does not change the period of tau (Prestidge Sec. 4).")
x = sp.Symbol("x")
b = sp.symbols("b0:6")
chi_r = sum(b[j] * x ** j for j in range(6))
rr = 3 + x
ex2 = sp.expand(sp.simplify((-Vn.subs(r, rr) * sp.diff(chi_r, x, 2) + c1n.subs(r, rr) * sp.diff(chi_r, x) + (c0n.subs(r, rr) - lam) * chi_r) * x * rr ** 3))
pol2 = sp.Poly(sp.series(ex2, x, 0, 5).removeO(), x)
e2 = [sp.expand(pol2.coeff_monomial(x ** j)) for j in range(4)]
s01 = sp.solve(e2[:2], [b[1], b[2]], dict=True)[0]
consist = sp.simplify(e2[2].subs(s01))
b3_in_e2 = sp.diff(e2[2], b[3])
out(f"- r_s = 3M: indicial roots 0 and 3. Series: b1 = {sp.factor(s01[b[1]])} (= Prestidge (4.5)), b2 = {sp.factor(s01[b[2]])}; the order-x^2 equation "
    f"does not contain b3 (coefficient {b3_in_e2}) and is satisfied identically (residual {consist}), so b3 is free and there is **no logarithm**: "
    "r_s is an apparent singularity, every solution is analytic there [identity; sympy]. Numerically the ODE is integrated around r_s on a complex semicircle; "
    "upper and lower detours must agree (printed).")
out("")
c1f = sp.lambdify((r, lam), c1n, "numpy")
c0f = sp.lambdify((r, lam), c0n, "numpy")
A1f, A2f, A3f = [sp.lambdify(lam, e, "numpy") for e in (A1, A2, A3)]


def rhs_real(t, Y, lv):
    rv = t
    Vv = 1 - 2 / rv
    return [Y[1], (c1f(rv, lv) * Y[1] + (c0f(rv, lv) - lv) * Y[0]) / Vv]


def shoot(lv, side=+1, delta=DELTA_H, Rfar=None, rho=RHO_DETOUR, rtol=RTOL):
    k = math.sqrt(-lv)
    if Rfar is None:
        Rfar = max(R_MIN, KR_FAR / k)
    x0 = delta
    chi0 = 1 + A1f(lv) * x0 + A2f(lv) * x0 ** 2 + A3f(lv) * x0 ** 3
    dchi0 = A1f(lv) + 2 * A2f(lv) * x0 + 3 * A3f(lv) * x0 ** 2
    s1 = solve_ivp(rhs_real, (RP + x0, RS - rho), [chi0, dchi0], args=(lv,), method="DOP853", rtol=rtol, atol=ATOL)
    Y = np.array(s1.y[:, -1], dtype=complex)

    def rhs_arc(th, Yc):
        rv = RS + rho * cmath.exp(1j * th)
        drdth = 1j * rho * cmath.exp(1j * th)
        Vv = 1 - 2 / rv
        d2 = (c1f(rv, lv) * Yc[1] + (c0f(rv, lv) - lv) * Yc[0]) / Vv
        return [Yc[1] * drdth, d2 * drdth]

    th_end = 0.0 if side > 0 else -2 * math.pi
    s2 = solve_ivp(rhs_arc, (math.pi, th_end) if side > 0 else (-math.pi, 0.0), Y, method="DOP853", rtol=rtol, atol=ATOL)
    Y2 = s2.y[:, -1]
    imag = float(max(abs(Y2[0].imag) / abs(Y2[0]), abs(Y2[1].imag) / max(abs(Y2[1]), 1e-300)))
    s3 = solve_ivp(rhs_real, (RS + rho, Rfar), [Y2[0].real, Y2[1].real], args=(lv,), method="DOP853", rtol=rtol, atol=ATOL, dense_output=True)
    chiR, dchiR = s3.y[0, -1], s3.y[1, -1]
    F = (dchiR + (k + 2 / Rfar) * chiR) * Rfar ** 2 * math.exp(-k * Rfar) / (2 * k)
    return F, imag, s1, s3


# ---------------- scan and count ----------------
out("## L1 - GPY negative mode: TT s-wave spectrum below zero [standard: GR control]")
out("")
grid = -np.geomspace(-LAM_SCAN_LO, -LAM_SCAN_HI, N_SCAN)
Fs = np.array([shoot(lv)[0] for lv in grid])
roots = []
for i in range(len(grid) - 1):
    if np.sign(Fs[i]) != np.sign(Fs[i + 1]):
        lo, hi = grid[i], grid[i + 1]
        Rfix = max(R_MIN, KR_FAR / math.sqrt(-hi))
        rt = brentq(lambda lv: shoot(lv, Rfar=Rfix)[0], lo, hi, xtol=1e-13, rtol=1e-13)
        roots.append(rt)
count = len(roots)
out(f"Shooting: regular series at the bolt, complex detour around r_s, integrate to R = max({R_MIN:g}, {KR_FAR:g}/k) M, k = sqrt(-lambda); shooting function = "
    "coefficient of the growing e^(kr)/r^2 branch. " + f"Scan of {N_SCAN} log-spaced points in M^2 lambda in [{LAM_SCAN_LO}, {LAM_SCAN_HI}] (lower end is 10x the "
    "pointwise bound -2 max|Weyl| = -1/(2M^2) [assumed estimate]), sign changes refined by brentq.")
out("")
out("| mode | M^2 lambda | lambda r+^2 | real/complex | theory | upper-vs-lower detour (imag part) | upper-vs-lower |delta F| / |F scale| |")
out("|---:|---:|---:|---|---|---:|---:|")
lam_neg = roots[0] if roots else float("nan")
for j, rt in enumerate(roots):
    Fu, im_u, _, _ = shoot(rt, +1)
    Fl, im_l, _, _ = shoot(rt, -1)
    Fscale = max(abs(shoot(rt * 1.01)[0]), abs(shoot(rt * 0.99)[0]))
    out(f"| {j + 1} | {rt:.8f} | {rt * RP ** 2:.6f} | real | Euclidean Einstein (GR control) | {max(im_u, im_l):.1e} | {abs(Fu - Fl) / Fscale:.1e} |")
out("")
imag_ok = True
if roots:
    _, im_u, s1, s3 = shoot(lam_neg, +1)
    imag_ok = im_u < IMAG_TOL
    # nodes of the eigenfunction
    rr_ = np.linspace(RS + RHO_DETOUR, max(R_MIN, KR_FAR / math.sqrt(-lam_neg)) * 0.6, 4000)
    chi_out = s3.sol(rr_)[0]
    nodes_in = int(np.sum(np.diff(np.sign(s1.y[0])) != 0))
    nodes_out = int(np.sum(np.diff(np.sign(chi_out)) != 0))
    out(f"Eigenfunction chi (normalised chi(r+) = 1): sign changes on [r+, r_s - rho]: {nodes_in}; on [r_s + rho, 0.6 R]: {nodes_out} [computed].")
# resolution checks
chk = []
if roots:
    Rf = max(R_MIN, KR_FAR / math.sqrt(-lam_neg))
    for lab_, kw in [("delta = 1e-4", dict(delta=1e-4)), ("R x 1.5", dict(Rfar=1.5 * Rf)), ("detour radius 0.25", dict(rho=0.25)), ("rtol 1e-10", dict(rtol=1e-10))]:
        lo, hi = lam_neg * 1.02, lam_neg * 0.98
        kw2 = dict(kw)
        if "Rfar" not in kw2:
            kw2["Rfar"] = Rf
        rt2 = brentq(lambda lv: shoot(lv, **kw2)[0], lo, hi, xtol=1e-13, rtol=1e-13)
        chk.append((lab_, rt2))
    out("Resolution checks [finite-size]: " + "; ".join(f"{l}: {v:.8f} (change {v - lam_neg:+.1e})" for l, v in chk) + ".")
out("")
pass_a = bool(roots) and abs(lam_neg - LAM_TARGET) <= LAM_TOL
pass_b = count == COUNT_EXPECT
out(f"**(a) eigenvalue: M^2 lambda = {lam_neg:.6f} vs {LAM_TARGET} +- {LAM_TOL} -> {'PASS' if pass_a else 'FAIL'}** (Prestidge eq. (5.12) -0.192; Reall eq. (1.7) -0.19 M^-2) [standard: GR control].")
out(f"**(b) count: {count} negative TT s-wave mode(s) in the scan window -> {'PASS' if pass_b else 'FAIL'}** [standard: GR control].")
out(f"r_s regularity (path independence below {IMAG_TOL:g}): {imag_ok}.")
out("")

# ---------------- (c) Lorentzian ----------------
out("## (c) Lorentzian growing modes [standard: GR control]")
out("")
out("- s-wave (the sector of the GPY mode): Lorentzian count = 0 [identity: Birkhoff - the only spherically symmetric vacuum solution is static Schwarzschild, "
    "so there is no spherical dynamical degree of freedom to grow]. This is the graded (c).")
fR = lambda rv: 1 - 2 / rv
rg = np.geomspace(RP * (1 + 1e-9), 1e4, 200000)
rows_lw = []
for ell in (2, 3, 4):
    VRW = fR(rg) * (ell * (ell + 1) / rg ** 2 - 6 / rg ** 3)
    lm = (ell - 1) * (ell + 2) / 2
    VZ = fR(rg) * (2 * lm ** 2 * (lm + 1) * rg ** 3 + 6 * lm ** 2 * rg ** 2 + 18 * lm * rg + 18) / (rg ** 3 * (lm * rg + 3) ** 2)
    rows_lw.append((ell, float(np.min(VRW / fR(rg) * rg ** 3)), float(np.min(VZ / fR(rg) * rg ** 3))))
out("- Report only, l >= 2: Regge-Wheeler and Zerilli potentials, min over r in (2M, 10^4 M] of V(r) r^3/f(r) (> 0 means V > 0 everywhere outside the horizon, "
    "so -d^2/dr*^2 + V has no negative eigenvalue, i.e. no growing mode): "
    + "; ".join(f"l = {l}: RW {a_:.4f}, Zerilli {b_:.4f}" for l, a_, b_ in rows_lw) + " [computed; report only].")
lw_pos = all(a_ > 0 and b_ > 0 for _, a_, b_ in rows_lw)
pass_c = True   # identity (Birkhoff) for the s-wave sector
out(f"**(c) Lorentzian count (s-wave) = 0 -> PASS** [identity: Birkhoff]; report-only l = 2-4 positivity: {lw_pos}.")
out("")

# ---------------- (d) conformal column ----------------
out("## (d) Conformal-factor column (counted separately) [standard: GR control; Gibbons-Hawking-Perry 1978, Gibbons-Perry 1978]")
out("")
out("Trace operator: in the GHP/Prestidge split A + B = -F + G, the trace (conformal) part of the metric fluctuation enters the Euclidean action with the "
    "WRONG sign (Reall Sec. 1.3: 'a wrong-sign kinetic term'); for Lambda = 0 the trace operator F is (a positive multiple of) the scalar Laplacian -nabla^2 "
    "[standard; constant not re-derived - sign and spectrum do not depend on it]. Unrotated, every trace mode lowers the action (unbounded below). "
    "Gibbons-Perry rotate the conformal factor (phi -> i phi), after which the trace operator is -nabla^2 >= 0. These modes are a Wick artefact, not physical.")
out("")
conf_rows = []
for Rb in CONF_BOXES:
    rgr = np.linspace(RP, Rb, CONF_NPTS)
    h = rgr[1] - rgr[0]
    rm = 0.5 * (rgr[1:] + rgr[:-1])
    w = rm ** 2 * fR(rm)                       # r^2 V at half points (natural BC at the bolt, where V = 0)
    Dm = sps.diags([-np.ones(CONF_NPTS - 1), np.ones(CONF_NPTS - 1)], [0, 1], shape=(CONF_NPTS - 1, CONF_NPTS)) / h
    K = (Dm.T @ sps.diags(w * h) @ Dm).tocsr()
    mw = rgr ** 2 * h
    mw[0] *= 0.5
    keep = np.arange(CONF_NPTS - 1)            # Dirichlet at the box wall
    K = K[keep][:, keep].tocsc()
    Mm = sps.diags(mw[keep]).tocsc()
    ev = spla.eigsh(K, k=2, M=Mm, sigma=-1e-6, which="LM")[0]
    conf_rows.append((Rb, float(np.min(ev)), float(np.min(ev)) * Rb ** 2))
out("| row | wrong-sign trace kinetic term? | rotated (Gibbons-Perry)? | lowest eigenvalue of trace operator -nabla^2 (s-wave, tau-independent), box r <= R | R^2 x lowest | count of negative trace modes after rotation | real/complex | theory |")
out("|---|---|---|---|---|---|---|---|")
for Rb, l0, l0R in conf_rows:
    out(f"| conformal, R = {Rb:g} M | yes | yes | {l0:.6e} M^-2 | {l0R:.4f} | {int(l0 < 0)} | real | Euclidean Einstein (GR control) |")
out("")
out(f"The lowest trace eigenvalue is positive and falls like 1/R^2 (R^2 x lowest -> about pi^2 = {math.pi ** 2:.4f}): the rotated trace operator has spectrum [0, inf) on "
    "the infinite instanton, no negative mode, infimum 0 not attained [computed; finite-size]. Unrotated, the count is formally infinite (every trace mode) - the conformal-factor problem.")
pass_d = True    # the column is reported
out("**(d) conformal modes reported in their own column -> PASS**.")
out("")

# ---------------- bolt rule ----------------
out("## Bolt rule: smooth period derived from the metric, not fixed [standard: GR control; kinematic]")
out("")
eps_list = [1e-2, 3e-3, 1e-3, 3e-4, 1e-4]


def kappa_tip(G):
    """d sqrt(F)/d(proper distance) at a tip of ds^2 = F dtau^2 + dx^2/F, with the metric function written at offset s from the tip as
    F = s G(s) (exact factorisation, avoids round-off). sqrt(F)/dist at small offsets e, dist = int_0^sqrt(e) 2 du / sqrt(G(u^2)),
    then a quadratic fit in e extrapolated to e = 0."""
    ks_ = []
    for e_ in eps_list:
        dist = quad(lambda u_: 2 / math.sqrt(G(u_ * u_)), 0.0, math.sqrt(e_), limit=200, epsabs=0, epsrel=1e-13)[0]
        ks_.append(math.sqrt(e_ * G(e_)) / dist)
    return float(np.polyfit(eps_list, ks_, 2)[-1]), ks_


kap_num, kap = kappa_tip(lambda s_: 1 / (RP + s_))     # V(r+ + s) = s/(r+ + s), M = 1
beta_star = 2 * math.pi / kap_num
out(f"kappa from the metric: sqrt(V)/(proper distance from the bolt) at r - r+ = {eps_list} gives {', '.join(f'{k_:.10f}' for k_ in kap)} -> (quadratic fit, e -> 0) {kap_num:.10f} "
    f"(GR value 1/(4M) = {1 / (4 * M):.10f}). Smooth period beta* = 2 pi/kappa = {beta_star:.8f} vs 8 pi M = {8 * math.pi * M:.8f}.")


def gauss_bonnet(beta, Rcut=10.0):
    # cigar (tau, r): K = -V''/2, dA = dtau dr; boundary circle r = Rcut, k_g = V'/(2 sqrt V), length beta sqrt V
    Vp_ = lambda t_: 2 / t_ ** 2
    intK = beta * quad(lambda t_: -0.5 * (-4 / t_ ** 3), RP, Rcut)[0]
    intkg = beta * math.sqrt(fR(Rcut)) * Vp_(Rcut) / (2 * math.sqrt(fR(Rcut)))
    return intK + intkg                                    # = 2 pi - (cone deficit)


out("")
out("| period beta | cone angle beta x kappa | 2 pi | Gauss-Bonnet: int K + boundary k_g (cigar to r = 10M) | deficit 2 pi - angle | smooth bolt? |")
out("|---|---:|---:|---:|---:|---|")
bolt_rows = []
for lab_, bt in [("beta* (derived)", beta_star), ("8 pi M (GR value)", 8 * math.pi * M), ("4 pi (old lift-4d period)", 4 * math.pi)]:
    ang = bt * kap_num
    gb = gauss_bonnet(bt)
    smooth = abs(ang - 2 * math.pi) < BOLT_TOL * 2 * math.pi
    bolt_rows.append((lab_, smooth))
    out(f"| {lab_} = {bt:.6f} | {ang:.8f} | {2 * math.pi:.8f} | {gb:.8f} | {2 * math.pi - ang:.3e} | {'yes' if smooth else 'NO - conical defect (FAIL)'} |")
out("")
bolt_ok = abs(beta_star - 8 * math.pi * M) / (8 * math.pi * M) < BOLT_TOL and bolt_rows[1][1] and not bolt_rows[2][1]
out(f"**Bolt check: {'PASS' if bolt_ok else 'FAIL'}** - the derived smooth period equals 8 pi M within {BOLT_TOL:g}, and the 4 pi period is detected as a cone. "
    "The period is computed from the metric's tip geometry, never set and then checked against itself (cf. OLD_LIFT_REVIEW.md, lift-4d).")
out("")

# ---------------- Requirement 1 harness test [kinematic, no gravity theory] ----------------
out("## Requirement 1 harness test [kinematic, no gravity theory]")
out("")
out("Spec, 'Local Grok Build lift checks' (qg-operator, 09-25): the old Pair A P2 geometry ds^2 = d eps^2/F + F dtau^2, F = eps_EP^2 - eps^2, with the old period "
    "4 pi/eps_EP 'is not a smooth Euclidean horizon'; smooth period 2 pi/eps_EP; 'the old 4 pi/eps_EP period fails requirement 1 (a 4 pi cone; Gauss-Bonnet balances "
    "with chi = 2)'. Here the same harness as the bolt rule (tip kappa from proper distance, cone angle, Gauss-Bonnet by quadrature) is run on that 2D metric. "
    "No field equation and no gravity theory is used; this tests requirement 1's smoothness check, not gravity. P2 itself is [hive-interpretation] (built to match a spec).")
out("")


def tip_geometry(Ff, Fpp, e_lo, e_hi):
    """kappa at both tips of ds^2 = de^2/F + F dtau^2 from sqrt(F)/(proper distance), extrapolated; area per unit tau; int K per unit tau"""
    ee_ = e_hi
    ks = [kappa_tip(lambda s_: 2 * ee_ - s_)[0], kappa_tip(lambda s_: 2 * ee_ - s_)[0]]   # F(-e+s) = F(e-s) = s(2 e - s)
    area_per_tau = quad(lambda t_: 1.0, e_lo, e_hi)[0]                       # sqrt(g) = sqrt(F/F) = 1
    intK_per_tau = quad(lambda t_: -0.5 * Fpp(t_), e_lo, e_hi)[0]            # K = -F''/2
    return ks, area_per_tau, intK_per_tau


req1_rows = []
req1_ok = True
out("| eps_EP | period | source | kappa at tips (from metric) | cone angles beta x kappa | area | int K dA | Gauss-Bonnet int K + sum(2 pi - angle) | 2 pi chi (chi = 2) | smooth tip (requirement 1)? |")
out("|---:|---|---|---|---|---:|---:|---:|---:|---|")
for ee in [EPS_EP] + EPS_EP_EXTRA:
    Ff = lambda t_, ee=ee: ee ** 2 - t_ ** 2
    Fpp = lambda t_: -2.0
    ks, apt, kpt = tip_geometry(Ff, Fpp, -ee, ee)
    beta_s = 2 * math.pi / ks[0]
    for lab_, bt in [("derived smooth 2 pi/kappa", beta_s), ("old Pair A 4 pi/eps_EP", 4 * math.pi / ee)]:
        angs = [bt * k_ for k_ in ks]
        area = bt * apt
        intK = bt * kpt
        gb = intK + sum(2 * math.pi - a_ for a_ in angs)
        smooth = all(abs(a_ - 2 * math.pi) < BOLT_TOL * 2 * math.pi for a_ in angs)
        gb_ok = abs(gb - 4 * math.pi) / (4 * math.pi) < GB_TOL
        req1_rows.append((ee, lab_, smooth, gb_ok, bt, area))
        out(f"| {ee:.6f} | {bt:.6f} | {lab_} | {ks[0]:.9f}, {ks[1]:.9f} | {angs[0]:.6f}, {angs[1]:.6f} | {area:.6f} | {intK:.6f} | {gb:.9f} | {4 * math.pi:.9f} | "
            f"{'yes' if smooth else 'NO - 4 pi cone at each tip (fails requirement 1)'} |")
    req1_ok &= abs(beta_s - 2 * math.pi / ee) / (2 * math.pi / ee) < BOLT_TOL
main = [r_ for r_ in req1_rows if r_[0] == EPS_EP]
req1_ok &= main[0][2] and (not main[1][2]) and all(r_[3] for r_ in req1_rows) and all(r_[2] == (r_[1].startswith("derived")) for r_ in req1_rows)
out("")
out(f"eps_EP = 2 pi/{TIP_PERIOD_QUOTED} = {EPS_EP:.6f} (from the quoted smooth period; spec: about 0.514). Derived smooth period {main[0][4]:.6f} vs quoted {TIP_PERIOD_QUOTED}; "
    f"old period 4 pi/eps_EP = {main[1][4]:.6f} (quoted 24.463390). Smooth period: area {main[0][5]:.6f} = 4 pi = {4 * math.pi:.6f} (unit round S^2, no cone); "
    f"old period: area {main[1][5]:.6f} = 8 pi with two 4 pi cones; Gauss-Bonnet balances in both cases: 8 pi + 2(2 pi - 4 pi) = 4 pi = 2 pi chi, chi = 2.")
out(f"**Requirement 1 harness test [kinematic, no gravity theory]: {'PASS' if req1_ok else 'FAIL'}** - the harness derives the smooth period from the tip geometry, "
    "passes it, and flags the old Pair A 4 pi/eps_EP period as failing requirement 1 (4 pi cone), at every eps_EP tried; Gauss-Bonnet holds with chi = 2 "
    f"(tolerance {GB_TOL:g}). This calibrates the smooth-tip check only; it says nothing about the unknown quantum gravity.")
out("")
ang_s = main[0][4] * kappa_tip(lambda s_: 2 * EPS_EP - s_)[0]
ang_o = main[1][4] * kappa_tip(lambda s_: 2 * EPS_EP - s_)[0]
REQ1_SENTENCE = (f"Requirement 1 smooth-tip result: with the smooth period 2 pi/kappa = {main[0][4]:.6f} the tip is {'SMOOTH' if main[0][2] else 'a CONE'} "
                 f"(cone angle {ang_s:.6f} = {ang_s / math.pi:.6f} pi, area {main[0][5]:.6f} = {main[0][5] / math.pi:.6f} pi); with the old lift's 4 pi/eps_EP = {main[1][4]:.6f} "
                 f"the tip is {'SMOOTH' if main[1][2] else 'a CONE'} (cone angle {ang_o:.6f} = {ang_o / math.pi:.6f} pi at each tip, area {main[1][5]:.6f} = {main[1][5] / math.pi:.6f} pi), "
                 f"and Gauss-Bonnet balances with chi = 2 in both cases [computed; kinematic, no gravity theory].")
out("**" + REQ1_SENTENCE + "**")
out("")

# ---------------- on-shell action (report only) ----------------
out("## Report only - on-shell Euclidean action [standard: GR control; Gibbons-Hawking 1977]")
out("")
out("I = -(1/16 pi) int R sqrt(g) - (1/8 pi) int (K - K0) sqrt(h); R = 0 on shell; boundary r = R_b with K = r^-2 d(r^2 sqrt V)/dr, flat subtraction K0 = 2/R_b, beta = beta* (derived).")
out("")
out("| R_b / M | I | 4 pi M^2 = A/4 = beta M/2 | relative difference |")
out("|---:|---:|---:|---:|")
Iref = 4 * math.pi * M ** 2
for Rb in ACTION_R:
    sV = math.sqrt(fR(Rb))
    Kb = (2 * Rb * sV + Rb ** 2 * (2 / Rb ** 2) / (2 * sV)) / Rb ** 2
    K0 = 2 / Rb
    I_ = -(1 / (8 * math.pi)) * (Kb - K0) * beta_star * sV * 4 * math.pi * Rb ** 2
    out(f"| {Rb:g} | {I_:.10f} | {Iref:.10f} | {(I_ - Iref) / Iref:+.2e} |")
out("")
out("Sign: +A/4 is the asymptotically flat value (mass term present); the -A/4 form of the old qg-theory job applies only to compact spaces (dS/Nariai) [Venus 22:40].")
out("")

# ---------------- GL / Stelle cross-check (report only) ----------------
out("## Report only - Gregory-Laflamme / Stelle code check (not evidence)")
out("")
mur = math.sqrt(-lam_neg) * RP if roots else float("nan")
out(f"lambda r+^2 = {lam_neg * RP ** 2:.6f} (expected about -0.768 = 4 x -0.192); mu* r+ = sqrt(-lambda) r+ = {mur:.6f}; "
    f"LPPS m2 r_h = {GL_LPPS} (relative difference {(mur - GL_LPPS) / GL_LPPS:+.2e}); Reall mu* = {GL_REALL_MU} at r+ = 2 gives {GL_REALL_MU * 2:.2f} "
    f"(our mu* = {math.sqrt(-lam_neg) if roots else float('nan'):.6f}). The identification m2^2 = -lambda (same Lichnerowicz operator) is Venus's identity reasoning; "
    "LPPS is cited for the 0.876 only [identity, Venus 22:40; code check only].")
out("")

# ---------------- grade ----------------
grade = "PASS" if (pass_a and pass_b and pass_c and pass_d) else "FAIL"
out("## Count table row (control)")
out("")
out("| row | theory | (Euclidean negative TT modes, Lorentzian growing modes) | real/complex | conformal modes | tag |")
out("|---|---|---|---|---|---|")
out(f"| L1 Schwarzschild | Euclidean Einstein (Q = 0), Lambda = 0 | ({count}, 0) | real | separate column: rotated, lowest trace eigenvalue -> 0+ | [standard: GR control] |")
out("")
out("## Summary")
out("")
out(f"- (a) M^2 lambda = {lam_neg:.6f} ({'PASS' if pass_a else 'FAIL'}); (b) count {count} ({'PASS' if pass_b else 'FAIL'}); (c) Lorentzian s-wave 0 [identity] (PASS); (d) conformal column (PASS). "
    f"Bolt check (GR control): {'PASS' if bolt_ok else 'FAIL'}. Requirement 1 harness test [kinematic, no gravity theory]: {'PASS' if req1_ok else 'FAIL'}. r_s path independence: {imag_ok}.")
out(f"- {REQ1_SENTENCE}")
out(f"- **Grade by the spec's rule: {grade}** - this is a reproduction. **It means the harness is calibrated against the GR control. It does NOT mean the lift is "
    "done or unblocked; L1 has no gravity-independent part, and the lift's gravity (unknown quantum gravity) is not tested here.**")
after = {f: crc_sha(f) for f in AUD}
out(f"- Files in open-problems\\ (top level, {len(AUD)}) unchanged by the run: {before == after}.")
out(f"- Runtime: {time.time() - T0:.0f} s [computed].")
with open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(OUT) + "\n")
