#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Job B0 (Bradlow-cap line): n coincident BPS vortices on a round sphere - the shared Taubes base run.
Spec: ../JOB_B0_TAUBES_BASE_SPEC.md (Helios; Venus PASS ~22:05 BST). Writes RESULTS.md (ONLY ever written by this
script) next to itself. Run:  $env:PYTHONIOENCODING='utf-8'; python -B run.py
Every number in RESULTS.md is printed from a variable. All PASS thresholds are fixed in the parameter block below
before the first run. B1-B4 are NOT built here.
"""
import os, sys, time, platform, hashlib, zlib, math
import numpy as np
import scipy
import scipy.sparse as sps
import scipy.sparse.linalg as spla
from scipy.integrate import solve_bvp, simpson
import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC_DIR = os.path.dirname(HERE)
SPEC = os.path.join(SPEC_DIR, "JOB_B0_TAUBES_BASE_SPEC.md")
T0 = time.time()
OUT = []


def out(s=""):
    print(s, flush=True)
    OUT.append(s)


# ---------------- parameters and thresholds (fixed before the first run) ----------------
N_LIST = [1, 2, 3]                       # spec: n = 1, 2, 3
EPS_LIST = [0.01, 0.02, 0.05, 0.1, 1.0, 4.0]   # spec: eps = A/A_B - 1
EPS_NEAR = [0.01, 0.02, 0.05, 0.1]       # spec: "near the cap"
P1_FIT_EPS = [0.01, 0.02, 0.05]          # spec pass rule: straight-line fit over the 3 smallest eps
P1_TOL = 0.03                            # spec: intercept within 3% of 1
C1_TOL = 1e-6                            # spec: relative error below 1e-6
C2_TOL = 1e-3                            # C2: max relative error of -D^2 eigenvalues vs Wu-Yang [assumed]
C2_LEVELS = 4                            # C2: levels l = n/2 ... n/2 + 3 checked [assumed]
ZERO_TOL = 1e-5                          # zero mode: omega^2 < 1e-5 (discretisation ~h^4; smallest physical gap ~1e-2) [assumed]
K_WINDOW = 2                             # sectors scanned: k = -n-2 ... +2 [assumed]
NEV = 6                                  # eigenvalues per sector
T_BVP, N_BVP0, BVP_TOL = 14.0, 4001, 1e-10   # Taubes BVP in t = log tan(theta/2) on [-T, T] [assumed]
T_FL, H_FL = 10.0, 0.01                  # fluctuation grid in t: [-T_FL, T_FL], step h (2001 nodes) [assumed]
H_FL_CHECK = 0.005                       # resolution check of the gap at the smallest eps [finite-size]
N_QUAD = 200001                          # Simpson points for C1 integrals
CONT_EPS = [0.1, 0.2, 0.5, 1.0, 2.0, 4.0]    # continuation path to the far areas (not reported as results)
SPREAD = [(2, 1), (3, 1), (3, 2)]        # report-only control: (n, p) = p vortices at north, n - p at south
PLANE_RMAX, PLANE_DCMP = 14.0, 2.0       # report-only plane comparison: plane domain r <= 14; compare at geodesic d <= 2


def crc_sha(path):
    b = open(path, "rb").read()
    return "%08X" % (zlib.crc32(b) & 0xFFFFFFFF), hashlib.sha256(b).hexdigest()[:8].upper()


siblings = sorted(f for f in os.listdir(SPEC_DIR) if os.path.isfile(os.path.join(SPEC_DIR, f)))
before = {f: crc_sha(os.path.join(SPEC_DIR, f)) for f in siblings}

out("# Job B0: n vortices on a round sphere - Taubes base run (RESULTS, generated by run.py; do not edit by hand)")
out("")
out(f"Generated {time.strftime('%Y-%m-%d %H:%M:%S')} (local time, BST = UTC+01:00). Python {platform.python_version()}, "
    f"numpy {np.__version__}, scipy {scipy.__version__}, sympy {sp.__version__}.")
crc, sha = before[os.path.basename(SPEC)]
out(f"Spec: JOB_B0_TAUBES_BASE_SPEC.md, CRC32 {crc}, SHA-256 prefix {sha} (posted hash B5ABA965 = SHA-256 prefix match: {sha == 'B5ABA965'}).")
out("")
out(f"Fixed before the first run: C1 relative error < {C1_TOL:g}; C2 relative error < {C2_TOL:g} on {C2_LEVELS} levels; zero mode = omega^2 < {ZERO_TOL:g}; "
    f"C3 = exactly one complex zero mode in each sector k = -n..-1 and none in the other scanned sectors k = -n-{K_WINDOW}..{K_WINDOW}; "
    f"P1 PASS = straight-line fit of gap^2/eps over eps = {P1_FIT_EPS} extrapolates to 1 within {P1_TOL:.0%}, for every n. "
    "Grade (spec): PASS = C1-C3 hold and P1 passes; PARTIAL = controls pass, P1 misses; FAIL = a control fails.")
out("")
out("Model (spec, e = v = 1): L = 1/2|D phi|^2 + 1/4 F^2 + 1/8(|phi|^2 - 1)^2; BPS: (D1 + iD2)phi = 0, B = 1/2(1 - |phi|^2); "
    "A_B = 4 pi n; R^2 = A/(4 pi) = n(1 + eps).")
out("")

# ---------------- sympy identities ----------------
th, R, n_, t, A, AB = sp.symbols("theta R n t A A_B", positive=True)
lap = lambda g: sp.simplify(sp.diff(sp.sin(th) * sp.diff(g, th), th) / (R ** 2 * sp.sin(th)))
I1 = sp.simplify(lap(2 * n_ * sp.log(sp.sin(th / 2))) + n_ / R ** 2)
I1b = sp.simplify(lap(2 * n_ * sp.log(sp.cos(th / 2))) + n_ / R ** 2)
thetat = 2 * sp.atan(sp.exp(t))
I2 = sp.simplify(sp.diff(thetat, t) - sp.sin(thetat))
I3 = sp.simplify(sp.sin(thetat) ** 2 - sp.sech(t) ** 2)
I3b = sp.simplify((sp.sin(thetat / 2) ** 2 - sp.exp(2 * t) / (1 + sp.exp(2 * t))).rewrite(sp.exp))
U = sp.Function("u")
ut = U(thetat)
lhs_t = sp.diff(ut, t, 2)
rhs_th = sp.sin(th) ** 2 * (sp.diff(U(th), th, 2) + sp.cot(th) * sp.diff(U(th), th))
I4 = sp.simplify((lhs_t - rhs_th.subs(th, thetat)).doit())
P3l = sp.pi * n_ / 2 * (AB / A + A / AB) - sp.pi * n_
I5 = sp.simplify((P3l - (A - AB) ** 2 / (8 * A)).subs(AB, 4 * sp.pi * n_))
I6 = sp.simplify((sp.pi * n_ * (A - AB) ** 2 / (2 * A * AB) - (A - AB) ** 2 / (8 * A)).subs(AB, 4 * sp.pi * n_))
I7 = sp.simplify((n_ / (2 * R ** 2) - sp.Rational(1, 2)) - sp.Rational(1, 2) * (4 * sp.pi * n_ / (4 * sp.pi * R ** 2) - 1))
out("## Identities [identity; sympy]")
out("")
out("| statement | sympy residual |")
out("|---|---|")
out(f"| Laplacian on S^2(R) of 2n log sin(theta/2) = -n/R^2 away from the pole | {I1} |")
out(f"| Laplacian on S^2(R) of 2n log cos(theta/2) = -n/R^2 away from the south pole (spread control) | {I1b} |")
out(f"| t = log tan(theta/2): d theta/dt = sin theta | {I2} |")
out(f"| sin^2 theta = sech^2 t | {I3} |")
out(f"| sin^2(theta/2) = e^(2t)/(1 + e^(2t)) | {I3b} |")
out(f"| u_tt = sin^2(theta) (u_theta theta + cot theta u_theta), so the spec ODE (L17) times sin^2 theta is u_tt = sech^2 t (n - R^2 + R^2 sin^(2n)(theta/2) e^u) | {I4} |")
out(f"| P3: (pi n/2)(A_B/A + A/A_B) - pi n = (A - A_B)^2/(8A) with A_B = 4 pi n | {I5} |")
out(f"| P3 in the spec's form pi n v^2 (A - A_B)^2/(2 A A_B) equals (A - A_B)^2/(8A) | {I6} |")
out(f"| LLL mass^2: eB - 1/2 = n/(2R^2) - 1/2 = (1/2)(A_B/A - 1) | {I7} |")
out("With h = log|phi|^2 = 2n log sin(theta/2) + u, BPS gives Laplacian(h) = e^h - 1 + 4 pi n delta_N, hence the spec ODE (L17), as Venus checked. "
    "Integrating the ODE over the sphere with u'(0) = u'(pi) = 0 gives the integral of |phi|^2 = A - 4 pi n (C1) [identity].")
out("")


# ---------------- background: Taubes BVP in t ----------------
def logsig2(tt):          # log sin^2(theta/2) = log sigma(2t)
    return -np.logaddexp(0.0, -2.0 * tt)


def logcos2(tt):          # log cos^2(theta/2)
    return -np.logaddexp(0.0, 2.0 * tt)


def sech2(tt):
    return np.exp(2.0 * (math.log(2.0) - np.logaddexp(tt, -tt)))


def solve_bg(n, p, R2, guess=None):
    """u'' = sech^2 t (n - R^2 + R^2 sin^{2p}(theta/2) cos^{2(n-p)}(theta/2) e^u), u'(+-T) = 0."""
    def lw(tt):
        return p * logsig2(tt) + (n - p) * logcos2(tt)

    def f(tt, y):
        s2 = sech2(tt)
        return np.vstack([y[1], s2 * (n - R2 + R2 * np.exp(lw(tt) + y[0]))])

    def jac(tt, y):
        s2 = sech2(tt)
        J = np.zeros((2, 2, tt.size))
        J[0, 1] = 1.0
        J[1, 0] = s2 * R2 * np.exp(lw(tt) + y[0])
        return J

    bc = lambda ya, yb: np.array([ya[1], yb[1]])
    bcj = lambda ya, yb: (np.array([[0.0, 1.0], [0.0, 0.0]]), np.array([[0.0, 0.0], [0.0, 1.0]]))
    tt = np.linspace(-T_BVP, T_BVP, N_BVP0)
    if guess is None:
        y0 = np.zeros((2, tt.size))
    else:
        y0 = guess(tt)
    s = solve_bvp(f, bc, tt, y0, fun_jac=jac, bc_jac=bcj, tol=BVP_TOL, max_nodes=2_000_000)
    return s, lw


def bg_fields(sol, lw, n, p, R2, tt):
    y = sol.sol(tt)
    u, up = y[0], y[1]
    h = lw(tt) + u
    sig = np.exp(logsig2(tt))
    hp = 2 * p * (1 - sig) - 2 * (n - p) * sig + up
    f = np.exp(h / 2)
    Om2 = R2 * sech2(tt)
    return dict(u=u, up=up, h=h, hp=hp, f=f, f2=np.exp(h), Om2=Om2, Om=np.sqrt(Om2))


def integrals(sol, lw, n, p, R2):
    tt = np.linspace(-T_BVP, T_BVP, N_QUAD)
    b = bg_fields(sol, lw, n, p, R2, tt)
    phi2 = 2 * np.pi * simpson(b["Om2"] * b["f2"], x=tt)
    E = 2 * np.pi * simpson(b["f2"] * b["hp"] ** 2 / 4 + b["Om2"] * (1 - b["f2"]) ** 2 / 4, x=tt)
    return phi2, E, float(np.max(b["f2"]))


# ---------------- fluctuation operator, sector k ----------------
def sector_matrices(bgfun, n, p, k, H, T):
    """Real sector-k form of the background-gauge Hessian K = int |P|^2 + |S/Omega|^2 dt, mass M = int Omega^2(|eta|^2 + |b|^2) dt.
    eta ~ e^{i(p+k)phi} (regular gauge at N), alpha = a_t + i a_phi = i Omega b e^{ik phi}.
    P = eta' - nu eta + f Omega b,  S/Omega = b' + (k - tanh t) b + Omega f eta,  nu = k + h'/2."""
    tt = np.arange(-T, T + H / 2, H)
    Mn = tt.size
    th_ = 0.5 * (tt[1:] + tt[:-1])
    bh = bgfun(th_)
    bn = bgfun(tt)
    nu = k + bh["hp"] / 2
    fO = bh["f"] * bh["Om"]
    km = k - np.tanh(th_)
    J = Mn - 1
    rows = np.arange(J)
    Dm = sps.csr_matrix((np.r_[-np.ones(J), np.ones(J)] / H, (np.r_[rows, rows], np.r_[rows, rows + 1])), shape=(J, Mn))
    Av = sps.csr_matrix((np.full(2 * J, 0.5), (np.r_[rows, rows], np.r_[rows, rows + 1])), shape=(J, Mn))
    Pe = Dm - sps.diags(nu) @ Av
    Pb = sps.diags(fO) @ Av
    Se = sps.diags(fO) @ Av
    Sb = Dm + sps.diags(km) @ Av
    Lmat = sps.bmat([[Pe, Pb], [Se, Sb]]).tocsr()
    wt = np.full(Mn, H)
    wt[0] = wt[-1] = H / 2
    Mdiag = np.r_[wt * bn["Om2"], wt * bn["Om2"]]
    free = np.ones(2 * Mn, bool)
    if p + k != 0:
        free[0] = False                 # eta Dirichlet at N
    if p + k - n != 0:
        free[Mn - 1] = False            # eta Dirichlet at S (regular-gauge index p + k - n)
    if k != -1:
        free[Mn] = False                # b Dirichlet at N
    if k != 1:
        free[2 * Mn - 1] = False        # b Dirichlet at S
    Lf = Lmat[:, free]
    K = (H * (Lf.T @ Lf)).tocsc()
    Mm = sps.diags(Mdiag[free]).tocsc()
    return K, Mm, free, tt, bn


def lowest(K, Mm, nev=NEV):
    w, v = spla.eigsh(K, k=nev, M=Mm, sigma=-1e-3, which="LM")
    o = np.argsort(w)
    return w[o], v[:, o]


# ---------------- C2: symmetric phase -D^2 ----------------
def symmetric_spectrum(n, R2, m, H, T, nev):
    tt = np.arange(-T, T + H / 2, H)
    Mn = tt.size
    Aphi = 0.5 * n * (1 + np.tanh(tt))       # uniform B = n/(2R^2): F_flat = Omega^2 B, A_phi(-inf) = 0
    th_ = 0.5 * (tt[1:] + tt[:-1])
    J = Mn - 1
    rows = np.arange(J)
    Dm = sps.csr_matrix((np.r_[-np.ones(J), np.ones(J)] / H, (np.r_[rows, rows], np.r_[rows, rows + 1])), shape=(J, Mn))
    wt = np.full(Mn, H)
    wt[0] = wt[-1] = H / 2
    K = H * (Dm.T @ Dm) + sps.diags(wt * (m - Aphi) ** 2)
    Mdiag = wt * R2 * sech2(tt)
    free = np.ones(Mn, bool)
    if m != 0:
        free[0] = False
    if m != n:
        free[-1] = False
    K = K.tocsr()[free][:, free].tocsc()
    Mm = sps.diags(Mdiag[free]).tocsc()
    w = spla.eigsh(K, k=nev, M=Mm, sigma=-1e-3, which="LM")[0]
    return np.sort(w)


# ======================= runs =======================
out("## Background solutions (Taubes ODE, all n vortices at the north pole) [computed]")
out("")
out(f"Solved in t = log tan(theta/2) on [-{T_BVP:g}, {T_BVP:g}] (the spec ODE times sin^2 theta, identity above), scipy solve_bvp, tol {BVP_TOL:g}, "
    "u'(+-T) = 0. Near the cap (eps <= 0.1) every solve starts from Venus's constant u0 = log[(n+1)(1 - A_B/A)]; eps = 1 and 4 are reached by "
    f"continuation through eps = {CONT_EPS} [assumed].")
out("")
out("| n | eps | A | status | mesh nodes | max BVP residual | integral |phi|^2 | A - 4 pi n | C1 rel. err | energy | pi n | energy rel. err | max|phi|^2 | P2 ratio max|phi|^2/(1 - A_B/A) | theta-form (L17) residual |")
out("|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
BG = {}
c1_ok = True
p2 = {}
for n in N_LIST:
    sols = {}
    prev = None
    for eps in sorted(set(EPS_LIST) | set(CONT_EPS)):
        R2 = n * (1 + eps)
        Aa = 4 * np.pi * R2
        if eps <= 0.1:
            u0 = math.log((n + 1) * (1 - 1 / (1 + eps)))
            guess = lambda tt, u0=u0: np.vstack([np.full(tt.size, u0), np.zeros(tt.size)])
        else:
            guess = lambda tt, s=prev: s.sol(tt)
        s, lw = solve_bg(n, n, R2, guess)
        prev = s
        sols[eps] = (s, lw)
    for eps in EPS_LIST:
        s, lw = sols[eps]
        R2 = n * (1 + eps)
        Aa = 4 * np.pi * R2
        phi2, E, mx = integrals(s, lw, n, n, R2)
        e1 = abs(phi2 - (Aa - 4 * np.pi * n)) / (Aa - 4 * np.pi * n)
        e2 = abs(E - np.pi * n) / (np.pi * n)
        c1_ok &= (e1 < C1_TOL) and (e2 < C1_TOL) and s.success
        rat = mx / (1 - 1 / (1 + eps))
        p2[(n, eps)] = rat
        # theta-form residual of the spec ODE (L17) at interior theta, by finite differences of u(theta)
        thg = np.linspace(0.3, np.pi - 0.3, 2001)
        tg = np.log(np.tan(thg / 2))
        ug = s.sol(tg)[0]
        dth = thg[1] - thg[0]
        u1 = np.gradient(ug, dth)
        u2 = np.gradient(u1, dth)
        rhs = n - R2 + R2 * np.sin(thg / 2) ** (2 * n) * np.exp(ug)
        res = np.max(np.abs((u2 + u1 / np.tan(thg) - rhs)[5:-5]))
        BG[(n, eps)] = (s, lw)
        out(f"| {n} | {eps:g} | {Aa:.6f} | {'ok' if s.success else s.message} | {s.x.size} | {np.max(s.rms_residuals):.1e} | {phi2:.10f} | {Aa - 4 * np.pi * n:.10f} | {e1:.1e} | "
            f"{E:.10f} | {np.pi * n:.10f} | {e2:.1e} | {mx:.6f} | {rat:.6f} | {res:.1e} |")
out("")
out("Profiles [computed]: |phi|^2 and B = (1 - |phi|^2)/2 at theta = 0, pi/4, pi/2, 3pi/4, pi (theta from the north pole, where the n vortices sit).")
out("")
out("| n | eps | |phi|^2 at theta = 0, pi/4, pi/2, 3pi/4, pi | B at the same theta |")
out("|---:|---:|---|---|")
for n in N_LIST:
    for eps in EPS_LIST:
        s, lw = BG[(n, eps)]
        thp = np.array([0.0, np.pi / 4, np.pi / 2, 3 * np.pi / 4, np.pi])
        tp = np.clip(np.log(np.tan(np.clip(thp, 1e-300, np.pi - 1e-15) / 2)), -T_BVP, T_BVP)
        f2p = np.exp(lw(tp) + s.sol(tp)[0])
        f2p[0] = 0.0                    # exact zero of order 2n at the pole
        out(f"| {n} | {eps:g} | " + ", ".join(f"{x:.6f}" for x in f2p) + " | " + ", ".join(f"{(1 - x) / 2:.6f}" for x in f2p) + " |")
out("")
out(f"**C1 [identity]: {'PASS' if c1_ok else 'FAIL'}** - integral |phi|^2 = A - 4 pi n and energy = pi n to relative error < {C1_TOL:g} at every (n, eps) [computed].")
out(f"The theta-form residual is max |u_thth + cot(theta) u_th - RHS| on theta in [0.3, pi - 0.3], with u_th, u_thth from numpy.gradient at step {dth:.6f}; it measures that second-order FD error, not the solution error.")
out("")

# ---------------- C2 ----------------
out("## C2 - symmetric phase (phi = 0, uniform B): spectrum of -D^2 [standard: Wu-Yang; Haldane 1983]")
out("")
out("Expected (spec): [l(l+1) - (n/2)^2]/R^2, l = n/2, n/2+1, ..., each with 2l+1 states; in this gauge level l occupies angular sectors "
    "m = n/2 - l ... n/2 + l, one state each. The LLL (l = n/2) is eB = n/(2R^2) with n+1 states; LLL mass^2 mu^2 = eB - 1/2.")
out("")
out("| n | eps | max rel. err over l <= n/2+3, all m | states per level found (l = n/2, n/2+1, ...) | expected 2l+1 | eB | mu^2 = eB - 1/2 | (1/2)(A_B/A - 1) |")
out("|---:|---:|---:|---|---|---:|---:|---:|")
c2_ok = True
for n in N_LIST:
    for eps in EPS_LIST:
        R2 = n * (1 + eps)
        lmax = n / 2 + C2_LEVELS - 1
        cnt = [0] * C2_LEVELS
        err = 0.0
        for m in range(int(round(n / 2 - lmax)), int(round(n / 2 + lmax)) + 1):
            l0 = max(n / 2, abs(m - n / 2))
            exp_ = [((l0 + j) * (l0 + j + 1) - (n / 2) ** 2) / R2 for j in range(C2_LEVELS)]
            nexp = [e for j, e in enumerate(exp_) if l0 + j <= lmax + 1e-9]
            w = symmetric_spectrum(n, R2, m, H_FL, T_FL, max(len(nexp), 1) + 1)
            for j, e in enumerate(nexp):
                err = max(err, abs(w[j] - e) / e)
                cnt[int(round(l0 + j - n / 2))] += 1
        expc = [int(round(2 * (n / 2 + j) + 1)) for j in range(C2_LEVELS)]
        ok = err < C2_TOL and cnt == expc
        c2_ok &= ok
        eB = n / (2 * R2)
        out(f"| {n} | {eps:g} | {err:.1e} | {cnt} | {expc} | {eB:.6f} | {eB - 0.5:.6f} | {0.5 * (1 / (1 + eps) - 1):.6f} |")
out("")
out(f"**C2 [standard]: {'PASS' if c2_ok else 'FAIL'}** (tolerance {C2_TOL:g}) [computed].")
out("")

# ---------------- vortex branch: zero modes and gap ----------------
out("## Vortex branch - fluctuation operator per sector k = m - n (background gauge) [computed]")
out("")
out("Operator: the second variation of the energy in background gauge, K = integral of |delta P|^2 + (delta Q^2 + G^2)/Omega^2, with P = (D_t + iD_phi)phi and "
    "Q = F - (Omega^2/2)(1 - |phi|^2) the Bogomolny expressions and G = div a - Omega^2 Im(phi* eta) the background-gauge condition, on the "
    "cylinder t = log tan(theta/2) with conformal factor Omega = R sech t; kinetic metric M = integral of Omega^2|eta|^2 + |a|^2. omega^2 = generalised "
    f"eigenvalues of (K, M). Finite differences: sum-of-squares form on a staggered grid, h = {H_FL:g}, t in [-{T_FL:g}, {T_FL:g}]. Each eigenvalue "
    "is one complex mode (two real modes). The background-gauge term lifts all pure-gauge directions, so there is no gauge zero mode left to remove; "
    "in k = 0 the lowest mode pairs the amplitude direction (eta = phi) with the global phase rotation (eta = i phi).")
out("")
out("| n | eps | zero modes per sector k = -n-2 ... 2 | C3 ok | lowest nonzero omega^2 per sector k = -n-2 ... 2 |")
out("|---:|---:|---|---|---|")
c3_ok = True
gap = {}
ovl = {}
zmax = 0.0
for n in N_LIST:
    for eps in EPS_LIST:
        R2 = n * (1 + eps)
        s, lw = BG[(n, eps)]
        bgfun = lambda tt, s=s, lw=lw, n=n, R2=R2: bg_fields(s, lw, n, n, R2, tt)
        zc, lown = [], []
        for k in range(-n - K_WINDOW, K_WINDOW + 1):
            Kk, Mk, free, tt, bn = sector_matrices(bgfun, n, n, k, H_FL, T_FL)
            w, v = lowest(Kk, Mk)
            z = int(np.sum(np.abs(w) < ZERO_TOL))
            if z:
                zmax = max(zmax, float(np.max(np.abs(w[np.abs(w) < ZERO_TOL]))))
            nz = w[np.abs(w) >= ZERO_TOL]
            zc.append(z)
            lown.append(nz[0] if nz.size else float("nan"))
            if k == 0:
                gap[(n, eps)] = nz[0]
                vec = v[:, np.where(np.abs(w) >= ZERO_TOL)[0][0]]
                full = np.zeros(free.size)
                full[free] = vec
                Mn = tt.size
                wt = np.full(Mn, H_FL)
                wt[0] = wt[-1] = H_FL / 2
                amp = np.r_[bn["f"], np.zeros(Mn)]
                Md = np.r_[wt * bn["Om2"], wt * bn["Om2"]]
                ovl[(n, eps)] = float((full @ (Md * amp)) ** 2 / ((full @ (Md * full)) * (amp @ (Md * amp))))
        expect = [1 if -n <= k <= -1 else 0 for k in range(-n - K_WINDOW, K_WINDOW + 1)]
        ok = zc == expect
        c3_ok &= ok
        out(f"| {n} | {eps:g} | {zc} | {ok} | " + ", ".join(f"{x:.6f}" for x in lown) + " |")
out("")
out(f"Largest |omega^2| counted as zero: {zmax:.1e} (threshold {ZERO_TOL:g}).")
out(f"**C3 [standard: Manton-Sutcliffe ch. 7]: {'PASS' if c3_ok else 'FAIL'}** - one complex position zero mode in each of k = -n..-1 (2n real), none in the other scanned sectors [computed].")
out("")

# ---------------- P1 ----------------
out("## P1 (Venus's argument) - amplitude-mode gap in the vortex's own sector k = 0 [prediction]")
out("")
out("| n | eps = delta = (A - A_B)/A_B | A | gap^2 (k = 0) | ratio gap^2/delta | A_B/A (leading-order prediction) | ratio - A_B/A | overlap of the mode with eta = phi |")
out("|---:|---:|---:|---:|---:|---:|---:|---:|")
for n in N_LIST:
    for eps in EPS_LIST:
        g = gap[(n, eps)]
        out(f"| {n} | {eps:g} | {4 * np.pi * n * (1 + eps):.6f} | {g:.8f} | {g / eps:.6f} | {1 / (1 + eps):.6f} | {g / eps - 1 / (1 + eps):+.2e} | {ovl[(n, eps)]:.6f} |")
out("")
p1_ok = True
out("| n | fit over eps | intercept (eps -> 0) | |intercept - 1| | within 3% | slope d(ratio)/d(delta) (expected about -1) | slope over the 4 near-cap eps |")
out("|---:|---|---:|---:|---|---:|---:|")
p1fit = {}
for n in N_LIST:
    xs = np.array(P1_FIT_EPS)
    ys = np.array([gap[(n, e)] / e for e in P1_FIT_EPS])
    sl, ic = np.polyfit(xs, ys, 1)
    x4 = np.array(EPS_NEAR)
    y4 = np.array([gap[(n, e)] / e for e in EPS_NEAR])
    sl4 = np.polyfit(x4, y4, 1)[0]
    ok = abs(ic - 1) <= P1_TOL
    p1_ok &= ok
    p1fit[n] = (ic, sl)
    out(f"| {n} | {P1_FIT_EPS} | {ic:.6f} | {abs(ic - 1):.2e} | {ok} | {sl:.6f} | {sl4:.6f} |")
out("")
out(f"**P1: {'PASS' if p1_ok else 'MISS'}** (intercept within {P1_TOL:.0%} of 1 for every n) [computed].")
out("")
# resolution check
out(f"Resolution check [finite-size]: gap^2 at eps = {EPS_LIST[0]:g} with h = {H_FL:g} vs h = {H_FL_CHECK:g}:")
for n in N_LIST:
    R2 = n * (1 + EPS_LIST[0])
    s, lw = BG[(n, EPS_LIST[0])]
    bgfun = lambda tt, s=s, lw=lw, n=n, R2=R2: bg_fields(s, lw, n, n, R2, tt)
    Kk, Mk, free, tt, bn = sector_matrices(bgfun, n, n, 0, H_FL_CHECK, T_FL)
    w, _ = lowest(Kk, Mk)
    g2 = w[np.abs(w) >= ZERO_TOL][0]
    out(f"- n = {n}: {gap[(n, EPS_LIST[0])]:.10f} vs {g2:.10f}, relative change {abs(g2 - gap[(n, EPS_LIST[0])]) / g2:.1e}.")
out("")

# ---------------- P2 ----------------
out("## P2 [computed by us from Baptista-Manton eq. (7) with all zeros at one pole; to check] - max|phi|^2/(1 - A_B/A) -> n + 1 (print only)")
out("")
out("| n | ratio at eps = " + " | ".join(f"{e:g}" for e in EPS_LIST) + " | linear extrapolation to eps = 0 (fit over " + f"{P1_FIT_EPS}) | n + 1 |")
out("|---:|" + "---:|" * len(EPS_LIST) + "---:|---:|")
for n in N_LIST:
    ic2 = np.polyfit(P1_FIT_EPS, [p2[(n, e)] for e in P1_FIT_EPS], 1)[1]
    out(f"| {n} | " + " | ".join(f"{p2[(n, e)]:.6f}" for e in EPS_LIST) + f" | {ic2:.6f} | {n + 1} |")
out("")

# ---------------- P3 ----------------
out("## P3 [identity, print only] - symmetric phase above the vortex")
out("")
out("| n | eps | E_sym = 2 pi^2 n^2/A + A/8 | E_vortex (numerical) | E_sym - E_vortex | (A - A_B)^2/(8A) | difference |")
out("|---:|---:|---:|---:|---:|---:|---:|")
for n in N_LIST:
    for eps in EPS_LIST:
        Aa = 4 * np.pi * n * (1 + eps)
        s, lw = BG[(n, eps)]
        _, E, _ = integrals(s, lw, n, n, n * (1 + eps))
        Es = 2 * np.pi ** 2 * n ** 2 / Aa + Aa / 8
        d = (Aa - 4 * np.pi * n) ** 2 / (8 * Aa)
        out(f"| {n} | {eps:g} | {Es:.10f} | {E:.10f} | {Es - E:.10e} | {d:.10e} | {Es - E - d:+.1e} |")
out("")

# ---------------- report-only controls ----------------
out("## Report only - spread-out control: p vortices at the north pole, n - p at the south pole")
out("")
out("Same code with sin^(2p)(theta/2) cos^(2(n-p))(theta/2) in the ODE; start u0 = log[(1 - A_B/A)/B(p+1, n-p+1)] (the LLL profile normalised by C1) [assumed]; "
    "gap^2 = lowest nonzero omega^2 in the sector of phi itself (k = 0).")
out("")
out("| n | p | eps | C1 rel. err | gap^2 | ratio gap^2/eps | same ratio, all at one pole | difference |")
out("|---:|---:|---:|---:|---:|---:|---:|---:|")
spread_fit = {}
for (n, p) in SPREAD:
    ys = []
    for eps in P1_FIT_EPS:
        R2 = n * (1 + eps)
        Aa = 4 * np.pi * R2
        Bf = math.gamma(p + 1) * math.gamma(n - p + 1) / math.gamma(n + 2)
        u0 = math.log((1 - 1 / (1 + eps)) / Bf)
        s, lw = solve_bg(n, p, R2, lambda tt, u0=u0: np.vstack([np.full(tt.size, u0), np.zeros(tt.size)]))
        phi2, E, _ = integrals(s, lw, n, p, R2)
        e1 = abs(phi2 - (Aa - 4 * np.pi * n)) / (Aa - 4 * np.pi * n)
        bgfun = lambda tt, s=s, lw=lw, n=n, p=p, R2=R2: bg_fields(s, lw, n, p, R2, tt)
        Kk, Mk, free, tt, bn = sector_matrices(bgfun, n, p, 0, H_FL, T_FL)
        w, _ = lowest(Kk, Mk)
        g = w[np.abs(w) >= ZERO_TOL][0]
        ys.append(g / eps)
        out(f"| {n} | {p} | {eps:g} | {e1:.1e} | {g:.8f} | {g / eps:.6f} | {gap[(n, eps)] / eps:.6f} | {g / eps - gap[(n, eps)] / eps:+.2e} |")
    sl, ic = np.polyfit(P1_FIT_EPS, ys, 1)
    spread_fit[(n, p)] = (ic, sl)
out("")
out("Spread-control fits (same rule as P1): " + "; ".join(f"n = {n}, p = {p}: intercept {ic:.6f}, slope {sl:.6f}" for (n, p), (ic, sl) in spread_fit.items())
    + " [computed; report only].")
out("")

out("## Report only - far from the cap: sphere profile vs plane n-vortex")
out("")


def plane_profile(n):
    sl_ = np.log(PLANE_RMAX)
    def f(ss, y):
        return np.vstack([y[1], np.exp(2 * ss) * (np.exp(2 * n * ss + y[0]) - 1)])
    bc = lambda ya, yb: np.array([ya[1], yb[0] + 2 * n * sl_])
    ss = np.linspace(-T_BVP, sl_, N_BVP0)
    y0 = np.vstack([-2 * n * np.log1p(np.exp(ss)) , np.zeros(ss.size)])
    return solve_bvp(f, bc, ss, y0, tol=BVP_TOL, max_nodes=2_000_000)


out(f"|phi|^2 against geodesic distance d = R theta from the pole, compared for d <= {PLANE_DCMP:g} with the plane vortex (plane BVP in log r, r <= {PLANE_RMAX:g}).")
out("")
out("| n | eps | R | max |phi|^2 sphere - plane over d <= " + f"{PLANE_DCMP:g}" + " |")
out("|---:|---:|---:|---:|")
for n in N_LIST:
    ps = plane_profile(n)
    for eps in [e for e in EPS_LIST if e >= 1]:
        R2 = n * (1 + eps)
        Rr = math.sqrt(R2)
        d = np.linspace(1e-3, PLANE_DCMP, 400)
        thv = d / Rr
        tv = np.log(np.tan(thv / 2))
        s, lw = BG[(n, eps)]
        sph = np.exp(lw(tv) + s.sol(tv)[0])
        pl = np.exp(2 * n * np.log(d) + ps.sol(np.log(d))[0])
        out(f"| {n} | {eps:g} | {Rr:.6f} | {np.max(np.abs(sph - pl)):.4f} |")
out("")

# ---------------- grade ----------------
controls = c1_ok and c2_ok and c3_ok
grade = "PASS" if (controls and p1_ok) else ("PARTIAL" if controls else "FAIL")
out("## Summary")
out("")
out(f"- C1 [identity]: {'PASS' if c1_ok else 'FAIL'}; C2 [standard]: {'PASS' if c2_ok else 'FAIL'}; C3 [standard]: {'PASS' if c3_ok else 'FAIL'}.")
out(f"- P1 [prediction]: {'PASS' if p1_ok else 'MISS'} - intercepts " + ", ".join(f"n = {n}: {p1fit[n][0]:.6f}" for n in N_LIST)
    + "; slopes " + ", ".join(f"n = {n}: {p1fit[n][1]:.6f}" for n in N_LIST) + ".")
out(f"- **Grade by the fixed rule: {grade}**")
after = {f: crc_sha(os.path.join(SPEC_DIR, f)) for f in siblings}
out(f"- Spec folder files unchanged by the run (CRC32 and SHA-256 before = after): {before == after}.")
out(f"- Runtime: {time.time() - T0:.0f} s [computed].")
with open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(OUT) + "\n")
