"""Job 5c: vacuum flux share filter (algebra on top of Job Five).

RESULTS.md is written only by this script. No git. Job Five and Job Three
folders (including Orion's X files) are read-only inputs and are hash-audited.
Every number printed to RESULTS.md comes from a variable.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import math
import re
import sys
from pathlib import Path

import sympy as sp

HERE = Path(__file__).resolve().parent
J5 = Path(r"C:\Users\Akitt\radion-onshell-filter")
J3 = Path(r"C:\Users\Akitt\betti-berry-vacuum-filter")
ORION = ("X_POSTS_verbatim.md", "X_NOTES.md", "X_WINDOW_DEFS.md")

# ---------------- grades and scan settings, FIXED BEFORE THE FIRST RUN ----------------
PASS_N = 3                  # PASS needs n = 3 to be the only survivor ...
PASS_MIN_REL_WIDTH = 0.05   # ... over a dS Lambda_6 stretch with (hi-lo)/((hi+lo)/2) >= this
N_LIST = (1, 2, 3, 4, 5, 6)
K_LIST = (1, 2, 3, 4, 5, 6)
GRID_POINTS = 200000        # fine linear grid in (0, Lambda_max(n)) per n
EDGE_TOL = 1e-12            # p tolerance for closed-band membership at exact edges [computed rounding]
M6_NUM = 1.0                # unit normalisation as in Job Five [assumed input]
G6_NUM = 1.0                # unit normalisation as in Job Five [assumed input]
JOB5_SPOT_LAMBDA = 0.1      # Job Five's spot Lambda_6 row [assumed input, from Job Five]
N_ALL_CHECK = 1000          # fold-in: numeric all-n check of the conditional statement (analytic bound covers n beyond)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def snapshot(root: Path):
    return {str(p.relative_to(root)): sha(p) for p in sorted(root.rglob("*")) if p.is_file()}


def parse_j3_bands(path: Path):
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\| band (\d+) \| ([0-9.]+) \| ([0-9.]+) \|\s*$", line)
        if m:
            rows.append((int(m.group(1)), float(m.group(2)), float(m.group(3))))
    if not rows:
        raise RuntimeError("Job Three p-band table not found")
    return [(lo, hi) for _, lo, hi in sorted(rows)]


def parse_j5_bands(path: Path):
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\| (\d) \| \[([0-9.]+), ([0-9.]+)\] \| \[([-0-9.]+), ([-0-9.]+)\] \|", line)
        if m:
            rows.append((int(m.group(1)), float(m.group(2)), float(m.group(3))))
    return [(lo, hi) for _, lo, hi in sorted(rows)]


def fmt_iv(lo, hi, nd=6):
    return "[%.*f, %.*f]" % (nd, lo, nd, hi)


def main():
    before_j5, before_j3 = snapshot(J5), snapshot(J3)
    orion_before = {f: sha(J3 / f) for f in ORION}
    j3_bands = parse_j3_bands(J3 / "RESULTS.md")
    j5_bands = parse_j5_bands(J5 / "RESULTS.md")
    j3_src = (J3 / "run.py").read_text(encoding="utf-8")
    j5_src = (J5 / "run.py").read_text(encoding="utf-8")
    intrinsic_checks = [
        ("Job Three rho_res comes from `def rho_at(p):` (occupancy p only)", bool(re.search(r"^\s*def rho_at\(p\):", j3_src, re.M))),
        ("Job Three bands come from `def rho_window_bands():` (no flux argument)", bool(re.search(r"^\s*def rho_window_bands\(\):", j3_src, re.M))),
        ("Job Three flux enters only through `job_two_assumed_map(flux_n, radius_R)` (the old p = n/(3R^2) map)", "def job_two_assumed_map(flux_n, radius_R)" in j3_src),
        ("Job Five sets F_thetaphi = n sin(theta)/2 (source of B)", "F_θφ = n sinθ/2" in j5_src),
    ]
    intrinsic = all(ok for _, ok in intrinsic_checks[:3])

    L = []
    w = L.append
    now = dt.datetime.now().astimezone()
    w("# RESULTS (generated by run.py - do not edit by hand)")
    w("")
    w("Job 5c: vacuum flux share filter. Approved through NanoRibbon (Akitti's go); specced by Helios.")
    w("Generated: %s (BST/local time, UTC%s:%s); Python %s, sympy %s." % (now.strftime("%Y-%m-%d %H:%M:%S"), now.strftime("%z")[:3], now.strftime("%z")[3:], sys.version.split()[0], sp.__version__))
    w("")
    w("Toy breathing-mode calculation on top of Job Five. Only R is dynamical. Not a complete compactification and not a solution to vacuum selection.")
    w("")
    w("Fixed grades (set before the first run): PASS = only n = %d survives over a dS Lambda_6 stretch with relative width >= %.2f, no s anywhere; PARTIAL = several n survive; FAIL = no n survives; a single non-PASS survivor = UNGRADED." % (PASS_N, PASS_MIN_REL_WIDTH))
    w("")
    w("## Source audit before run [computed, read-only]")
    w("")
    w("Job Five tree: %d files; Job Three tree: %d files." % (len(before_j5), len(before_j3)))
    for f, h in orion_before.items():
        w("- Orion file %s SHA-256 before: %s" % (f, h))
    w("- Job Three RESULTS.md %s; run.py %s." % (sha(J3 / "RESULTS.md"), sha(J3 / "run.py")))
    w("- Job Five RESULTS.md %s; run.py %s; README.md %s." % (sha(J5 / "RESULTS.md"), sha(J5 / "run.py"), sha(J5 / "README.md")))
    w("")

    # ---------------- band reuse ----------------
    w("## Band-reuse finding (Helios's catch) [computed from Job Three source, read-only]")
    w("")
    w("| source check | result |")
    w("|---|---|")
    for label, ok in intrinsic_checks:
        w("| %s | %s |" % (label, ok))
    w("")
    if intrinsic:
        w("Case: **intrinsic**. Job Three's survival bands are fixed intervals of its own p, identical for every n; the old map only turned them into per-n R-bands. The p-bands are reused unchanged with the new p [hive-interpretation]; Job Three's per-n R-bands are not reused. No percolation was run.")
    else:
        w("Case: **mapping-dependent** (a source check failed); bands below would need recomputing in the new variable.")
    w("")
    w("| band | p interval (Job Three code-derived table, primary) [computed in Job Three; finite-size] | p interval (Job Five interpolation, cross-check) [post-hoc] |")
    w("|---|---|---|")
    for i, (lo, hi) in enumerate(j3_bands):
        cross = fmt_iv(*j5_bands[i]) if i < len(j5_bands) else "-"
        w("| %d | %s | %s |" % (i + 1, fmt_iv(lo, hi), cross))
    w("Per-n band used for every n = %s: the same list above [identity of the reuse]." % ", ".join(str(n) for n in N_LIST))
    w("")

    # ---------------- Stage 0 symbolic ----------------
    x, n, s, R, ksym = sp.symbols("x n s R k", positive=True)
    Lam, M6, g6, G, e = sp.symbols("Lambda_6 M_6 g_6 G e", positive=True)
    a = 4 * sp.pi
    b = 4 * sp.pi * M6**4
    c = sp.pi / (2 * g6**2)
    V = a * Lam / x - b / x**2 + c * n**2 / x**3
    Q = a * Lam * x**2 - 2 * b * x + 3 * c * n**2
    Vmin_form = (b * x - 2 * c * n**2) / x**3
    B = n / (2 * g6 * R**2)
    rhoF = B**2 / 2
    flux_term = c * n**2 / x**3
    lam_term = a * Lam / x
    curv_term = b / x**2
    p_flux_sym = flux_term / (flux_term + lam_term)
    p_curv_sym = flux_term / (flux_term + lam_term + curv_term)
    xf = 2 * c * n**2 / b
    Lf = b**2 / (4 * a * c * n**2)
    Lam_s = (1 - s**2) * b**2 / (3 * a * c * n**2)   # s = sqrt(1-u), u = (n/n_max)^2
    x1_s = 3 * c * n**2 / (b * (1 + s))
    rss = {M6: (1 / (8 * sp.pi * G)) ** sp.Rational(1, 4), g6: e}
    xf_rss = sp.simplify(xf.subs(rss))
    Lf_rss = sp.simplify(Lf.subs(rss))
    p_flat = sp.simplify(p_flux_sym.subs({x: xf, Lam: Lf}))
    pc_flat = sp.simplify(p_curv_sym.subs({x: xf, Lam: Lf}))
    p_s = sp.simplify(p_flux_sym.subs({Lam: Lam_s, x: x1_s}))
    pc_s = sp.simplify(p_curv_sym.subs({Lam: Lam_s, x: x1_s}))
    p_s_closed = (1 + s) / (2 * (2 - s))
    pc_s_closed = (1 + s) / (7 - 2 * s)
    nmax2 = b**2 / (3 * a * c * Lam)
    Lam_pole = sp.simplify(Lam_s.subs(s, 2))
    Lam_pole_c = sp.simplify(Lam_s.subs(s, sp.Rational(7, 2)))
    checks = [
        ("B convention: 4 pi R^2 (B^2/2) equals Job Five's Jordan flux term pi n^2/(2 g_6^2 R^2)", sp.simplify(4 * sp.pi * R**2 * rhoF - sp.pi * n**2 / (2 * g6**2 * R**2)) == 0, "identity"),
        ("Flux term of V: 4 pi x (B^2/2)/x^2 = c n^2/x^3", sp.simplify(4 * sp.pi * x * rhoF.subs(R, sp.sqrt(x)) / x**2 - flux_term) == 0, "identity"),
        ("Lambda term of V: 4 pi x Lambda_6/x^2 = a Lambda_6/x", sp.simplify(4 * sp.pi * x * Lam / x**2 - lam_term) == 0, "identity"),
        ("Curvature term of V: 4 pi x (-M_6^4/x)/x^2 = -b/x^2 (density -M_6^4 R_2/2, R_2 = 2/R^2)", sp.simplify(4 * sp.pi * x * (-M6**4 / x) / x**2 + curv_term) == 0, "identity"),
        ("So p_flux = (B^2/2)/(B^2/2 + Lambda_6) = flux term/(flux term + Lambda term) of V", sp.simplify(rhoF.subs(R, sp.sqrt(x)) / (rhoF.subs(R, sp.sqrt(x)) + Lam) - p_flux_sym) == 0, "identity"),
        ("V at a stationary point: V - (b x - 2 c n^2)/x^3 = Q/x^3 with V' = -Q/x^4, so V_min = (b x - 2 c n^2)/x^3", (sp.simplify(V - Vmin_form - Q / x**3) == 0) and (sp.simplify(sp.diff(V, x) + Q / x**4) == 0), "identity"),
        ("Flat point x* = 2 c n^2/b, Lambda_6 = b^2/(4 a c n^2): V' = 0 and V = 0", (sp.simplify(sp.diff(V, x).subs({x: xf, Lam: Lf})) == 0) and (sp.simplify(V.subs({x: xf, Lam: Lf})) == 0), "identity"),
        ("RSS balance at the flat point: B^2/2 = Lambda_6", sp.simplify(rhoF.subs(R, sp.sqrt(xf)) - Lf) == 0, "identity"),
        ("x* = n^2/(4 g_6^2 M_6^4)", sp.simplify(xf - n**2 / (4 * g6**2 * M6**4)) == 0, "identity"),
        ("Tuned Lambda_6 = 2 g_6^2 M_6^8/n^2", sp.simplify(Lf - 2 * g6**2 * M6**8 / n**2) == 0, "identity"),
        ("RSS units M_6^4 = 1/(8 pi G), g_6 = e: x* = a_RSS^2 = 2 pi G n^2/e^2", sp.simplify(xf_rss - 2 * sp.pi * G * n**2 / e**2) == 0, "standard: RSS 1983; identity"),
        ("RSS units: tuned Lambda_6 = e^2/(32 pi^2 G^2 n^2)", sp.simplify(Lf_rss - e**2 / (32 * sp.pi**2 * G**2 * n**2)) == 0, "standard: RSS 1983; identity"),
        ("Stable root in s = sqrt(1-u), u = (n/n_max)^2, n_max^2 = b^2/(3 a c Lambda_6): x_1 = 3 c n^2/(b(1+s)) solves Q = 0 and sqrt(D) = b s", (sp.simplify(Q.subs({Lam: Lam_s, x: x1_s})) == 0) and (sp.simplify(b**2 - 3 * a * c * Lam_s * n**2 - (b * s)**2) == 0) and (sp.simplify(3 * a * c * Lam_s * n**2 / b**2 - (1 - s**2)) == 0), "identity"),
        ("p_flux on-shell = (1+s)/(2(2-s)), a function of n/n_max only", sp.simplify(p_s - p_s_closed) == 0, "identity"),
        ("p_curv on-shell = (1+s)/(7-2s), a function of n/n_max only", sp.simplify(pc_s - pc_s_closed) == 0, "identity"),
        ("dS sign: b x_1 - 2 c n^2 = c n^2 (1-2s)/(1+s), so dS iff s < 1/2 iff Lambda_6 > b^2/(4 a c n^2)", sp.simplify(b * x1_s - 2 * c * n**2 - c * n**2 * (1 - 2 * s) / (1 + s)) == 0, "identity"),
        ("Negative Lambda_6 means s > 1, so p_flux > 1; pole at s = 2, i.e. Lambda_6 = -b^2/(a c n^2)", sp.simplify(Lam_pole + b**2 / (a * c * n**2)) == 0, "identity"),
        ("Scaling: V(k^2 x; k n, Lambda_6/k^2) = k^-4 V(x; n, Lambda_6), so every ratio of V's terms is k-invariant", sp.simplify(V.subs({x: ksym**2 * x, n: ksym * n, Lam: Lam / ksym**2}, simultaneous=True) - V / ksym**4) == 0, "identity"),
    ]
    w("## Stage 0 - identities [identity; sympy]")
    w("")
    w("| check | sympy result | tag |")
    w("|---|---|---|")
    for label, ok, tag in checks:
        w("| %s | %s | [%s] |" % (label, ok, tag))
    w("")
    w("Printed symbolic results [identity]: p_flux at the flat point = %s; p_curv at the flat point = %s; n_max^2 = %s; RSS-unit x* = %s; RSS-unit tuned Lambda_6 = %s; p_curv pole for negative Lambda_6 at Lambda_6 = %s." % (p_flat, pc_flat, sp.simplify(nmax2), xf_rss, Lf_rss, Lam_pole_c))
    w("RSS unit map [standard: RSS 1983]: Randjbar-Daemi, Salam & Strathdee, Nucl. Phys. B 214 (1983) 491.")
    w("")

    # ---------------- numerics ----------------
    aa = float(sp.N(a))
    bb = float(sp.N(b.subs(M6, M6_NUM)))
    cc = float(sp.N(c.subs(g6, G6_NUM)))
    w("Numeric convention [assumed input]: M_6 = %.1f, g_6 = %.1f, so a = %.9f, b = %.9f, c = %.9f, c/b = %.6f." % (M6_NUM, G6_NUM, aa, bb, cc, cc / bb))
    w("")

    def lam_max(k):
        return bb**2 / (3 * aa * cc * k * k)

    def lam_flat(k):
        return bb**2 / (4 * aa * cc * k * k)

    def onshell(Lv, k):
        D = bb * bb - 3 * aa * cc * Lv * k * k
        if not (Lv > 0 and D > 0):
            return None
        xm = 3 * cc * k * k / (bb + math.sqrt(D))
        fl = cc * k * k / xm**3
        la = aa * Lv / xm
        cu = bb / xm**2
        Vm = la - cu + fl
        vxx = 2 * aa * Lv / xm**3 - 6 * bb / xm**4 + 12 * cc * k * k / xm**5
        return {"x": xm, "p_flux": fl / (fl + la), "p_curv": fl / (fl + la + cu), "V": Vm, "Vform": (bb * xm - 2 * cc * k * k) / xm**3, "Vscale": la + cu + fl, "vxx": vxx, "B2half": fl / (aa / xm)}

    versions = {
        "p_flux": {"s_of_p": lambda p: (4 * p - 1) / (1 + 2 * p), "p_of_s": lambda sv: (1 + sv) / (2 * (2 - sv)), "tag": "[hive-interpretation; curvature left out: assumed]"},
        "p_curv": {"s_of_p": lambda p: (7 * p - 1) / (1 + 2 * p), "p_of_s": lambda sv: (1 + sv) / (7 - 2 * sv), "tag": "[hive-interpretation; |curvature| in denominator: assumed]"},
    }
    for ver in versions.values():
        ver["p_at_lam0"] = ver["p_of_s"](1.0)      # Lambda_6 -> 0+ (s -> 1), open end
        ver["p_at_lammax"] = ver["p_of_s"](0.0)    # Lambda_6 -> Lambda_max (s -> 0), critical, excluded

    def in_band(pv, bands):
        for i, (lo, hi) in enumerate(bands):
            if lo - EDGE_TOL <= pv <= hi + EDGE_TOL:
                return i + 1
        return 0

    # Stage 0 table
    w("### Stage 0 table - exactly flat RSS point per n [identity; tuned]")
    w("")
    w("| n | x* | Lambda_6 (flat) | B^2/2 at x* | p_flux | p_curv | 1/2 inside band | distance 1/2 - band lo | distance band hi - 1/2 |")
    w("|---:|---:|---:|---:|---:|---:|---|---:|---:|")
    half = float(p_flat)
    for k in N_LIST:
        xs_ = 2 * cc * k * k / bb
        Lf_ = lam_flat(k)
        fl = cc * k * k / xs_**3
        la = aa * Lf_ / xs_
        cu = bb / xs_**2
        bi = in_band(half, j3_bands)
        if bi:
            lo, hi = j3_bands[bi - 1]
            d1, d2 = half - lo, hi - half
        else:
            near = min(j3_bands, key=lambda bd: min(abs(half - bd[0]), abs(half - bd[1])))
            d1, d2 = half - near[0], near[1] - half
        w("| %d | %.6f | %.6f | %.6f | %.12f | %.12f | %s | %.6f | %.6f |" % (k, xs_, Lf_, fl / (aa / xs_), fl / (fl + la), fl / (fl + la + cu), ("band %d" % bi) if bi else "none", d1, d2))
    w("")
    w("Wall [by construction]: p_flux = %s at the flat point for every n, so the flat point cannot select n. Whether 1/2 is inside a band is the same answer for every n." % p_flat)
    w("")

    # ---------------- Stage 1 ----------------
    w("## Stage 1 - p_on along the stable root, 0 < Lambda_6 < Lambda_max(n) [computed]")
    w("")
    w("Negative Lambda_6 [identity]: on the AdS minimum s > 1, so p_flux > 1 (not a share). The denominator vanishes at Lambda_6 = -b^2/(a c n^2), so p is undefined there; Lambda_6 <= 0 is excluded. Lambda_6 = Lambda_max(n) is the double-root critical point (no minimum, as in Job Five) and is excluded.")
    for vname, ver in versions.items():
        w("On-shell range of %s for Lambda_6 in (0, Lambda_max): (%.12f, %.12f), open at both ends; the same for every n [identity] %s." % (vname, ver["p_at_lammax"], ver["p_at_lam0"], ver["tag"]))
    w("")

    def windows_for(ver, k):
        lo_end, hi_end = ver["p_at_lammax"], ver["p_at_lam0"]
        segs = []
        for bi, (blo, bhi) in enumerate(j3_bands, 1):
            plo, phi = max(blo, lo_end), min(bhi, hi_end)
            if plo >= phi:
                continue
            open_lo = phi >= hi_end
            open_hi = plo <= lo_end
            La = (1 - ver["s_of_p"](phi) ** 2) * lam_max(k)
            Lb = (1 - ver["s_of_p"](plo) ** 2) * lam_max(k)
            Lf_ = lam_flat(k)
            parts = []
            if Lb <= Lf_:
                parts.append((La, Lb, "AdS"))
            elif La >= Lf_:
                parts.append((La, Lb, "dS"))
            else:
                parts.append((La, Lf_, "AdS"))
                parts.append((Lf_, Lb, "dS"))
            for lo, hi, kind in parts:
                segs.append({"band": bi, "lo": lo, "hi": hi, "kind": kind, "open_lo": open_lo and lo == La, "open_hi": open_hi and hi == Lb})
        return segs

    def grid_check(vname, k, segs):
        step = lam_max(k) / GRID_POINTS
        inside_prev = False
        runs = []
        start = None
        mono_ok = True
        sign_mismatch = 0
        vform_err = 0.0
        min_vxx = float("inf")
        p_prev = None
        last_in = None
        for i in range(1, GRID_POINTS):
            Lv = i * step
            st = onshell(Lv, k)
            pv = st[vname]
            if p_prev is not None and pv > p_prev + 1e-15:
                mono_ok = False
            p_prev = pv
            vform_err = max(vform_err, abs(st["V"] - st["Vform"]) / st["Vscale"])
            min_vxx = min(min_vxx, st["vxx"])
            kind = "dS" if Lv > lam_flat(k) else "AdS"
            if (st["V"] > 0) != (kind == "dS") and abs(st["V"]) > 1e-12:
                sign_mismatch += 1
            ins = in_band(pv, j3_bands) > 0
            if ins and not inside_prev:
                start = Lv
            if ins:
                last_in = Lv
            if not ins and inside_prev:
                runs.append((start, last_in))
            inside_prev = ins
        if inside_prev:
            runs.append((start, last_in))
        # compare with exact merged windows (merge dS/AdS parts of a band)
        merged = {}
        for sg in segs:
            m = merged.setdefault(sg["band"], [sg["lo"], sg["hi"]])
            m[0] = min(m[0], sg["lo"])
            m[1] = max(m[1], sg["hi"])
        exact = sorted(merged.values())
        max_dev = 0.0
        if len(exact) == len(runs):
            for (glo, ghi), (elo, ehi) in zip(runs, exact):
                max_dev = max(max_dev, abs(glo - elo), abs(ghi - ehi))
        else:
            max_dev = float("nan")
        return {"step": step, "runs": runs, "n_exact": len(exact), "max_dev": max_dev, "mono": mono_ok, "sign_mismatch": sign_mismatch, "vform_err": vform_err, "min_vxx": min_vxx}

    all_segs = {}
    grids = {}
    for vname, ver in versions.items():
        all_segs[vname] = {}
        grids[vname] = {}
        w("### Survival windows per n - %s %s" % (vname, ver["tag"]))
        w("")
        w("| n | Lambda_max(n) | Lambda_6 flat (dS/AdS boundary) | band | Lambda_6 window [exact closed form] | dS or AdS | relative width = width/midpoint | width/lower edge | p_on at window edges |")
        w("|---:|---:|---:|---:|---|---|---:|---:|---|")
        for k in N_LIST:
            segs = windows_for(ver, k)
            all_segs[vname][k] = segs
            grids[vname][k] = grid_check(vname, k, segs)
            if not segs:
                w("| %d | %.6f | %.6f | - | none | - | - | - | - |" % (k, lam_max(k), lam_flat(k)))
            for sg in segs:
                rel = (sg["hi"] - sg["lo"]) / ((sg["hi"] + sg["lo"]) / 2)
                pa = onshell(sg["lo"], k)[vname]
                pb = onshell(sg["hi"], k)[vname]
                w("| %d | %.6f | %.6f | %d | %s%.6f, %.6f%s | %s | %.6f | %.6f | %.6f / %.6f |" % (k, lam_max(k), lam_flat(k), sg["band"], "(" if sg["open_lo"] else "[", sg["lo"], sg["hi"], ")" if sg["open_hi"] else "]", sg["kind"], rel, (sg["hi"] - sg["lo"]) / sg["lo"], pa, pb))
        w("The shared edge Lambda_6 = b^2/(4 a c n^2) between an AdS and a dS part is the exactly flat point [tuned], neither dS nor AdS.")
        w("")
        w("Grid cross-check [computed]: %d points per n in (0, Lambda_max(n))." % GRID_POINTS)
        w("| n | grid step | grid windows (merged per band) | max |grid edge - exact edge| | p monotone decreasing in Lambda_6 | V sign vs flat-point rule mismatches | max |V - (b x - 2 c n^2)/x^3| / (sum of term magnitudes) | min V''(x_1) |")
        w("|---:|---:|---|---:|---|---:|---:|---:|")
        for k in N_LIST:
            gch = grids[vname][k]
            runs = "; ".join(fmt_iv(lo, hi) for lo, hi in gch["runs"]) or "none"
            w("| %d | %.3e | %s | %.3e | %s | %d | %.3e | %.6e |" % (k, gch["step"], runs, gch["max_dev"], gch["mono"], gch["sign_mismatch"], gch["vform_err"], gch["min_vxx"]))
        w("")

    # ---------------- fixed-Lambda uniqueness ----------------
    def uniqueness(vname):
        segs = all_segs[vname]
        pts = {0.0, lam_max(min(N_LIST))}
        for k in N_LIST:
            pts.add(lam_flat(k))
            for sg in segs[k]:
                pts.add(sg["lo"])
                pts.add(sg["hi"])
        pts = sorted(pts)
        out = []
        for l, r in zip(pts, pts[1:]):
            mid = 0.5 * (l + r)
            surv = tuple(k for k in N_LIST if any(sg["lo"] <= mid <= sg["hi"] for sg in segs[k]))
            kinds = tuple(("dS" if mid > lam_flat(k) else "AdS") for k in surv)
            if out and out[-1][2] == surv and out[-1][3] == kinds:
                out[-1][1] = r
            else:
                out.append([l, r, surv, kinds])
        return [o for o in out if o[2]]

    uniq = {}
    for vname, ver in versions.items():
        uniq[vname] = uniqueness(vname)
        w("### Which n survive at a fixed Lambda_6 - %s [computed]" % vname)
        w("")
        if not uniq[vname]:
            w("No Lambda_6 > 0 has any surviving n.")
        else:
            w("| Lambda_6 interval | surviving n | dS/AdS per surviving n |")
            w("|---|---|---|")
            for l, r, surv, kinds in uniq[vname]:
                w("| %s | %s | %s |" % (fmt_iv(l, r), ", ".join(str(k) for k in surv), ", ".join("n=%d %s" % (k, kd) for k, kd in zip(surv, kinds))))
        w("")

    # ---------------- k-family scaling ----------------
    w("## Scaling identity - k-family Lambda_6^(k) = (3/k)^2 Lambda_6^(3) [identity; computed]")
    w("")
    w("p_on depends only on n/n_max with n_max^2 = b^2/(3 a c Lambda_6); n -> k n with Lambda_6 -> Lambda_6/k^2 leaves p unchanged. Each k-family point is checked against **n = k's own band** (Job Three's band list for n = k, identical to n = 3's because the bands are intrinsic).")
    spots = []
    for sg in all_segs["p_flux"][3]:
        tagk = "band %d %s" % (sg["band"], sg["kind"])
        spots.append(("n=3 %s lower edge" % tagk, sg["lo"]))
        spots.append(("n=3 %s midpoint" % tagk, 0.5 * (sg["lo"] + sg["hi"])))
        spots.append(("n=3 %s upper edge" % tagk, sg["hi"]))
    spots.append(("n=3 flat point [tuned]", lam_flat(3)))
    spots.append(("Job Five spot Lambda_6", JOB5_SPOT_LAMBDA))
    w("")
    w("| point | Lambda_6^(3) | k | Lambda_6^(k) | below Lambda_max(k) | p_flux(n=k) | abs(p_flux(n=k) - p_flux(n=3)) | p_flux inside n=k band | abs(p_curv(n=k) - p_curv(n=3)) | p_curv inside n=k band |")
    w("|---|---:|---:|---:|---|---:|---:|---|---:|---|")
    max_dp = 0.0
    all_match = True
    for label, L3 in spots:
        st3 = onshell(L3, 3)
        for k in K_LIST:
            Lk = (3.0 / k) ** 2 * L3
            stk = onshell(Lk, k)
            dpf = abs(stk["p_flux"] - st3["p_flux"])
            dpc = abs(stk["p_curv"] - st3["p_curv"])
            max_dp = max(max_dp, dpf, dpc)
            inf_k = in_band(stk["p_flux"], j3_bands)
            in3 = in_band(st3["p_flux"], j3_bands)
            all_match &= (bool(inf_k) == bool(in3))
            w("| %s | %.6f | %d | %.6f | %s | %.12f | %.3e | %s | %.3e | %s |" % (label, L3, k, Lk, Lk < lam_max(k), stk["p_flux"], dpf, ("YES (band %d)" % inf_k) if inf_k else "NO", dpc, ("YES (band %d)" % in_band(stk["p_curv"], j3_bands)) if in_band(stk["p_curv"], j3_bands) else "NO"))
    w("")
    w("Max abs(p(n=k) - p(n=3)) over all k-family rows, both versions: %.3e [computed]. Membership at n = k equals membership at n = 3 for every row: %s [computed]." % (max_dp, all_match))
    if intrinsic and all_match:
        w("Case [identity]: Job Three's bands are the same for every n, so the k-family survives exactly. **The filter cannot select n on its own**; n-selection can only come from fixing Lambda_6.")
    else:
        w("Case: some k-family point fails, so n-dependence of the bands is doing the selecting.")
    w("")

    # ---------------- grades ----------------
    w("## Grades (thresholds fixed before the first run)")
    w("")

    def grade(vname):
        segs = all_segs[vname]
        surv = [k for k in N_LIST if segs[k]]
        ds3 = [sg for sg in segs.get(PASS_N, []) if sg["kind"] == "dS"]
        best = max(((sg["hi"] - sg["lo"]) / ((sg["hi"] + sg["lo"]) / 2) for sg in ds3), default=0.0)
        best_lo = max(((sg["hi"] - sg["lo"]) / sg["lo"] for sg in ds3), default=0.0)
        if not surv:
            g = "FAIL"
        elif surv == [PASS_N] and best >= PASS_MIN_REL_WIDTH:
            g = "PASS"
        elif len(surv) > 1:
            g = "PARTIAL"
        else:
            g = "UNGRADED (single survivor outside the fixed scheme)"
        return g, surv, best, best_lo

    w("| version | surviving n (any Lambda_6 > 0) | widest n=%d dS stretch, relative width = width/midpoint (graded) | same stretch, width/lower edge (for reference) | threshold (on width/midpoint) | grade |" % PASS_N)
    w("|---|---|---:|---:|---:|---|")
    grades = {}
    for vname, ver in versions.items():
        g, surv, best, best_lo = grade(vname)
        grades[vname] = g
        w("| %s %s | %s | %.6f | %.6f | %.2f | **%s** |" % (vname, ver["tag"], ", ".join(str(k) for k in surv) or "none", best, best_lo, PASS_MIN_REL_WIDTH, g))
    w("")
    w("Conditional statement [post-hoc], next to the fixed grades:")
    for vname in versions:
        only3 = [(l, r, kinds) for l, r, surv, kinds in uniq[vname] if surv == (PASS_N,)]
        if only3:
            parts = "; ".join("%s (%s)" % (fmt_iv(l, r), kinds[0]) for l, r, kinds in only3)
            ds_parts = [(l, r) for l, r, kinds in only3 if kinds[0] == "dS"]
            ds_txt = "; ".join("%s, relative width (width/midpoint) %.6f, width/lower edge %.6f" % (fmt_iv(l, r), (r - l) / ((r + l) / 2), (r - l) / l) for l, r in ds_parts) or "none"
            w("- %s: **n = %d alone for Lambda_6 in %s** (checked over n = %s); dS part: %s [post-hoc]." % (vname, PASS_N, parts, ", ".join(str(k) for k in N_LIST), ds_txt))
            for l, r in ds_parts:
                wm, wl = (r - l) / ((r + l) / 2), (r - l) / l
                w("  - Even this post-hoc 'n = %d alone' dS stretch is below the PASS width: width/midpoint %.6f < %.2f is %s; width/lower edge %.6f < %.2f is %s [computed]." % (PASS_N, wm, PASS_MIN_REL_WIDTH, wm < PASS_MIN_REL_WIDTH, wl, PASS_MIN_REL_WIDTH, wl < PASS_MIN_REL_WIDTH))
        else:
            w("- %s: there is no Lambda_6 for which n = %d survives alone [computed]." % (vname, PASS_N))
    w("Uniqueness cannot PASS from inside this run: by the scaling identity, something outside the run (a KK gap, a measured Lambda_4) has to fix Lambda_6 [assumed: remaining assumption]. No radius scale s appears anywhere [by construction].")
    w("")
    # ---------------- fold-in: all-n check of 'n = 3 alone' ----------------
    w("## All-n check of 'n = %d alone' (p_flux) [identity; computed]" % PASS_N)
    w("")
    vf = versions["p_flux"]
    lam_unit = lam_max(1)  # Lambda_6 = u * lam_unit / n^2, u = (n/n_max)^2 [identity]
    ub = [(1 - vf["s_of_p"](min(hi, vf["p_at_lam0"])) ** 2, 1 - vf["s_of_p"](max(lo, vf["p_at_lammax"])) ** 2) for lo, hi in j3_bands if max(lo, vf["p_at_lammax"]) < min(hi, vf["p_at_lam0"])]
    w("Band windows in u = (n/n_max)^2 = Lambda_6 n^2 / (b^2/(3ac)), the same for every n [identity]: %s; so window(n) = u-window x %.6f / n^2." % ("; ".join("band %d %s" % (i + 1, fmt_iv(a_, b_)) for i, (a_, b_) in enumerate(ub)), lam_unit))
    u1lo, u1hi = ub[0]
    r_lo, r_hi = u1lo / u1hi, u1hi / u1lo
    hits = [k for k in range(1, N_ALL_CHECK + 1) if r_lo < (PASS_N**2) / k**2 < r_hi]
    w("Band 1 vs band 1 [identity]: n's band-1 window overlaps n = %d's (positive length) iff %d/n^2 lies in the open ratio interval (u1_lo/u1_hi, u1_hi/u1_lo) = (%.6f, %.6f). Integers n = 1..%d with %d/n^2 in it: %s." % (PASS_N, PASS_N**2, r_lo, r_hi, N_ALL_CHECK, PASS_N**2, hits))
    nb_lo = PASS_N * math.sqrt(1.0 / r_hi)
    nb_hi = PASS_N * math.sqrt(1.0 / r_lo)
    w("  Analytic: the condition is %.6f < n < %.6f, which contains only the integer(s) %s [identity]." % (nb_lo, nb_hi, [k for k in range(max(1, math.floor(nb_lo)), math.ceil(nb_hi) + 1) if nb_lo < k < nb_hi]))
    if len(ub) > 1:
        u2lo, u2hi = ub[1]
        reach = u2hi * lam_unit / 1**2
        n3_b1_lo = u1lo * lam_unit / PASS_N**2
        w("Band 2 vs n = %d band 1 [identity]: the highest band-2 window of any n >= 1 is n = 1's, reaching Lambda_6 = %.6f; n = %d's band-1 window starts at %.6f; band 2 stays below it for every n: %s." % (PASS_N, reach, PASS_N, n3_b1_lo, reach < n3_b1_lo))
    u_top = max(h for _, h in ub)
    u_bot3 = min(l_ for l_, _ in ub)
    n_cut = PASS_N * math.sqrt(u_top / u_bot3)
    w("Cut-off [identity]: for n > %.6f every window of n lies below n = %d's lowest window edge (%.6f), so n = 1..%d covers all n >= 1 with room to spare." % (n_cut, PASS_N, u_bot3 * lam_unit / PASS_N**2, N_ALL_CHECK))

    def subtract(base, cuts):
        pieces = [base]
        for cl, ch in sorted(cuts):
            nxt = []
            for pl, ph in pieces:
                if ch <= pl or cl >= ph:
                    nxt.append((pl, ph))
                    continue
                if cl > pl:
                    nxt.append((pl, cl))
                if ch < ph:
                    nxt.append((ch, ph))
            pieces = nxt
        return [(pl, ph) for pl, ph in pieces if ph > pl]

    others = {}
    for k in range(1, N_ALL_CHECK + 1):
        if k == PASS_N:
            continue
        for sg in windows_for(vf, k):
            others.setdefault(k, []).append((sg["lo"], sg["hi"], sg["band"]))
    w("")
    w("| n = %d window (n = 1..6 analysis) | dS/AdS | other n in 1..%d overlapping it (band) | 'n = %d alone' pieces over n = 1..%d |" % (PASS_N, N_ALL_CHECK, PASS_N, N_ALL_CHECK))
    w("|---|---|---|---|")
    alone_all = []
    for sg in all_segs["p_flux"][PASS_N]:
        ov = sorted({(k, bnd) for k, lst in others.items() for lo_, hi_, bnd in lst if hi_ > sg["lo"] and lo_ < sg["hi"]})
        cuts = [(lo_, hi_) for k, lst in others.items() for lo_, hi_, _ in lst if hi_ > sg["lo"] and lo_ < sg["hi"]]
        pieces = subtract((sg["lo"], sg["hi"]), cuts)
        alone_all.extend((pl, ph, sg["kind"]) for pl, ph in pieces)
        w("| band %d %s | %s | %s | %s |" % (sg["band"], fmt_iv(sg["lo"], sg["hi"]), sg["kind"], ", ".join("n=%d (band %d)" % ov_ for ov_ in ov) or "none", "; ".join(fmt_iv(pl, ph) for pl, ph in pieces) or "none"))
    w("")
    ds_all = [(l_, h_) for l_, h_, kd in alone_all if kd == "dS"]
    w("All-n conditional statement [post-hoc; identity for the band-1 part]: **n = %d alone for all n >= 1 when Lambda_6 is in %s**." % (PASS_N, "; ".join("%s (%s)" % (fmt_iv(l_, h_), kd) for l_, h_, kd in alone_all)))
    w("dS part over all n: %s [computed]." % ("; ".join("%s, width/midpoint %.6f, width/lower edge %.6f" % (fmt_iv(l_, h_), (h_ - l_) / ((h_ + l_) / 2), (h_ - l_) / l_) for l_, h_ in ds_all) or "none"))
    w("Grades are unchanged by this check: they were fixed on n = %s [computed]." % ", ".join(str(k) for k in N_LIST))
    w("")
    w("## Walls")
    w("")
    w("- Flat RSS point: p_flux = %s for every n, so it cannot select n [by construction]." % p_flat)
    w("- Scaling: p_on is a function of n/n_max only and the bands are n-independent, so survival at (n, Lambda_6) implies survival at (k n, Lambda_6/k^2) [identity].")
    w("- Negative Lambda_6: p_flux > 1, with a pole at Lambda_6 = -b^2/(a c n^2); excluded [identity].")
    w("- Robustness: p_curv only reaches (%.6f, %.6f) on-shell; any band outside that range is unreachable [identity]." % (versions["p_curv"]["p_at_lammax"], versions["p_curv"]["p_at_lam0"]))
    w("- Job Three's bands are m = 16 finite-size values inside an assumed residual window [finite-size; assumed input].")
    w("")
    after_j5, after_j3 = snapshot(J5), snapshot(J3)
    orion_after = {f: sha(J3 / f) for f in ORION}
    w("## Source audit after run [computed]")
    w("")
    w("Job Five tree unchanged: %s; Job Three tree unchanged: %s; Orion X files unchanged: %s." % (before_j5 == after_j5, before_j3 == after_j3, orion_before == orion_after))
    (HERE / "RESULTS.md").write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
