#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Job B2 (Bradlow-cap line, folder 02, vacuum): does the vortex-gas pressure really blow up at the cap?
Spec: ../JOB_B2_VACUUM_PRESSURE_SPEC.md (Helios; Venus cleared; GitHub main 07c9d97). Writes RESULTS.md (ONLY ever written
by this script) next to itself. Reads B0's RESULTS.md (measured amplitude gaps) read-only; B0 files are not modified.
Run:  $env:PYTHONIOENCODING='utf-8'; python -B run.py
Every number in RESULTS.md is printed from a variable. All thresholds are fixed in the parameter block before the graded run.
"""
import os, re, time, platform, hashlib, zlib, math
import numpy as np
import scipy
from scipy.special import gammaln, logsumexp
import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC_DIR = os.path.dirname(HERE)
SPEC = os.path.join(SPEC_DIR, "JOB_B2_VACUUM_PRESSURE_SPEC.md")
B0_DIR = os.path.join(SPEC_DIR, "B0_taubes_base")
B0_RES = os.path.join(B0_DIR, "RESULTS.md")
T0 = time.time()
OUT = []


def out(s=""):
    print(s, flush=True)
    OUT.append(s)


# ---------------- parameters and thresholds (fixed before the graded run) ----------------
SPEC_HASH = "3A069F08"                    # posted SHA-256 prefix of the spec
B0_RES_HASH = "AE4E8FFB"                  # SHA-256 prefix of B0 RESULTS.md (as reported and as the job brief says)
N_LIST = [1, 2, 3]                        # spec: N = 1, 2, 3 from B0
EPS_LADDER = [0.01, 0.02, 0.05, 0.1, 1.0, 4.0]   # B0's area ladder (eps = A/A_B - 1)
T_LIST = [0.01, 0.1, 1.0]                 # spec
HBAR_LIST = [0.1, 1.0]                    # spec
K_MAX = 200000                            # spectrum sum cut-off (tail weight printed) [assumed]
K_MAX_LARGE_N = 3000000                   # cut-off for the N = 1e5 trend check [assumed]
TAIL_TOL = -40.0                          # require log(weight at K_MAX / max weight) < -40 [assumed]
Z_FIT = list(np.geomspace(1e-4, 1e-2, 9)) # small-z grid for the slope fit (quadratic fit of (1 - P~)/z in z) [assumed]
A2_TOL = 1e-3                             # A2: relative error of fitted c vs (N+1)/(6N) [assumed]
N_TREND = [1, 2, 3, 10, 100, 1000]        # A2 trend of c(N) toward MW's 1/6 (N = 1-3 graded, rest report)
N_MW = 10 ** 5                            # A3: MW's own illustrative N (their Figs. 4.1-4.5)
Z_MW = [0.25, 0.5, 1.0, 2.0, 8.0, 12.0, 16.0, 30.0, 35.0]   # A3 test points: high (<5), intermediate (5..2logN), low (>2logN+3)
# A3 criterion [assumed]: |P~_exact - P~_(36)| <= |last retained term of (36)| + (3 + z)/N * |leading term| + z/(4N)
# (the second piece bounds the O(1/N) terms that MW drop, e.g. g_1 = N(N+2) and exp(-z k^2/N); the third is MW's own
# finite-N crossover term in eq. (34), P~ = z e^(-z/2) - z/(4N). Added during box scratch development after z = 16 failed without it - disclosed in README).
VALID = 1.0                               # a validity column "crosses 1" when it reaches >= 1


def crc_sha(path):
    b = open(path, "rb").read()
    return "%08X" % (zlib.crc32(b) & 0xFFFFFFFF), hashlib.sha256(b).hexdigest()[:8].upper()


def audit_list():
    fs = [os.path.join(SPEC_DIR, f) for f in sorted(os.listdir(SPEC_DIR)) if os.path.isfile(os.path.join(SPEC_DIR, f))]
    fs += [os.path.join(B0_DIR, f) for f in sorted(os.listdir(B0_DIR)) if os.path.isfile(os.path.join(B0_DIR, f))]
    return fs


AUD = audit_list()
before = {f: crc_sha(f) for f in AUD}

out("# Job B2: vortex-gas pressure at the Bradlow cap (folder 02, vacuum) - RESULTS (generated by run.py; do not edit by hand)")
out("")
out(f"Generated {time.strftime('%Y-%m-%d %H:%M:%S')} (local time, BST = UTC+01:00). Python {platform.python_version()}, "
    f"numpy {np.__version__}, scipy {scipy.__version__}, sympy {sp.__version__}.")
crc, sha = before[SPEC]
out(f"Spec: JOB_B2_VACUUM_PRESSURE_SPEC.md, CRC32 {crc}, SHA-256 prefix {sha} (posted {SPEC_HASH}: match {sha == SPEC_HASH}).")
crc0, sha0 = before[B0_RES]
out(f"B0 input: B0_taubes_base/RESULTS.md, CRC32 {crc0}, SHA-256 prefix {sha0} (expected {B0_RES_HASH}: match {sha0 == B0_RES_HASH}).")
if sha != SPEC_HASH or sha0 != B0_RES_HASH:
    out("**STOP: hash mismatch - nothing computed.**")
    open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8", newline="\n").write("\n".join(OUT) + "\n")
    raise SystemExit(1)
out("")
out("Convention (spec, one throughout): H = (1/2) hbar^2 Laplacian on the moduli space (MW eq. (4), M22 eq. (6)); dissolving-limit metric "
    "g = (A - 4 pi N) G_FS on CP^N (MW eq. (2)); e = v = 1; eps = A/A_B - 1, A_B = 4 pi N.")
out("")
out(f"Fixed before the graded run: A2 = fitted small-z slope c within {A2_TOL:g} (relative) of (N+1)/(6N) for N = {N_LIST}; "
    "A3 = exact MW sum at N = 1e5 agrees with MW eq. (36) in each regime to within |last retained term| + (3+z)/N |leading term| + z/(4N) (MW eq. (34)); "
    f"A1 = sympy residuals exactly 0; spectrum tail weight below e^({TAIL_TOL:g}); validity columns cross at {VALID:g}. "
    "Grade (spec): PASS if Stage A reproduces and B0 P1 passed; PARTIAL if B0 P1 was PARTIAL; FAIL if Stage A fails.")
out("")

# ======================= Stage A1: sympy =======================
A, Nn, T, hb, z, k = sp.symbols("A N T hbar z k", positive=True)
out("## Stage A1 - sympy reproductions [identity]")
out("")
Vol = (A - 4 * sp.pi * Nn) ** Nn / sp.factorial(Nn)                 # MN (3.23), sphere
Zc = Vol * (2 * sp.pi ** 2 * T / sp.Symbol("h", positive=True) ** 2) ** Nn   # MN (4.3), g = 0 (R = 1)
Fc = -T * sp.log(Zc)
Pc = sp.simplify(-sp.diff(Fc, A))
r1 = sp.simplify(Pc - Nn * T / (A - 4 * sp.pi * Nn))
out(f"- MN (3.23) Vol_N = (A - 4 pi N)^N / N!  ->  P = -dF/dA = {sp.sstr(Pc)}; residual vs MN (4.7) NT/(A - 4 pi N): {r1} "
    "(exact for every N on the sphere, since Z is proportional to (A - 4 pi N)^N; the pi^N / h^(2N) prefactor cancels).")
# M22 (16)-(20): reproduce its algebra with its printed coefficient (the misprint)
Z22 = (T / (2 * hb ** 2)) ** Nn / sp.factorial(Nn) * (A - 4 * sp.pi * Nn) ** Nn * (1 + hb ** 2 * Nn ** 2 / (6 * T * (A - 4 * sp.pi * Nn)))
F22 = -T * (Nn * sp.log(T / (2 * hb ** 2)) - sp.log(sp.factorial(Nn)) + Nn * sp.log(A - 4 * sp.pi * Nn) + hb ** 2 * Nn ** 2 / (6 * T * (A - 4 * sp.pi * Nn)))  # log(1+x) ~ x, as M22
P22 = sp.simplify(-sp.diff(F22, A))
r2 = sp.simplify(P22 - (Nn * T / (A - 4 * sp.pi * Nn) - hb ** 2 * Nn ** 2 / (6 * (A - 4 * sp.pi * Nn) ** 2)))
Pv = sp.Symbol("P")
eos = sp.simplify(((P22 + hb ** 2 * Nn ** 2 / (6 * (A - 4 * sp.pi * Nn) ** 2)) * (A - 4 * sp.pi * Nn)) - Nn * T)
zdef = hb ** 2 / (2 * sp.pi * T) * 4 * sp.pi * Nn / (A - 4 * sp.pi * Nn)                     # MW (7)
c22 = sp.simplify((hb ** 2 * Nn ** 2 / (6 * (A - 4 * sp.pi * Nn) ** 2)) / (Nn * T / (A - 4 * sp.pi * Nn)) / zdef)
out(f"- M22 eqs. (16)->(19)->(20), algebra reproduced with M22's printed coefficient: residual of (19) {r2}, of (20) {eos}. "
    f"In MW's variable z this is P = NT/(A - 4 pi N)(1 - c22 z) with c22 = {c22}. **Misprinted, for reference (MW fn. 1); not a cross-check.**")
# corrected coefficient from the FS heat kernel: Z = (4 pi t)^(-N) [Vol + (t/6) Int R + ...], t = hbar^2/(2T)
tt = hb ** 2 / (2 * T)
Rs = 4 * Nn * (Nn + 1) / (A - 4 * sp.pi * Nn)          # scalar curvature of (A - 4 pi N) G_FS (G_FS holomorphic sectional curvature 4, Delta eigenvalues 4k(N+k))
a_coef = sp.simplify(tt * Rs / 6 / zdef)
c_exact = sp.simplify(a_coef / Nn)
out(f"- Heat-kernel first correction: Z = Z_class (1 + (t/6) R + ...), t = hbar^2/(2T), R = 4N(N+1)/(A - 4 pi N) (scaled FS) gives (t R/6)/z = {a_coef}, "
    f"so P = NT/(A - 4 pi N)(1 - c z), c = {c_exact} [computed, Venus; matches the spec's (N+1)/(6N)].")
r3 = sp.simplify(c_exact - (Nn + 1) / (6 * Nn))
plain = sp.simplify(c_exact * zdef * Nn * T / (A - 4 * sp.pi * Nn) - 2 * c_exact * hb ** 2 * Nn ** 2 / (A - 4 * sp.pi * Nn) ** 2)
VolFS = sp.pi ** Nn * (A - 4 * sp.pi * Nn) ** Nn / sp.factorial(Nn)
curv22 = 2 * Nn ** 2 * sp.pi ** Nn / sp.factorial(Nn) * (A - 4 * sp.pi * Nn) ** (Nn - 1)
ratio_curv = sp.simplify(Rs * VolFS / curv22)
out(f"- Residual c - (N+1)/(6N): {r3}; plain units c z NT/(A - 4 pi N) - 2c hbar^2 N^2/(A - 4 pi N)^2: {plain} (spec L18).")
out(f"- Where the 2 sits (spec L19, our arithmetic): R Vol(scaled FS) / M22 eq. (15) at g = 0 = {ratio_curv} -> 2 as N -> infinity "
    f"(limit {sp.limit(ratio_curv, Nn, sp.oo)}).")
a1_ok = (r1 == 0) and (r2 == 0) and (eos == 0) and (r3 == 0) and (plain == 0)
out("")
out(f"**A1: {'PASS' if a1_ok else 'FAIL'}** [identity; sympy].")
out("")


# ======================= exact MW spectrum sum =======================
def mw_stats(N, zv, K=K_MAX):
    """Exact MW sum Z = sum_k g_k exp(-z k (1 + k/N)), k = 0, 1, ... (MW eqs. (5)-(6)).
    Returns log Z, the reduced pressure P~ = P/(NT/(A - 4 pi N)) = (z/N) <k(1 + k/N)> (as log), and the tail weight."""
    kk = np.arange(0, K + 1, dtype=float)
    lg = np.log(N) + np.log(N + 2 * kk) - 2 * np.log(N + kk) + 2 * (gammaln(N + kk + 1) - gammaln(N + 1) - gammaln(kk + 1))
    e = kk * (1 + kk / N)
    lw = lg - zv * e
    lZ = logsumexp(lw)
    with np.errstate(divide="ignore"):
        lE = logsumexp(lw[1:] + np.log(e[1:]))
    lPt = math.log(zv / N) + lE - lZ
    return lZ, lPt, float(lw[-1] - lw.max())


def fmt_log(lx):
    """format exp(lx) without underflow"""
    l10 = lx / math.log(10)
    ex = math.floor(l10)
    return f"{10 ** (l10 - ex):.4f}e{ex:+d}"


# ======================= Stage A2: small-z slope =======================
out("## Stage A2 - exact MW spectrum sum: small-z slope c vs (N+1)/(6N) [computed]")
out("")
out("Reduced pressure P~ = P/(NT/(A - 4 pi N)) = (z/N)<k(1 + k/N)>, from P = T d(log Z)/dA with dz/dA = -z/(A - 4 pi N). "
    f"Fit: quadratic in z of (1 - P~)/z over z = {Z_FIT[0]:g} ... {Z_FIT[-1]:g} ({len(Z_FIT)} log-spaced points); c = intercept.")
out("")
out("| N | fitted c | (N+1)/(6N) | rel. err | graded | next coefficient (fit; MW large-N: 1/180 = 0.005556) | max tail log-weight |")
out("|---:|---:|---:|---:|---|---:|---:|")
a2_ok = True
tail_ok = True
cfit = {}
for N in N_TREND:
    ys, tails = [], []
    for zv in Z_FIT:
        _, lPt, tail = mw_stats(N, zv, K=max(K_MAX, 200 * N))
        ys.append((1 - math.exp(lPt)) / zv)
        tails.append(tail)
    p = np.polyfit(Z_FIT, ys, 2)
    c_f = p[-1]
    c_e = (N + 1) / (6 * N)
    rel = abs(c_f - c_e) / c_e
    graded = N in N_LIST
    if graded:
        a2_ok &= rel < A2_TOL
    tail_ok &= max(tails) < TAIL_TOL
    cfit[N] = c_f
    out(f"| {N} | {c_f:.10f} | {c_e:.10f} | {rel:.1e} | {graded} | {-p[-2]:.6f} | {max(tails):.1f} |")
out("")
out(f"Large-N trend: 6c(N) = " + ", ".join(f"{6 * cfit[N]:.6f} (N = {N})" for N in N_TREND) + " -> 1, i.e. c -> 1/6 = MW eqs. (25), (36) [computed].")
out(f"For reference only (misprinted, MW fn. 1): M22's coefficient 1/12 = {1 / 12:.6f}.")
out("")
out(f"**A2: {'PASS' if a2_ok else 'FAIL'}** (N = {N_LIST}, tolerance {A2_TOL:g}).")
out("")

# ======================= Stage A3: MW (36) at large N =======================
out(f"## Stage A3 - exact sum at N = {N_MW:g} vs MW eq. (36) [computed]")
out("")
L2 = 2 * math.log(N_MW)
out(f"2 log N = {L2:.4f}. Regimes of (36): high 0 < z < 5; intermediate 5 < z < 2 log N; low z > 2 log N (crossover 2 log N +- 3, MW Sec. 4; low-regime test points are beyond it).")
out("")
out("| z | regime | P~ exact | P~ MW (36) | |difference| | allowed: |last term| + (3+z)/N |leading| + z/(4N) | ok |")
out("|---:|---|---:|---:|---:|---:|---|")
a3_ok = True
for zv in Z_MW:
    _, lPt, tail = mw_stats(N_MW, zv, K=K_MAX_LARGE_N)
    tail_ok &= tail < TAIL_TOL
    pe = math.exp(lPt)
    if zv < 5:
        reg, lead, last = "high", 1.0, zv ** 2 / 180
        p36 = 1 - zv / 6 + zv ** 2 / 180
    elif zv < L2:
        reg, lead, last = "intermediate", zv * math.exp(-zv / 2), zv * (2 - zv) * math.exp(-zv)
        p36 = lead + last
    else:
        reg, lead, last = "low", N_MW * zv * math.exp(-zv), -N_MW ** 3 * zv * math.exp(-2 * zv)
        p36 = lead + last
    allow = abs(last) + (3 + zv) / N_MW * abs(lead) + zv / (4 * N_MW)
    ok = abs(pe - p36) <= allow
    a3_ok &= ok
    out(f"| {zv:g} | {reg} | {pe:.10e} | {p36:.10e} | {abs(pe - p36):.2e} | {allow:.2e} | {ok} |")
out("")
out(f"**A3: {'PASS' if a3_ok else 'FAIL'}**. Spectrum tails all below e^({TAIL_TOL:g}): {tail_ok}.")
out("")
stageA = a1_ok and a2_ok and a3_ok and tail_ok
out(f"**Stage A: {'PASS' if stageA else 'FAIL'}**")
out("")

# ======================= B0 input =======================
txt = open(B0_RES, encoding="utf-8").read()
sec = txt.split("## P1 (Venus's argument)")[1].split("\n\n")[1]
gap2 = {}
for line in sec.splitlines():
    m = re.match(r"\|\s*(\d+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|", line)
    if m:
        gap2[(int(m.group(1)), float(m.group(2)))] = float(m.group(4))
b0_grade = re.search(r"\*\*Grade by the fixed rule: (\w+)\*\*", txt).group(1)
b0_p1 = re.search(r"\*\*P1: (\w+)\*\*", txt).group(1)
missing = [(N, e) for N in N_LIST for e in EPS_LADDER if (N, e) not in gap2]
out("## Input from B0 (read from B0_taubes_base/RESULTS.md, P1 table; B0 not recomputed, not modified)")
out("")
out(f"B0 grade: {b0_grade}; B0 P1: {b0_p1}; gaps read: {len(gap2)} (missing: {missing}). gap^2 is B0's measured lowest non-zero omega^2 in sector k = 0 "
    "(all N vortices at one pole), printed there to 8 decimals.")
out("")

# ======================= Stage B =======================
out("## Stage B - near-cap rows on B0's area ladder")
out("")
out("Columns: P_class = NT/(A - 4 pi N) [standard, MN (4.7)]; P_MW = exact MW sum [computed; uses the dissolving-limit metric, so it is MW's model only for eps << 1, extrapolated at eps = 1, 4 - assumed]; "
    "z (MW eq. (7)); m_gap^2 = B0 measured [computed, B0], beside Venus's e^2 v^2 (A - A_B)/A_B = eps [leading order, reference]; "
    "Delta E = (A - A_B)^2/(8A) [identity, B0 P3]; m_gap^2 (A - A_B)/(8 Delta E) (Venus: = 1 when m_gap^2 = (A - A_B)/A; printed with the B0 gap); "
    "classical validity T/Delta E; quantum validity hbar m_gap/Delta E (B0 measured gap; leading-order reference beside it); T/(hbar m_gap) [report only: > 1 classical gas applies, < 1 quantum]; "
    "moduli step hbar^2 lambda_1/2 = 2 hbar^2 (N+1)/(A - 4 pi N) divided by hbar m_gap (> 1: truncation to the moduli inconsistent; relevant for the quantum gas only).")
out("")
out("| N | T | hbar | eps | A | P_class | P_MW | z | m_gap^2 (B0) | eps (leading order, reference) | m_gap^2 (A-A_B)/(8 Delta E) | Delta E | T/Delta E | hbar m_gap/Delta E | hbar m_gap/Delta E (leading order, reference) | T/(hbar m_gap) | step/(hbar m_gap) |")
out("|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
rows = {}
for N in N_LIST:
    AB = 4 * math.pi * N
    for T_ in T_LIST:
        for h_ in HBAR_LIST:
            for eps in EPS_LADDER:
                Aa = AB * (1 + eps)
                x = Aa - AB
                Pcl = N * T_ / x
                zv = h_ ** 2 / (2 * math.pi * T_) * AB / x
                _, lPt, tail = mw_stats(N, zv)
                tail_ok_B = tail < TAIL_TOL
                lPmw = math.log(Pcl) + lPt
                g2 = gap2[(N, eps)]
                mg = math.sqrt(g2)
                dE = x ** 2 / (8 * Aa)
                cl = T_ / dE
                qu = h_ * mg / dE
                qu_lo = h_ * math.sqrt(eps) / dE
                th = T_ / (h_ * mg)
                step = 2 * h_ ** 2 * (N + 1) / x
                st = step / (h_ * mg)
                rows[(N, T_, h_, eps)] = dict(Pcl=Pcl, lPmw=lPmw, cl=cl, qu=qu, th=th, st=st, tail=tail_ok_B, z=zv)
                out(f"| {N} | {T_:g} | {h_:g} | {eps:g} | {Aa:.4f} | {Pcl:.6e} | {fmt_log(lPmw)} | {zv:.4e} | {g2:.8f} | {eps:g} | {g2 * x / (8 * dE):.6f} | "
                    f"{dE:.6e} | {cl:.4e} | {qu:.4e} | {qu_lo:.4e} | {th:.4e} | {st:.4e} |")
                tail_ok &= tail_ok_B
out("")
out(f"Spectrum tails below e^({TAIL_TOL:g}) in every Stage B row: {all(r['tail'] for r in rows.values())}.")
out("")

# ---------------- epsilon* ----------------
out("## epsilon*(T): where the gas description ends [computed]")
out("")
out("Read off the ladder, scanning from the far area (eps = 4) toward the cap: eps* = the first ladder area at which the governing column is >= 1. "
    "Governing column per row (spec: T/(hbar m_gap) says which applies): T/Delta E where T >= hbar m_gap (classical gas), hbar m_gap/Delta E where T < hbar m_gap (quantum gas). "
    "'>= 4' means already broken at the largest ladder area. For each scale separately, eps*_scale = first ladder area where that column is >= 1 (moduli step: step/(hbar m_gap) >= 1); "
    "the scale with the largest eps* breaks first. P(eps*) is printed for the governing gas (P_class if classical, P_MW if quantum), with the other beside it.")
out("")
out("| N | T | hbar | eps* (governing) | governing gas at eps* | eps* classical T/Delta E | eps* quantum hbar m_gap/Delta E | eps* moduli step | breaks first | P(eps*) governing | P_class(eps*) | P_MW(eps*) |")
out("|---:|---:|---:|---|---|---|---|---|---|---:|---:|---:|")
ladder_desc = sorted(EPS_LADDER, reverse=True)
mono_ok = True


def first_cross(key, N, T_, h_):
    vals = [rows[(N, T_, h_, e)][key] for e in ladder_desc]
    for e, v in zip(ladder_desc, vals):
        if v >= VALID:
            return e
    return None


def interp_cross(key, N, T_, h_):
    """log-log linear interpolation of a validity column between the bracketing ladder areas [assumed]"""
    es = sorted(EPS_LADDER)
    vs = [rows[(N, T_, h_, e)][key] for e in es]
    if vs[-1] >= VALID:
        return None, ">= 4"
    if vs[0] < VALID:
        return None, "< 0.01"
    for i in range(len(es) - 1):
        if vs[i] >= VALID > vs[i + 1]:
            l0, l1 = math.log(es[i]), math.log(es[i + 1])
            v0, v1 = math.log(vs[i]), math.log(vs[i + 1])
            le = l0 + (0.0 - v0) * (l1 - l0) / (v1 - v0)
            return math.exp(le), f"{math.exp(le):.4f}"
    return None, "?"


def lab(e):
    if e is None:
        return "none on ladder (valid down to 0.01)"
    return ">= 4" if e == ladder_desc[0] else f"{e:g}"


EST = {}
INT = {}
for N in N_LIST:
    for T_ in T_LIST:
        for h_ in HBAR_LIST:
            gov = []
            for e in ladder_desc:
                r = rows[(N, T_, h_, e)]
                gov.append((e, r["cl"] if r["th"] >= 1 else r["qu"], "classical" if r["th"] >= 1 else "quantum"))
            eg, gname = None, "-"
            for e, v, nm in gov:
                if v >= VALID:
                    eg, gname = e, nm
                    break
            ec = first_cross("cl", N, T_, h_)
            eq = first_cross("qu", N, T_, h_)
            es = first_cross("st", N, T_, h_)
            for key in ("cl", "qu", "st"):
                seq = [rows[(N, T_, h_, e)][key] for e in ladder_desc]
                mono_ok &= all(seq[i] <= seq[i + 1] for i in range(len(seq) - 1))
            ic = interp_cross("cl", N, T_, h_)
            iq = interp_cross("qu", N, T_, h_)
            ist = interp_cross("st", N, T_, h_)
            ivals = {"classical melting": ic, "quantum gap": iq, "moduli step": ist}
            num = {kk: (vv[0] if vv[0] is not None else (99.0 if vv[1] == ">= 4" else -1.0)) for kk, vv in ivals.items()}
            ifirst = max(num, key=num.get)
            INT[(N, T_, h_)] = (ic[1], iq[1], ist[1], ifirst)
            cand = {"classical melting (T/Delta E)": ec, "quantum gap (hbar m_gap/Delta E)": eq, "moduli step": es}
            score = {kk: (vv if vv is not None else -1) for kk, vv in cand.items()}
            best = max(score.values())
            first = " = ".join(kk for kk, vv in score.items() if vv == best) if best > 0 else "none on ladder"
            if eg is not None:
                r = rows[(N, T_, h_, eg)]
                pg = f"{r['Pcl']:.6e}" if gname == "classical" else fmt_log(r["lPmw"])
                pc, pm = f"{r['Pcl']:.6e}", fmt_log(r["lPmw"])
            else:
                pg = pc = pm = "-"
            EST[(N, T_, h_)] = (eg, gname, ec, eq, es, first)
            out(f"| {N} | {T_:g} | {h_:g} | {lab(eg)} | {gname} | {lab(ec)} | {lab(eq)} | {lab(es)} | {first} | {pg} | {pc} | {pm} |")
out("")
out(f"All three validity columns rise monotonically toward the cap along the ladder (so 'first crossing' is unambiguous): {mono_ok}.")
out("")
out("Off-ladder crossing estimates [assumed: log-log linear interpolation of each column between the two bracketing ladder areas; "
    "the classical column is also solved exactly below]. 'breaks first' = the scale with the largest interpolated eps* (the ladder above is too coarse to separate them in many rows).")
out("")
out("| N | T | hbar | eps* classical (interp.) | eps* quantum gap (interp.) | eps* moduli step (interp.) | breaks first (interp.) |")
out("|---:|---:|---:|---:|---:|---:|---|")
for N in N_LIST:
    for T_ in T_LIST:
        for h_ in HBAR_LIST:
            a_, b_, c_, f_ = INT[(N, T_, h_)]
            out(f"| {N} | {T_:g} | {h_:g} | {a_} | {b_} | {c_} | {f_} |")
out("")

# ---------------- continuous classical eps* and the leading estimate ----------------
out("## Classical melting point off the ladder, and the leading estimate (Stage C, report only)")
out("")
out("T/Delta E = 1 solved exactly: (A - A_B)^2 = 8 T A  =>  A - A_B = 4T + sqrt(16 T^2 + 8 T A_B) [identity]. "
    "Leading estimate (spec, Venus): A - A_B ~ sqrt(8 T A), P(eps*) ~ N sqrt(T/(8A)) [standard at classical leading order]. With A = A* this is exact (x^2 = 8TA*); "
    "the leading-order version evaluates A at A_B.")
out("")
out("| N | T | eps* exact | A* | P_class(eps*) exact = NT/(A* - A_B) = N sqrt(T/(8A*)) | leading: eps from sqrt(8 T A_B) | leading P = N sqrt(T/(8 A_B)) | exact/leading P |")
out("|---:|---:|---:|---:|---:|---:|---:|---:|")
for N in N_LIST:
    AB = 4 * math.pi * N
    for T_ in T_LIST:
        xs = 4 * T_ + math.sqrt(16 * T_ ** 2 + 8 * T_ * AB)
        As = AB + xs
        P1_ = N * T_ / xs
        xl = math.sqrt(8 * T_ * AB)
        P2_ = N * math.sqrt(T_ / (8 * AB))
        out(f"| {N} | {T_:g} | {xs / AB:.6f} | {As:.6f} | {P1_:.6e} | {xl / AB:.6f} | {P2_:.6e} | {P1_ / P2_:.6f} |")
out("")
Avar = sp.Symbol("A", positive=True)
xsym = 4 * T + sp.sqrt(16 * T ** 2 + 8 * T * 4 * sp.pi * Nn)
r4 = sp.simplify(xsym ** 2 - 8 * T * (4 * sp.pi * Nn + xsym))
out(f"sympy: residual of (A* - A_B)^2 - 8 T A* at the root: {r4} [identity]. P_class(eps*) = N sqrt(T/(8A*)) exactly, since NT/x = N T/sqrt(8TA*) when x^2 = 8TA*.")
out("")
Ftor = -T * (sp.log(A) + (Nn - 1) * sp.log(A - 4 * sp.pi * Nn))
r5 = sp.simplify(-sp.diff(Ftor, A) - ((Nn - 1) * T / (A - 4 * sp.pi * Nn) + T / A))
out("Torus (report only): MN eq. (3.24) gives Vol = A (A - 4 pi N)^(N-1)/N!, so P = (N-1)T/(A - 4 pi N) + T/A [standard: MN (3.24); Shah-Manton JMP 35 (1994) 1171 not read]; "
    f"sympy residual {r5}. On the torus the classical pressure also diverges at A = 4 pi N (for N >= 2).")
out("")

# ---------------- grade ----------------
if not stageA:
    grade = "FAIL"
elif b0_p1 == "PASS" and b0_grade == "PASS":
    grade = "PASS"
else:
    grade = "PARTIAL"
out("## Summary")
out("")
out(f"- Stage A: A1 {'PASS' if a1_ok else 'FAIL'}, A2 {'PASS' if a2_ok else 'FAIL'} (c = (N+1)/(6N) reproduced: "
    + ", ".join(f"N = {N}: {cfit[N]:.8f}" for N in N_LIST) + f"), A3 {'PASS' if a3_ok else 'FAIL'}; tails ok {tail_ok}.")
out(f"- B0 P1: {b0_p1} (B0 grade {b0_grade}); measured B0 gaps used in all gap columns.")
out(f"- **Grade by the fixed rule: {grade}**" + (" - PASS by construction (reproduction + scale ordering)." if grade == "PASS" else ".")
    + " A PASS reproduces known results; it is not evidence for Akitti's link.")
after = {f: crc_sha(f) for f in AUD}
out(f"- Spec folder files and B0 files unchanged by the run (CRC32 and SHA-256 before = after, {len(AUD)} files): {before == after}.")
out(f"- Runtime: {time.time() - T0:.0f} s [computed].")
with open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(OUT) + "\n")
