"""Betti-Berry vacuum filter toy. Writes RESULTS.md (never hand-edit) and betti_vs_p.png.

Rules and every assumed input are fixed in README.md, written before this run.
This is not a solution to vacuum selection; the selection depends on the assumed inputs.
"""
import argparse
import datetime
import hashlib
import json
import math
import os
import sys

import numpy as np

import goldberg as GB
import percolation as PC
import potential as PT

HERE = os.path.dirname(os.path.abspath(__file__))
FOREIGN = ["X_NOTES.md", "X_POSTS_verbatim.md", "X_WINDOW_DEFS.md"]

# ---- assumed inputs (copied from README.md) ----
EPS_V = 1.0
F = 1.0
LAMBDA0 = 100.0
BETAS = [0.0, 0.5, 1.0]
GS = [1.0, 5.0, 9.0, 12.0, 20.0]
LO, HI = -20.0, 0.0
PHI0S = [0.0, -7.0, -14.0]
SIZES = [4, 8, 16]
M_RHO = 16
SEEDS = 300
MASTER_SEED = 20261002
WINDOW = (0.010, 0.030)
Q_B, C_B = 0.5, 1.0


def p_of_phi(phi, scale=20.0):
    """Occupancy map; scale=20 preserves the fixed default rule."""
    return float(min(1.0, max(0.0, -phi / scale)))


def sha(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def yn(b):
    return "YES" if b else "NO"


def surviving_vacua(vacua, rho_window=WINDOW, spectrum_filter=None):
    """Return vacua inside rho_window, preserving field content/spectrum for Job Two.

    Each input is a mapping with at least rho_res; field_content and spectrum are
    carried through untouched. spectrum_filter, when supplied, receives
    (field_content, spectrum, vacuum) and must return True to keep the vacuum.
    """
    lo, hi = rho_window
    out = []
    for vacuum in vacua:
        rho = vacuum.get("rho_res")
        if rho is None or not (lo <= float(rho) <= hi):
            continue
        if spectrum_filter is not None and not spectrum_filter(
                vacuum.get("field_content"), vacuum.get("spectrum"), vacuum):
            continue
        out.append(vacuum)
    return out


def format_vacua(vacua):
    return "[" + "; ".join(v.get("id", "<unnamed>") for v in vacua) + "]"


def job_two_assumed_map(flux_n, radius_R):
    """[assumed input] alt-model map from (flux n, radius R) to occupancy p.

    The explicit toy choice is p = clip((|n|/3) * (1/R)^2, 0, 1); b1 is then
    obtained from the m=16 percolation observable at that p in main().
    """
    return float(min(1.0, max(0.0, (abs(float(flux_n)) / 3.0) * (1.0 / float(radius_R)) ** 2)))


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description="Betti-Berry vacuum filter")
    parser.add_argument("--vacua-json", help="JSON list for the surviving_vacua hook")
    parser.add_argument("--rho-lo", type=float, default=None, help="hook lower rho bound")
    parser.add_argument("--rho-hi", type=float, default=None, help="hook upper rho bound")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    L = []
    w = L.append
    now = datetime.datetime.now().astimezone()
    z = now.strftime("%z")
    import scipy
    w("# RESULTS (generated by run.py - do not edit by hand)")
    w("")
    w("**Signed off 2026-10-02:** Venus (maths PASS) and Helios (physics, PARTIAL: calculations sound; filter selects nothing; stopping by construction).")
    w("")
    w("Generated: %s (local time, UTC%s:%s)" % (now.strftime("%Y-%m-%d %H:%M:%S"), z[:3], z[3:]))
    w("Python %s, numpy %s, scipy %s" % (sys.version.split()[0], np.__version__, scipy.__version__))
    w("")
    w("Toy model. **Not a solution to vacuum selection**: which vacua survive depends entirely on the "
      "assumed inputs in README.md. No quantum-gravity claim.")
    w("")
    before = {f: sha(os.path.join(HERE, f)) for f in FOREIGN}
    w("Foreign input files, read only (SHA-256 before the run): " + "; ".join("%s %s" % (f, h[:16].upper()) for f, h in before.items()))
    w("")

    # ================= 1. Helios stopping condition FIRST =================
    w("## 1. Stopping condition (printed before any rho_res)")
    w("")
    w("Bound [standard]: g < 2 pi eps_V (1 + alpha beta) / f, with alpha = golden ratio = %.10f "
      "[from Akitti's post: irrational, golden ratio or similar]. The actual max uphill wiggle slope "
      "max(-dV_wiggle/dphi) and the local minima are found on [%g, %g] [computed]." % (PT.ALPHA, LO, HI))
    w("")
    w("| beta | g | bound 2 pi eps_V (1+alpha beta)/f | bound PASS/FAIL | actual max uphill slope in range | g below actual max | local minima in range | verdict |")
    w("|---|---|---|---|---|---|---|---|")
    sets = []
    for beta in BETAS:
        for g in GS:
            V = PT.Potential(g, beta, EPS_V, F, LAMBDA0)
            bnd = V.bound()
            mx, _ = V.max_uphill_slope(LO, HI)
            mins = V.minima(LO, HI)
            ok = g < bnd
            if not ok:
                verdict = "field never settles; Betti filter has nothing to act on"
            elif not mins:
                verdict = "bound passes but no local minimum in range; rho_res skipped"
            else:
                verdict = "field can settle; go on"
            w("| %g | %g | %.4f | %s | %.4f | %s | %d | %s |" % (beta, g, bnd, "PASS" if ok else "FAIL", mx, yn(g < mx), len(mins), verdict))
            sets.append(dict(beta=beta, g=g, V=V, ok=ok and bool(mins), mins=mins, bound=bnd, mx=mx))
    w("")
    w("The bound is an upper limit. In a finite range the two wiggles never quite line up, so the actual max "
      "sits a little below it [computed].")
    w("")

    # ================= 2. Rolling =================
    w("## 2. Rolling: overdamped gradient flow dphi/dt = -V'(phi), RK4 [assumed dynamics]")
    w("")
    w("| beta | g | phi_0 | phi_stop (flow) | phi_stop (grid cross-check) | difference | V(phi_stop) / E_* | p(phi_stop) |")
    w("|---|---|---|---|---|---|---|---|")
    reached = []
    for s in sets:
        if not s["ok"]:
            continue
        V = s["V"]
        s["stops"] = []
        for x0 in PHI0S:
            xf, t, steps = V.roll(x0, LO, HI)
            xg = V.first_stop_grid(x0, LO, HI)
            if xf is None:
                w("| %g | %g | %g | leaves range | %s | - | - | - |" % (s["beta"], s["g"], x0, "none" if xg is None else "%.6f" % xg))
                continue
            w("| %g | %g | %g | %.8f | %.8f | %.1e | %.4f | %.4f |" % (s["beta"], s["g"], x0, xf, xg, abs(xf - xg), V.V(xf), p_of_phi(xf)))
            s["stops"].append((x0, xf))
            reached.append((s, x0, xf))
    w("")
    w("p(phi) = clip(-phi/20, 0, 1) [assumed input]. V(phi_stop) still contains Lambda_0 = %g E_*. The post "
      "says ordinary cancellation removes the bulk; that cancellation is not modelled, and rho_res below is "
      "the post's residual only [from Akitti's post]." % LAMBDA0)
    w("Stopping [by construction, no backreaction]: overdamped flow from rest ends at the nearest downhill minimum (phi_stop is about phi0 - 0.5). In the real relaxion the barrier height is set by the Higgs vev, so barriers switch on only once the Higgs turns on, and that is the selection step (Graham-Kaplan-Rajendran 2015, arXiv:1504.07551) [standard]. This toy has fixed barriers.")
    w("")

    # ================= 3. Goldberg + percolation =================
    w("## 3. GoldbergHexa sphere and face-site percolation")
    w("")
    w("No existing GoldbergHexa implementation was found under C:\\Users\\Akitt (read-only search: text "
      "mentions only). `goldberg.py` builds GP(m,0) as the dual of the class-I geodesic icosahedron.")
    w("")
    w("| m | faces N | 10m^2+2 | pentagons | hexagons | other | face-adjacency edges (30m^2) | Goldberg vertices (20m^2) | Euler V-E+F |")
    w("|---|---|---|---|---|---|---|---|---|")
    graphs = {}
    for m in SIZES:
        G = GB.goldberg(m)
        graphs[m] = G
        c = GB.check(G)
        w("| %d | %d | %d | %d | %d | %d | %d (%d) | %d (%d) | %d |" % (
            m, c["faces N"], c["expected 10m^2+2"], c["pentagons (degree 5)"], c["hexagons (degree 6)"], c["other degrees"],
            c["face-adjacency edges"], c["expected 30m^2"], c["Goldberg vertices (= triangles)"], c["expected 20m^2"],
            c["Euler V-E+F of Goldberg polyhedron"]))
    w("")
    w("Face-site percolation on a hex tiling is site percolation on the triangular lattice, so p_c = 1/2 exactly "
      "in the infinite lattice [computed from lattice choice; standard]. b_1 is that of the 2D complex (the union "
      "of closed occupied faces), computed by Alexander duality and checked against the Euler characteristic "
      "of the induced sub-triangulation. The dual-graph count E - V + components is shown for contrast only; "
      "it counts every filled triangle as a cycle.")
    w("b_1 behavior [identity: Alexander duality + self-matching]: on S^2, b_1(X) = b_0(S^2 \\ X) - 1, and the GP(m,0) face graph is a self-matching triangulation, so <b_1>(p) = <b_0>(1-p) - 1 and <chi>(1/2) = 1 (up to 2^-N). Thus b_1 rises then falls, peaks near 0.8, crosses the window twice, and does not sharpen with size; the cluster count per face is smooth at p_c and its singular part is |p-p_c|^{8/3} in 2D [standard]. The pre-registered b_1 expectation failed because b_1 was the wrong observable, not because of a bug. Only the largest-cluster share (or wrapping cycles on a torus, which a sphere does not have) jumps at p_c.")
    w("")
    ps = np.round(np.linspace(0, 1, 101), 10)
    rng = np.random.default_rng(MASTER_SEED)
    curves = {}
    jump_rows = []
    for m in SIZES:
        G = graphs[m]
        res, mism = PC.sweep(G, ps, SEEDS, rng)
        N = G["N"]
        mean = {k: v.mean(axis=1) for k, v in res.items()}
        chi_exact = N * ps - (3 * N - 6) * ps ** 2 + (2 * N - 4) * ps ** 3
        curves[m] = (mean, N)
        w("### m = %d (N = %d faces), %d seeds per p, coupled sweep" % (m, N, SEEDS))
        w("")
        w("- b_1 by Alexander duality vs by Euler characteristic: %d disagreements in %d patterns [computed]." % (mism, SEEDS * len(ps)))
        i5 = int(np.argmin(abs(ps - 0.5)))
        w("- Mean Euler characteristic at p = 1/2: %.3f (exact expectation [identity]: %.3f); largest |MC - exact| over all p: %.2f "
          "(seed noise) [computed]." % (mean["chi"][i5], chi_exact[i5], float(np.max(abs(mean["chi"] - chi_exact)))))
        w("")
        w("| p | b_0 per face | b_1 per face (complex) | dual-graph cycles per face (contrast) | largest-cluster share | b_1 of largest cluster per face | share of all b_1 on the largest cluster [post-hoc] |")
        w("|---|---|---|---|---|---|---|")
        share = np.where(mean["b1"] > 0, mean["b1_C"] / np.maximum(mean["b1"], 1e-300), np.nan)
        for pv in (0.1, 0.2, 0.3, 0.4, 0.45, 0.5, 0.55, 0.6, 0.7, 0.8, 0.9):
            i = int(np.argmin(abs(ps - pv)))
            w("| %.2f | %.4f | %.4f | %.4f | %.4f | %.4f | %s |" % (
                ps[i], mean["b0"][i] / N, mean["b1"][i] / N, mean["graph_cycles"][i] / N, mean["frac_max"][i],
                mean["b1_C"][i] / N, "-" if np.isnan(share[i]) else "%.3f" % share[i]))
        w("")
        # jump estimators
        def steepest(y):
            d = np.gradient(y, ps)
            i = int(np.argmax(d))
            half = d[i] / 2
            lo_i = i
            while lo_i > 0 and d[lo_i - 1] >= half:
                lo_i -= 1
            hi_i = i
            while hi_i < len(ps) - 1 and d[hi_i + 1] >= half:
                hi_i += 1
            return ps[i], ps[hi_i] - ps[lo_i]
        pf, wf = steepest(mean["frac_max"])
        pb, wb = steepest(mean["b1_C"] / N)
        sh = np.nan_to_num(share, nan=0.0)
        below = np.flatnonzero(sh[:-1] < 0.5)      # last upward crossing of 1/2 (low-p values are noisy)
        if len(below):
            k = int(below[-1])
            p_half = ps[k] + (0.5 - sh[k]) * (ps[k + 1] - ps[k]) / (sh[k + 1] - sh[k])
        else:
            p_half = float("nan")
        jump_rows.append((m, N, pf, wf, pb, wb, p_half))
        curves[m] = (mean, N, share)
    w("### Duality check at m = 16 [identity, computed]")
    w("")
    w("| p | <b_0>(p) per face | <b_1>(1-p) per face | difference |")
    w("|---|---|---|---|")
    mean16, N16, _share16 = curves[16]
    for pv in (0.1, 0.2, 0.3):
        i = int(np.argmin(abs(ps - pv)))
        j = int(np.argmin(abs(ps - (1.0 - pv))))
        b0p = mean16["b0"][i] / N16
        b1comp = mean16["b1"][j] / N16
        w("| %.1f | %.4f | %.4f | %.4f |" % (pv, b0p, b1comp, b0p - b1comp))
    w("b_0(p) - b_1(1-p) = 1 per pattern exactly, which is 1/N ≈ 0.0004 per face at m=16, so the ~0.0005 gap is expected [identity], plus seed noise.")
    w("")
    w("Exact <chi>(1/2) = Np - Ep^2 + Tp^3 = (5m^2+1) - 7.5m^2 + 2.5m^2 = 1 [identity].")
    w("")
    w("### b_1 per face at p = 0.8 [computed]")
    w("")
    w("| m | faces N | b_1 per face |")
    w("|---|---|---|")
    for m in SIZES:
        mean_m, N_m, _ = curves[m]
        i = int(np.argmin(abs(ps - 0.8)))
        w("| %d | %d | %.4f |" % (m, N_m, mean_m["b1"][i] / N_m))
    w("b_1 is extensive [computed]. Therefore rho_res is about eps_V * b_1/N, of order 0.1 eps_V across the middle range. Topology gives no parametric suppression; a small residual needs p pushed to an edge, which is the same tuning in a new place [hive-interpretation].")
    w("")
    w("### Where the jump is, against size [computed; finite-size]")
    w("")
    w("| m | faces N | steepest rise of largest-cluster share: p (width) | steepest rise of b_1 of largest cluster: p (width) | share of b_1 on largest cluster reaches 1/2 at p |")
    w("|---|---|---|---|---|")
    for m, N, pf, wf, pb, wb, ph in jump_rows:
        w("| %d | %d | %.2f (%.2f) | %.2f (%.2f) | %.3f |" % (m, N, pf, wf, pb, wb, ph))
    w("")
    w("The last column is an extra diagnostic [post-hoc, not in the pre-fixed rules]: the last p where the share of all "
      "b_1 sitting on the largest cluster crosses 1/2 upward. It fails as a sharp diagnostic at GP(4,0). Below p_c "
      "that share is noisy because there are almost no cycles at all.")
    w("")
    w("Widths are the full width at half maximum of the slope (p grid step 0.01). The step is smeared on every "
      "finite Goldberg sphere with its 12 pentagons, and it sharpens and moves as N grows [finite-size]. "
      "Infinite-lattice p_c = 1/2 [standard].")
    w("")
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(1, 3, figsize=(13, 4))
        for m in SIZES:
            mean, N, share = curves[m]
            ax[0].plot(ps, mean["frac_max"], label="m=%d (N=%d)" % (m, N))
            ax[1].plot(ps, mean["b1_C"] / N, label="m=%d" % m)
            ax[2].plot(ps, share, label="m=%d" % m)
        for a, t in zip(ax, ["largest-cluster share", "b_1 of largest cluster per face", "share of all b_1 on largest cluster"]):
            a.axvline(0.5, color="gray", ls="--", lw=0.8)
            a.set_xlabel("occupancy p"); a.set_title(t); a.legend(fontsize=8)
        ax[1].axhspan(WINDOW[0], WINDOW[1], color="green", alpha=0.15)
        fig.tight_layout(); fig.savefig(os.path.join(HERE, "betti_vs_p.png"), dpi=120); plt.close(fig)
        w("Plot: betti_vs_p.png (dashed line p = 1/2; green band in the middle panel = assumed window, since "
          "rho_res is about b_1/N there).")
    except Exception as exc:
        w("Plot not made: %s" % exc)
    w("")

    # ================= 4. Berry term =================
    w("## 4. Berry monopole term [assumed input]")
    w("")
    w("rho_Berry = (eps_V / L^d) c_B sum over holes c of (1 - cos gamma_c), gamma_c = q_B Omega_c, Omega_c = 4 pi A_c / N, "
      "with q_B = %g, c_B = %g. The sum runs over holes; each hole uses its real size A_c counted in faces: γ_c = 2πA_c/N; "
      "the FACES are treated as equal-area. The (1 - cos gamma) form is [assumed input]. Not given in Akitti's posts." % (Q_B, C_B))
    w("Berry vacua use GP(16,0), N = 2562 [assumed input].")
    w("")
    berry_p = 0.7
    berry_rows = []
    berry_rng = np.random.default_rng(MASTER_SEED + 2)
    for m in SIZES:
        Gm = graphs[m]
        Nm = Gm["N"]
        vals = []
        for _ in range(SEEDS):
            occ = berry_rng.random(Nm) < berry_p
            vals.append(EPS_V / Nm * PC.analyse(Gm, occ, Q_B, C_B)["berry"])
        berry_rows.append((m, Nm, float(np.mean(vals))))
    berry_alpha = float(np.polyfit(np.log([r[1] for r in berry_rows]), np.log([r[2] for r in berry_rows]), 1)[0])
    w("Berry term at fixed p = %.1f [computed scaling]:" % berry_p)
    w("")
    w("| m | faces N | mean Berry contribution to rho_res |")
    w("|---|---|---|")
    for m, Nm, val in berry_rows:
        w("| %d | %d | %.3e |" % (m, Nm, val))
    berry_local_48 = float(np.log(berry_rows[1][2] / berry_rows[0][2]) / np.log(berry_rows[1][1] / berry_rows[0][1]))
    berry_local_816 = float(np.log(berry_rows[2][2] / berry_rows[1][2]) / np.log(berry_rows[2][1] / berry_rows[1][1]))
    w("Fitted N-scaling exponent for the Berry term: %.4f [computed scaling]; local slopes m=4→8: %.4f, m=8→16: %.4f. The gap from -2 is [finite-size]." % (berry_alpha, berry_local_48, berry_local_816))
    w("Small-angle limit: ρ_B ≈ (2π²ε_V/N³)·ΣA_c² → N⁻², because at p=0.7 (empty density 0.3 < 1/2) the holes stay finite. The local slopes steepen toward -2, and dropping the largest complement piece at small m (about 13 holes at m=4) flattens the fit.")
    w("The Berry term is 1e-5 to 1e-8 of rho_res and moves no vacuum [computed; still assumed input].")
    w("")

    # ================= 5. Candidate vacua =================
    G = graphs[M_RHO]
    N = G["N"]
    rng2 = np.random.default_rng(MASTER_SEED + 1)
    U = [rng2.random(N) for _ in range(SEEDS)]
    cache = {}

    def rho_at(p):
        key = round(p, 12)
        if key not in cache:
            b1 = np.zeros(SEEDS); br = np.zeros(SEEDS)
            for s in range(SEEDS):
                o = PC.analyse(G, U[s] < p, Q_B, C_B)
                b1[s], br[s] = o["b1_C"], o["berry"]
            rho = EPS_V / N * (b1 + br)
            cache[key] = (b1.mean(), b1.std(), EPS_V / N * br.mean(), rho.mean(),
                          float(np.mean((rho >= WINDOW[0]) & (rho <= WINDOW[1]))))
        return cache[key]

    w("## 5. Candidate vacua (m = %d sphere, L^d = N = %d, %d seeds each, common random numbers)" % (M_RHO, N, SEEDS))
    w("")
    w("Window [assumed input]: %.3f <= rho_res <= %.3f E_* per lattice cell. Frozen = reached by the roll AND in window." % WINDOW)
    w("")
    w("### 5a. Vacua reached by the roll")
    w("")
    w("| beta | g | phi_0 | phi_stop | p | b_1(C) mean (std) | Berry part | rho_res | in-window | seeds in window | frozen |")
    w("|---|---|---|---|---|---|---|---|---|---|---|")
    frozen = []
    default_records = []
    for s, x0, xf in reached:
        p = p_of_phi(xf)
        b1m, b1s, brm, rho, fr = rho_at(p)
        inw = WINDOW[0] <= rho <= WINDOW[1]
        default_records.append({
            "id": "beta=%g g=%g phi0=%g -> phi=%.4f" % (s["beta"], s["g"], x0, xf),
            "beta": s["beta"], "g": s["g"], "phi0": x0, "phi_stop": xf,
            "p": p, "rho_res": float(rho), "field_content": None, "spectrum": None,
        })
        if inw:
            frozen.append((s["beta"], s["g"], x0, xf, rho))
        w("| %g | %g | %g | %.4f | %.4f | %.2f (%.2f) | %.2e | %.5f | %s | %.2f | %s |" % (
            s["beta"], s["g"], x0, xf, p, b1m, b1s, brm, rho, yn(inw), fr, "YES (phi frozen at %.4f)" % xf if inw else "NO (not populated)"))
    w("")
    w("### 5b. Every local minimum in [%g, %g] (reached or not)" % (LO, HI))
    w("")
    w("| beta | g | phi_min | p | b_1(C) mean | rho_res | in-window | reached from some phi_0 | frozen |")
    w("|---|---|---|---|---|---|---|---|---|")
    n_all = n_inw = 0
    inw_ps = []
    for s in sets:
        if not s["ok"]:
            continue
        stops = [xf for (_, xf) in s.get("stops", [])]
        for xm in s["mins"]:
            p = p_of_phi(xm)
            b1m, b1s, brm, rho, fr = rho_at(p)
            inw = WINDOW[0] <= rho <= WINDOW[1]
            rc = any(abs(xm - xs) < 1e-6 for xs in stops)
            n_all += 1; n_inw += int(inw)
            if inw:
                inw_ps.append(p)
            w("| %g | %g | %.4f | %.4f | %.2f | %.5f | %s | %s | %s |" % (s["beta"], s["g"], xm, p, b1m, rho, yn(inw), yn(rc), yn(inw and rc)))
    w("")
    w("Summary [computed]: %d parameter sets can settle; %d vacua reached; %d local minima in total, %d of them in "
      "the window; frozen vacua: %d." % (sum(1 for s in sets if s["ok"]), len(reached), n_all, n_inw, len(frozen)))
    if inw_ps:
        lo_side = [x for x in inw_ps if x < 0.75]; hi_side = [x for x in inw_ps if x >= 0.75]
        w("In-window minima sit at p in [%.3f, %.3f] (rising side of the b_1 curve, %d minima) and p in [%s] "
          "(falling side near p = 1, where holes fill in, %d minima) [computed]." % (
              min(lo_side) if lo_side else float("nan"), max(lo_side) if lo_side else float("nan"), len(lo_side),
              ("%.3f, %.3f" % (min(hi_side), max(hi_side))) if hi_side else "-", len(hi_side)))
    w("In-window minima exist near phi = -10.3 to -10.8 and -19.5 to -19.6 (p = 0.51-0.54 and 0.97-0.98), which starts at 0, -7 and -14 never reach [depends on phi0 choice].")
    if frozen:
        w("Frozen: " + "; ".join("beta=%g g=%g phi_0=%g -> phi=%.4f (rho_res=%.4f)" % f for f in frozen))
    w("")

    # ================= 6. Post-hoc parameter scan and Job Two hook =================
    w("## 6. Post-hoc parameter scan and surviving-vacua hook [post-hoc]")
    w("")
    w("Default surviving vacua [hook, computed]: %s" % format_vacua(surviving_vacua(default_records)))
    w("The default result remains 0 frozen vacua: barriers determine which stops are reached; the Betti/Berry filter only labels a reached stop by rho_res.")
    w("Hook: surviving_vacua(vacua, rho_window=WINDOW, spectrum_filter=None); --vacua-json PATH accepts a JSON list carrying rho_res, field_content, and spectrum [post-hoc].")
    w("Input provenance [post-hoc]: Akitti's posts define qualitative scars/MBL and a narrow structure-formation window, but not these numeric window bounds, p(phi), phi_0, k, or a Berry formula. The numerical window, clip(-phi/20), starts, m=16 observable, and all scan maps below are [assumed input].")
    w("Reference values [Akitti post, borrowed value; read-only X_WINDOW_DEFS.md]: p_c = 0.5 (site, this toy), 0.7055 (DK), and 0.38 (3D bond-DP); the source says \"Above p_c scars survive ... below it ... MBL\". Scar floor ~0.041 is also quoted there. These borrowed p_c values are not tied to V(phi).")
    w("The optional CSK theta-lock term mentioned in X_WINDOW_DEFS.md is not used; V(phi) is unchanged [assumed input].")
    scan_scales = (15.0, 20.0, 25.0)
    scan_rhos = {}
    for scale in scan_scales:
        scan_rhos[scale] = {}
        for record in default_records:
            scan_rhos[scale][record["id"]] = float(rho_at(p_of_phi(record["phi_stop"], scale))[3])
    scan_specs = [
        ("default", 20.0, 0.020, 0.010, tuple(PHI0S)),
        ("scale-15", 15.0, 0.020, 0.010, tuple(PHI0S)),
        ("scale-15-narrow", 15.0, 0.020, 0.005, tuple(PHI0S)),
        ("scale-15-high-centre", 15.0, 0.025, 0.010, tuple(PHI0S)),
        ("scale-15-start-minus-7", 15.0, 0.020, 0.010, (-7.0,)),
        ("scale-25", 25.0, 0.020, 0.010, tuple(PHI0S)),
    ]
    scan_results = {}
    w("| scan | occupancy scale | centre | half-width | phi_0 starts | candidates | surviving | filtered |")
    w("|---|---:|---:|---:|---|---:|---:|---:|")
    for name, scale, centre, halfwidth, starts in scan_specs:
        lo_scan, hi_scan = centre - halfwidth, centre + halfwidth
        records = []
        for record in default_records:
            if record["phi0"] not in starts:
                continue
            r = dict(record)
            r["p"] = p_of_phi(r["phi_stop"], scale)
            r["rho_res"] = scan_rhos[scale][r["id"]]
            records.append(r)
        survivors = surviving_vacua(records, (lo_scan, hi_scan))
        scan_results[name] = (records, survivors, (lo_scan, hi_scan), scale)
        w("| %s | %.1f | %.3f | %.3f | %s | %d | %d | %d |" % (
            name, scale, centre, halfwidth, ",".join(str(x) for x in starts), len(records), len(survivors), len(records)-len(survivors)))
    selected_records, selected_survivors, selected_window, selected_scale = scan_results["scale-15"]
    w("")
    w("Selected scan choice [post-hoc]: occupancy scale = 15, window = [%.3f, %.3f], starts = 0, -7, -14." % selected_window)
    w("Surviving vacua [hook, computed]: %s" % format_vacua(selected_survivors))
    selected_ids = {v["id"] for v in selected_survivors}
    w("")
    w("Scar-threshold cross-check on selected scan [post-hoc]: survivors require the rho window and p >= p_c.")
    w("| reference | threshold | survivors | surviving-vacua list |")
    w("|---|---:|---:|---|")
    for label, threshold in (("site (ours), [Akitti post, borrowed value]", 0.5), ("DK, [Akitti post, borrowed value]", 0.7055), ("3D bond-DP, [Akitti post, borrowed value]", 0.38)):
        ref_survivors = [v for v in selected_records if v["id"] in selected_ids and v["p"] >= threshold]
        w("| %s | %.4f | %d | %s |" % (label, threshold, len(ref_survivors), format_vacua(ref_survivors)))
    floor_survivors = [v for v in selected_records if v["rho_res"] >= 0.041 and v["rho_res"] <= WINDOW[1]]
    w("| scar floor, [Akitti post, borrowed value] | rho_res >= 0.041 | %d | %s |" % (len(floor_survivors), format_vacua(floor_survivors)))
    w("The ~0.041 scar floor is above the assumed rho upper edge 0.030, so that borrowed threshold and this window have no overlap; it cannot select a survivor without changing an assumed input.")
    for record in selected_records:
        why = "survives: rho_res is inside the scan window" if record["id"] in selected_ids else "filtered out: rho_res is outside the scan window"
        w("- %s: p=%.4f, rho_res=%.5f; %s." % (record["id"], record["p"], record["rho_res"], why))
    w("Separation [post-hoc]: the barriers/dynamics select the reached stops; the Betti/Berry filter does not move the field and only labels them. Job Two RESULTS_final.md was read read-only and its spectrum is carried in the grid records; no Job Two file or table was changed.")
    w("Four causes of the empty default [post-hoc diagnosis]: (1) first-barrier stopping is by construction, so the filter cannot make the field cross a barrier; (2) the phi_0 grid never reaches the in-window minima, while the scan shows that changing starts/map can discriminate; (3) raw b_1 is extensive, so an intensive b_1 per face or largest-cluster share is the appropriate future observable, not a silent default change; (4) the m=16 Berry term is about 6.9e-6 versus a 1e-2 window edge, so it cannot change selection at this precision.")

    # Job Two remains read-only/absent; this is an explicit assumed alt-model grid,
    # not a claim about the final model file.
    w("")
    w("### Job Two alt-model grid [post-hoc; assumed input, read-only]")
    w("Model content [Job Two RESULTS_final.md, read-only]: scalar Higgs on S2; at n=3, x=+/-1 gives three generations; the Higgs has one constant mode plus l(l+1)/R^2 tower; lowest fermion KK level is sqrt(|n|+1)/R; Yukawas are diagonal 1/(2*sqrt(pi)) while SO(3) holds; U(1)_X anomaly totals scale with n.")
    w("Explicit map [assumed input]: p(n,R) = clip((|n|/3)*(1/R)^2, 0, 1), using flux density n/R^2 normalized to the Job Two n=3,R=1 point; b_1(n,R) = mean raw m=16 b_1(C) at p(n,R); rho_res is then the same m=16 Betti+Berry estimator used above. This map is not supplied by Job Two.")
    w("p(n,R) = n/(3R^2) [identity, unclipped range]: the map sees only n/R^2, so it cannot distinguish fluxes at fixed n/R^2. Therefore (n=1,R=0.8) and (n=4,R=1.6) must have identical p, b_1 and rho_res under this assumed map.")
    w("n/R^2 is the flux density: on S^2, B is proportional to n/R^2, so this occupancy map is really a map of magnetic field strength on the sphere [assumed input].")
    w("n and R are not independent in a real solution: in an RSS-type Einstein-Maxwell flux compactification, the field equations fix R once the flux and 6D couplings (gauge coupling, Lambda_6, Planck scale) are given. R is the radion set by the solution, not a free knob [standard, not computed].")
    w("Therefore scanning R at fixed n scans 6D coupling choices, and the R-bands per n are bands of coupling choices. Radion stability remains [not checked] in Job Two; the R grid is an [assumed input: off-shell scan].")

    def rho_crossing(a, b, target):
        fa = rho_at(a)[3] - target
        fb = rho_at(b)[3] - target
        if fa == 0.0:
            return a
        if fb == 0.0:
            return b
        if fa * fb > 0.0:
            return 0.5 * (a + b)
        for _ in range(24):
            mid = 0.5 * (a + b)
            fm = rho_at(mid)[3] - target
            if fa * fm <= 0.0:
                b, fb = mid, fm
            else:
                a, fa = mid, fm
        return 0.5 * (a + b)

    def rho_window_bands():
        # Coarse p probes locate each band; rho_crossing then refines its edges.
        bands = []
        for p_lo_probe, p_hi_probe, dp in ((0.45, 0.57, 0.002), (0.95, 0.999, 0.001)):
            probes = list(np.arange(p_lo_probe, p_hi_probe + 0.5 * dp, dp))
            vals = [rho_at(float(q))[3] for q in probes]
            inside = [WINDOW[0] <= q <= WINDOW[1] for q in vals]
            i = 0
            while i < len(probes):
                if not inside[i]:
                    i += 1
                    continue
                j = i
                while j + 1 < len(probes) and inside[j + 1]:
                    j += 1
                if i == 0:
                    left = probes[i]
                else:
                    target = WINDOW[0] if vals[i - 1] < WINDOW[0] else WINDOW[1]
                    left = rho_crossing(float(probes[i - 1]), float(probes[i]), target)
                if j == len(probes) - 1:
                    right = probes[j]
                else:
                    target = WINDOW[0] if vals[j + 1] < WINDOW[0] else WINDOW[1]
                    right = rho_crossing(float(probes[j]), float(probes[j + 1]), target)
                bands.append((left, right))
                i = j + 1
        return bands

    rho_p_bands = rho_window_bands()
    w("Analytic R-bands [computed from the map]: invert p = n/(3R^2) at the code-derived rho-window p edges.")
    w("| band | p_lo from rho(p) | p_hi from rho(p) |")
    w("|---|---:|---:|")
    for ib, (plo, phi) in enumerate(rho_p_bands, 1):
        w("| band %d | %.6f | %.6f |" % (ib, plo, phi))
    w("| flux n | R interval for band 1 | R interval for band 2 |")
    w("|---:|---|---|")
    for flux_n in (1, 2, 3, 4):
        intervals = ["[%.6f, %.6f]" % (math.sqrt(flux_n / (3.0 * phi)), math.sqrt(flux_n / (3.0 * plo))) for plo, phi in rho_p_bands]
        w("| %d | %s | %s |" % (flux_n, intervals[0] if intervals else "-", intervals[1] if len(intervals) > 1 else "-"))
    if rho_p_bands:
        expected_n2 = (1.11, 1.17)
        expected_n3 = (1.36, 1.43)
        actual_n2 = (math.sqrt(2.0 / (3.0 * rho_p_bands[0][1])), math.sqrt(2.0 / (3.0 * rho_p_bands[0][0])))
        actual_n3 = (math.sqrt(3.0 / (3.0 * rho_p_bands[0][1])), math.sqrt(3.0 / (3.0 * rho_p_bands[0][0])))
        n2_ok = max(abs(actual_n2[0] - expected_n2[0]), abs(actual_n2[1] - expected_n2[1])) < 0.02
        n3_ok = max(abs(actual_n3[0] - expected_n3[0]), abs(actual_n3[1] - expected_n3[1])) < 0.02
        w("Venus band checks [computed comparison]: n=2 actual [%.6f, %.6f] vs estimate [1.11, 1.17] (%s); n=3 actual [%.6f, %.6f] vs estimate [1.36, 1.43] (%s)." % (actual_n2[0], actual_n2[1], "agrees" if n2_ok else "DISAGREES", actual_n3[0], actual_n3[1], "agrees" if n3_ok else "DISAGREES"))
        if len(rho_p_bands) > 1:
            actual_n3_narrow = (math.sqrt(3.0 / (3.0 * rho_p_bands[1][1])), math.sqrt(3.0 / (3.0 * rho_p_bands[1][0])))
            narrow_ok = max(abs(actual_n3_narrow[0] - 1.009), abs(actual_n3_narrow[1] - 1.013)) < 0.002
            w("n=3 narrow band [computed from the map]: %.6f–%.6f (supersedes the hand estimate ≈1.009–1.013 from rounded rows)." % (actual_n3_narrow[0], actual_n3_narrow[1]))
    job2 = []
    for flux_n in (1, 2, 3, 4):
        for radius_R in (0.8, 1.0, 1.2, 1.4, 1.6):
            p_job = job_two_assumed_map(flux_n, radius_R)
            b1_job, _b1s_job, _berry_job, rho_job, _frac_job = rho_at(p_job)
            job2.append({
                "id": "n=%g R=%.1f" % (flux_n, radius_R),
                "flux_n": flux_n, "radius_R": radius_R, "p": p_job,
                "b1": float(b1_job), "rho_res": float(rho_job),
                "field_content": {
                    "scalar": "Higgs", "compactification": "S2", "flux_n": flux_n,
                    "zero_modes_per_x1_fermion": abs(flux_n),
                    "higgs_constant_mode": True,
                    "higgs_tower_mass2_l1": "mu^2 + 2/R^2",
                },
                "spectrum": {
                    "model": "Job Two alt", "scalar": "Higgs", "flux_n": flux_n,
                    "radius_R": radius_R, "generations": abs(flux_n),
                    "lowest_fermion_KK": "sqrt(|n|+1)/R",
                    "yukawa_diagonal": "1/(2*sqrt(pi))", "SO3": True,
                    "anomaly_totals_assumed_scale_with_n": True,
                    "anomaly_SU2sqX": 4 * flux_n, "anomaly_YsqX": -2 * flux_n,
                },
            })
    job2_rho_survivors = surviving_vacua(job2, WINDOW)
    job2_survivors = surviving_vacua(job2, WINDOW, spectrum_filter=lambda _fc, sp, v: (
        v["flux_n"] == 3 and sp.get("generations") == 3))
    w("| flux n | R | p | raw b_1(C) | rho_res | rho window | n=3 spectrum |")
    w("|---:|---:|---:|---:|---:|---|---|")
    for v in job2:
        w("| %g | %.1f | %.4f | %.2f | %.5f | %s | %s |" % (v["flux_n"], v["radius_R"], v["p"], v["b1"], v["rho_res"], yn(v in job2_rho_survivors), yn(v in job2_survivors)))
    w("Rho-window survivors before spectrum compatibility [hook, computed]: %s" % format_vacua(job2_rho_survivors))
    w("Rho-window count = %d [grid-step]: the R step of 0.2 skips n=2's analytic band entirely and n=3's second band." % len(job2_rho_survivors))
    pc_half_survivors = [v for v in selected_records if v["id"] in selected_ids and 0.5 <= v["p"] < 0.6]
    if pc_half_survivors:
        p_survive = [v["p"] for v in pc_half_survivors]
        w("p_c = 1/2 threshold calls [finite-size]: selected-scan rho survivors have p in [%.6f, %.6f], inside the finite-size smearing of the m=16 step." % (min(p_survive), max(p_survive)))
    w("n = 3 is picked by the three-generation spectrum check, not by the filter [by construction]. R ~= 1.4 is just where the assumed normalisation puts p near 1/2 [assumed input].")
    w("Final surviving vacua [Job Two alt grid + n=3/three-generation spectrum hook, computed]: %s" % format_vacua(job2_survivors))
    w("These Job Two rows are assumed-input probes; RESULTS_final.md was read-only and no Job Two file or table was changed.")
    if args.vacua_json:
        with open(args.vacua_json, "r", encoding="utf-8") as fh:
            cli_vacua = json.load(fh)
        lo_cli = WINDOW[0] if args.rho_lo is None else args.rho_lo
        hi_cli = WINDOW[1] if args.rho_hi is None else args.rho_hi
        cli_survivors = surviving_vacua(cli_vacua, (lo_cli, hi_cli))
        w("CLI hook surviving vacua [post-hoc, computed]: %s" % format_vacua(cli_survivors))
    w("")
    w("## 7. Plain statement")
    w("")
    w("Which vacua are kept depends on the assumed inputs: the occupancy map p(phi), the starting points, the window, "
      "k, L, d and the Berry term. None of these comes from Akitti's posts. The field stops because of ordinary "
      "barriers; the Betti filter only labels the stops. This is not a solution to vacuum selection or to the "
      "cosmological-constant problem.")
    w("0 frozen vacua [assumed-input dependent; depends on phi0 choice]. The barriers do the selecting, and the Betti filter only labels stops. Lambda_0 is not cancelled.")
    w("")
    after = {f: sha(os.path.join(HERE, f)) for f in FOREIGN}
    w("Foreign input files unchanged by this run: %s (SHA-256 after: %s)." % (
        yn(after == before), "; ".join("%s %s" % (f, h[:16].upper()) for f, h in after.items())))
    with open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
